### ISSUE TITLE
[Cloud Posture] Cloubeat Error logs Partition error: File system error after CNVM integration installed

### ISSUE THREAD

**Issue by Omolola-Akinleye** [elastic/cloudbeat#1008]
**Describe the bug**
Write a detailed description of the observed behavior using the actions you performed.
 After installing cnvm integration, under cloudbeat.errors logs, I see the following error
`[elastic_agent.cloudbeat][error] 2023-05-25T15:33:08.190Z	[33mWARN[0m	Partition error: filesystem error: unexpected fs error: new xfs filesystem error: failed to parse primary allocation group: failed to parse agf magic byte error: 00000000`

**Preconditions**
[Environment Access](https://p.elstc.co/paste/3Z-V5+uz#+idqWItbzHCf5c3wOhXuYYrCuiiMd5WORPUD2KpiFMk)

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Install CNVM Integration
2. Go to  Fleet -> Agents -> 
3. Click the Vuln-mgmt integration hostname
4. Go logs and filter  Dataset by `elastic_agent.cloudbeat` and Log Level by `errors`

You should see

`[elastic_agent.cloudbeat][error] 2023-05-25T15:33:08.190Z	[33mWARN[0m	Partition error: filesystem error: unexpected fs error: new xfs filesystem error: failed to parse primary allocation group: failed to parse agf magic byte error: 00000000`

**Expected behavior**
Remove error above

**Comment by oren-zohar** [comment]
@amirbenun is this related to the XFS issue we already saw? do you think it will be solved in the new Trivy version fix?

**Comment by amirbenun** [comment]
Yes, it seems like this going to be fixed by https://github.com/elastic/cloudbeat/pull/1035.
To verify that this is the case, @Omolola-Akinleye, can you please provide more logs?
In particular, I care about the instance ID that cloudbeat started to scan right before this error message.
Next I will check, if that instance was created from AL2023 AMI.

**Comment by kfirpeled** [comment]
Closed - verify on next bc

**Comment by olegsu** [comment]
verified


![Image](https://github.com/elastic/cloudbeat/assets/23185631/7f7885cf-6cff-49cb-a3e2-5648ac63bd12)
