### ISSUE TITLE
[BUG] Kibana - Cloud Security - Browser's Tab title is not according to Kibana's standard

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#103]
**Describe the bug**
In the `Cloud Security` section, the tab's title is not according to Kibana's standard.

**Preconditions**
Install Kibana.

**To Reproduce**
1. Navigate to the Cloud security page.
2. Observe the tab's title - `Elastic`

**Expected behavior**
Tab's title should be `Cloud Security - Elastic` according to the rest of the pages, e.g the `Discover` page.

Kibana Version: 8.3.0-SNAPSHOT

**Comment by tehilashn** [comment]
@uri-weisman - can you please add a screenshot?

**Comment by kfirpeled** [comment]
Adding another screenshot 📸

![Screen Shot 2022-05-12 at 17 29 43](https://user-images.githubusercontent.com/61654899/168099170-524e3ced-7873-439c-a4d4-6d8a09e26c6a.png)

**Comment by orouz** [comment]
PR - https://github.com/elastic/kibana/pull/133618

**Comment by amirbenun** [comment]
Can we close this? @orouz
