### ISSUE TITLE
Functional tests are failing randomly with the error message "int too large to convert to float"

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#1030]
Functional tests are failing with the error message "int too large to convert to float" during the post-merge K8s job when trying to retrieve events from Elasticsearch.

[Failed run example](https://github.com/elastic/cloudbeat/actions/runs/5196431167/jobs/9370183571)

**Comment by oren-zohar** [comment]
Closing in favor of migration to the new testing format
