### ISSUE TITLE
[AWS Orgs] Call fetchers for each account

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1039]
**Motivation**

**Definition of done**
What needs to be completed at the end of this task
- [ ] List all accounts in the current organization
- [ ] For each account: 
  - [ ] assume role
  - [ ] call AWS fetchers

**Out of scope**
What should not be included in this task

**Related tasks/epics**
- https://github.com/elastic/cloudbeat/issues/982
- https://github.com/elastic/cloudbeat/issues/756

**Comment by CohenIdo** [comment]
8.10.0 BC1 QA Cycle - verified: 

aws organizations list: 


![Image](https://github.com/elastic/cloudbeat/assets/90558359/70303916-7cdb-4942-89ad-576a3dfafb65)

CSPM dashboard with all the organizations:


![Image](https://github.com/elastic/cloudbeat/assets/90558359/2361f666-c03d-4d38-82a3-4e3480236326)
