### ISSUE TITLE
[CNVM] Integration test (cloudbeat binary + AWS)

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1088]
### Motivation
As a **premerge** test, an integration test of cloudbeat binary with a test AWS account can get us a great coverage of the cloudbeat functionality.

### Components
- Standalone Cloudbeat binary
- AWS test account
- Elasticsearch

### Test flow
- Cloudbeat runs vulnerability management flow
- Scan a specific region in our AWS account with no instances (to reduce costs)
- Assert for vulnerabilities in ES

### Related tasks/epics
- https://github.com/elastic/cloudbeat/issues/700
- https://github.com/elastic/cloudbeat/issues/1089

**Comment by amirbenun** [comment]
When running the Cloudbeat CNVM on a Github action instance we get the following error:
```
Exiting: beater returned an error: VulnerabilityWorker: could not get init NewVulnerabilityRunner: DB error: failed to download vulnerability DB: database download error: oci download error: download error: failed to download: chtimes db/trivy.db: operation not permitted
```

Which must be related to https://github.com/elastic/cloudbeat/issues/731 and the fact that we have a limitation today running CNVM on AMD processors and it only works on ARM.

**Comment by oren-zohar** [comment]
@amirbenun we can change the runner image, no?

**Comment by amirbenun** [comment]
I will try using `macos-12-xl` but it's also amd based.
![image](https://github.com/elastic/cloudbeat/assets/34831306/de09b059-4687-4a31-8c0c-04972e682dae)

**Comment by oren-zohar** [comment]
are those running on ARM? [maybe they still don't have Apple silicon Github runners](https://github.com/github/roadmap/issues/528)

**Comment by amirbenun** [comment]
Moving the task to block and trying to resolve https://github.com/elastic/cloudbeat/issues/731
