### ISSUE TITLE
CloudFormation Integration test

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1089]
### Motivation
As a **premerge** test, an integration test of deploying an elastic-agent with the CloudFormation template can bring a a great coverage to the CloudFormation deployment method.

### Components
- ESS stack
- AWS test account

### Test flow
This test should only run on PRs where the CloudFormation template has been modified
- Creating an agent policy with the CNVM/CSPM integration
- Deploy the relevant CloudFormation stack on an AWS test account
- Make sure an agent has enrolled to the fleet
- By default, don't wait for vulnerabilities (to reduce test duration)

### Related tasks/epics
- https://github.com/elastic/cloudbeat/issues/700
- https://github.com/elastic/cloudbeat/issues/1088

**Comment by oren-zohar** [comment]
@amirbenun @gurevichdmitry Another step in this test should be resource clean-up IMO. This would mean we'd still need to wait for the setup to finish, so either the cleanup step would be at the end, or we could use some AWS lifecycle management feature instead.

**Comment by amirbenun** [comment]
@oren-zohar Do you mean cleaning the CloudFormation resources?

**Comment by amirbenun** [comment]
Since the elastic-agent installation success is a condition for the CloudFormation deployment (as part of [CloudFormation deployment: Rollback deployment if agent installation fails](https://github.com/elastic/cloudbeat/issues/1105#top)).
We can use `aws cloudformation wait stack-create-complete` to make sure that deployment succeed which will promise the successful installation of elastic-agent.

**Comment by amirbenun** [comment]
The github workflow expects `TF_VAR_ec_api_key` secret In order to create an ESS environment.
The API key should be generated on a shared Elastic Cloud account.
Moving this task to block until the following is completed:
- https://github.com/elastic/cloudbeat/issues/1231

**Comment by amirbenun** [comment]
To move on with this task and not to block it, we will use a temporary `EC_API_KEY` secret.
