### ISSUE TITLE
[BUG] Kibana - Rule Flyout - flyout is closing when clicking on kibana's searchbar

### ISSUE THREAD

**Issue by JordanSh** [elastic/cloudbeat#109]
**Describe the bug**
While rule flyout is open, clicking on the search bar in kibana will close the flyout

**Preconditions**
Have rules in the rule page 

**To Reproduce**
open a rule flyout
click on the search bar while the flyout is open

**Expected behavior**
for example, in discover page, the flyout stays open and the search is still functional 

**Screenshots**

https://user-images.githubusercontent.com/51442161/167644602-09e6416b-6bb0-4690-bdef-39c168678d49.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Kibana Version: 8.3-SNAPSHOT
 - SHA: df225b213b188c81888141cee2ec191424fc0649

**Comment by kfirpeled** [comment]
@oren-zohar , this is not part of the BC, fyi

**Comment by JordanSh** [comment]
QA Cycle 1: passed
OS: MacOS
Browser: Chrome
Kibana Version: 8.4 latest BC1
SHA: 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d
