### ISSUE TITLE
[CNVM] Vulnerability flavor context cancelation causes deadlock

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1097]
### Describe the bug
When cloudbeat get a configuration update, the launcher has to kill the current flavor and recreate one instead.
In practice, the vulnerability flavor enters a deadlock and you will never get vulnerabilities.

### Technical explanation
The vulnerability worker is in charge on the asynchronous pipeline of:
Listing EC2s -> Creating Snapshots -> Scan -> Send vulnerabilities.
When the context is canceled, trivy returns an error and the scanner stops listening to the incoming channel.
All other providers are waiting to send their data to the next provider in the pipeline, but since no one reads it causes a deadlock.

### Preconditions
Any version > 8.9.0 of ESS

### To Reproduce
Run Cloudbeat with the CNVM integration installed
Change the integration name to trigger a configuration update

### Expected behavior
To get vulnerabilities

**Comment by oren-zohar** [comment]
@amirbenun did it also happen on 8.8?

**Comment by amirbenun** [comment]
Yes, we should discuss if we want to backport it to 8.8.
@tehilashn what do you think?

**Comment by tehilashn** [comment]
I purpose we'll backport this to 8.8 anyway. If there will be another 8.8 release then the fix will be there.

**Comment by amirbenun** [comment]
Sounds good @tehilashn.
I opened a PR with the backport to 8.8
https://github.com/elastic/cloudbeat/pull/1116

**Comment by kfirpeled** [comment]
Verify by looking for errors in cloudbeat logs after a fresh deployment (0 errors)

**Comment by Omolola-Akinleye** [comment]
I see one error @oren-zohar  @amirbenun 
```
20:08:24.595
elastic_agent.cloudbeat
[elastic_agent.cloudbeat][error] VulnerabilityScanner.scan.ScanVM error: scan error: scan failed: failed analysis: inspection error: post analysis error: post analysis error: walk dir error: walk error: context canceled
```
