### ISSUE TITLE
[BUG] Kibana - Benchmarks - Invalid Rows Per Page 

### ISSUE THREAD

**Issue by orouz** [elastic/cloudbeat#110]
**Describe the bug**

the "rows per page" dropdown includes 3 options: 10, 25, 50
but we initialize it with 5, so when the dropdown is opened, there isn't a currently-selected option

**Preconditions**
- CIS integration installed

**To Reproduce**

1. go to Cloud Posture -> My Benchmarks
2. open the 'rows per page" dropdown
3. the option '5' is not listed, but page shows 5 per page

**Expected behavior**

the selected rows-per-page value is highlighted as active in the menu options

**Screenshots**
![Screen Shot 2022-05-10 at 17 06 42](https://user-images.githubusercontent.com/20814186/167648764-a7387922-306e-4aa1-96ff-a19b9dd455b8.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: `df225b213b188c81888141cee2ec191424fc0649`
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by tehilashn** [comment]
on the latest Kibana snapshot is seems to be fine:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/85991751/168014375-0b54d438-b5a0-479f-a5b5-86d9248f1484.png">

**Comment by orouz** [comment]
PR 
- https://github.com/elastic/kibana/pull/133370

**Comment by kfirpeled** [comment]
approved

**Comment by kfirpeled** [comment]
merged
