### ISSUE TITLE
[CNVM] Cost estimation for GA

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1117]
**Motivation**
We would like to provide customers with a ballpark estimate of the costs associated with CNVM usage.
One of the GA tasks on the list:
- https://github.com/elastic/security-team/issues/6844

**Definition of done**
What needs to be completed at the end of this task
- [ ] The customer should be able to know the cost ballpark of the integration

**Comment by jeniawhite** [comment]
The cost aspect of CNVM is the following:
- Running the scanner's EC2 instance
- Downloading/updating the Vulnerabilities database (network traffic outside of AWS)
- Fetching scanner's region EC2 instances
- Creation/deletion of EBS snapshots
- Listing and reading of EBS snapshot blocks
- Reporting vulnerabilities to ElasticSearch (network traffic)
- Vulnerabilities documents store cost in ElasticSearch
 
**Notice that these prices will change according to the `region` that the customer decides to deploy on.**
**The following prices are for region `us-west-1`**
**Customer might have contracts with AWS with different prices, the prices here are from reading the documentation and using the [AWS calculator](https://calculator.aws/#/addService/EBS)**

**Scanner:**
The default instance is `c6g.xlarge`.
```yaml
InstanceType:
    Type: String
    Default: c6g.xlarge
    AllowedValues:
      - c6g.xlarge
      - c6g.2xlarge
      - c6g.4xlarge
```
Looking at the prices for **on-demand** instances **per month assuming that we are running without stopping**:
<img width="776" alt="Screen Shot 2023-07-06 at 14 14 56" src="https://github.com/elastic/cloudbeat/assets/12246907/f90b7d93-0ccd-4458-93d2-cd3f4c95d14b">
We also attach an EBS volume for the instance of `32GB`:
```json
BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 32
```
<img width="479" alt="Screen Shot 2023-07-06 at 14 27 42" src="https://github.com/elastic/cloudbeat/assets/12246907/dc6bb05e-dde2-46bd-a679-f7cbce048791">

**Downloading/updating the Vulnerabilities database:**
This depends on the database size but currently the size is `379.551744MB`:
```
Evgbs-MacBook-Pro:cloudbeat evgb$ ls -ltr db/
total 741320
-rw-------  1 evgb  staff  379551744 Jul  6 09:11 trivy.db
```
This database is also being updated and cache invalidated periodically.
From the documentation the costs of sending these requests are basically 0$, because we are downloading the database not not uploading it (**database is going IN and the request to get it is OUT**).
<img width="892" alt="Screen Shot 2023-07-06 at 14 49 07" src="https://github.com/elastic/cloudbeat/assets/12246907/640bb11e-0d59-49cd-ad5e-79bbc2fce8f1">

**Fetching scanner's region EC2 instances:**
This should be also 0$, because we are querying from within the same region and we have no costs.
Assuming there are no costs for querying the EC2 instances (describe), I did not find any costs regarding these API calls.

**Creation/deletion of EBS snapshots:**
We are scanning once a day, which means that we are creating a snapshot for every EC2 instance volume once a day.
Assuming that the volume size is 30GB and it is being replicated once a day fully.
We get the following cost per month:
<img width="478" alt="Screen Shot 2023-07-06 at 15 02 46" src="https://github.com/elastic/cloudbeat/assets/12246907/bd6dae88-289d-4aa1-bed3-753711aace28">
**Notice that this is a calculation per one EBS snapshot per month**
This needs to be multiplied and changed according to customer's region's volumes.
We also delete the created snapshots at the end of scanning cycle each day, not sure if this lowers the cost because essentially the snapshots are alive only for the scanning timeframe.

**Listing and reading of EBS snapshot blocks:**
These are the costs of EBS `GetSnapshotBlockAPI`, `ListSnapshotBlocks`, `PutSnapshotBlock` (**each unit is 1000 requests**).
<img width="750" alt="Screen Shot 2023-07-06 at 15 13 39" src="https://github.com/elastic/cloudbeat/assets/12246907/f2ce5cfe-df8f-415e-b089-60ab42afd20e">
Because we've calculated the cost of creation above we will ignore the `PutSnapshotBlock` cost.
**Assuming that we are scanning a single EBS snapshot of 30GB once a day for a month**
This is the cost breakdown:
- GetSnapshotBlock API request uses a block size of 512KiB
- 30GB is 3e+7KiB which means 58593.75 requests to read this snapshot
- 58593.75 multiplied by 30 (amount of days in a month) is 1757812.5 requests
- Because the requests are being calculated per thousand requests if we divide this we get 1757.8125 units
- This means that it would cost us:
![Uploading Screen Shot 2023-07-06 at 15.20.46.png…]()
**This doesn't include the listing of blocks for each snapshot, this needs to be calculated according to number of snapshots via the formula mentioned above**

**Reporting vulnerabilities to ElasticSearch (network traffic):**
This is similar to the downloading of vulnerabilities database, but this point depends on the location of the ElasticSearch cluster.
If it is deployed in the same region as the scanner then there will be no extra costs.
If it is deployed in other regions then the cost is usually around 0.02$ per GB (depends on regions).
If it is deployed outside of AWS then we will use the OUT costs
<img width="884" alt="Screen Shot 2023-07-06 at 15 29 23" src="https://github.com/elastic/cloudbeat/assets/12246907/cb3e9409-d86d-4bf5-9deb-bc85064225bb">
In the next bullet I've calculated the average amount of space that a single vulnerability consumes and it is **~2KiB**.
The amount of data that is being sent is dependent on the amount of vulnerabilities found in the region by the scanner, multiple the above number and then get an estimation on the traffic cost dependent on your deployment scenario.
**Note that I'm not calculating the cost of logs for `cloudbeat` process**.

**Vulnerabilities documents store cost in ElasticSearch:**
Every vulnerability found is a document inside ElasticSearch, because there are different types of vulnerabilities this means that each document size is different dependent of the vulnerability and scanned EBS, instance metadata.
Looking at the vulnerabilities in our development cluster, the average document size is around **~2KiB**.
We also have the `latest` index transform which should eliminate non-unique documents.
Assuming that everything is unique we would consume another **~2KiB** for the `latest` index.
Which means that we consume **~4KiB** per vulnerability document.
**Note that I'm not calculating the cost of logs for `cloudbeat` process**.

@nick-alayil I hope that this gives you more clarity, let me know if this needs to be elaborated further.

**Comment by nick-alayil** [comment]
>@nick-alayil I hope that this gives you more clarity, let me know if this needs to be elaborated further.

Thank you @jeniawhite for providing an excellent in-depth analysis of CNVM cost estimation. It was precisely what I needed. We'll share the cost estimation results and discuss them with the team during our upcoming CNVM product sync.

**Comment by jeniawhite** [comment]
Looking at our development cluster costs for `CreateSnapshot` API call, we see a different amount.
![image](https://github.com/elastic/cloudbeat/assets/12246907/ec9e1aca-e5c1-41c0-b8bb-9430da5ce885)

We have multiple scanners running that are creating snapshots of our EC2 machines in a certain region.
This doesn't make sense and differs drastically from the calculations that AWS provides (also might be because `Elastic` probably has a non default cost contract with AWS).

I think that we need to investigate further the costs of snapshots creation and make sure that we give a concrete answer.
@nick-alayil Is is possible to deploy default AWS account without special cost contracts and measure the cost of snapshot creation?

**Comment by jeniawhite** [comment]
@nick-alayil
Let's get a concrete case as an example that we would like to measure the cost.
We will be able to calculate that exactly using our development account and then provide this as an example case.
Please provide the most customer-relevant example scenario.

We would need to following information:
- What is the region of the scanner and ES (or is ES outside of AWS).
- How many EC2 instances are in the region.
- Volume size (assuming only the root volume per instance), we can mix volumes sizes between EC2 instances as well.
- Scanner InstanceType picked by the user.
- Approximately number of vulnerabilities found per scanned snapshot.

What do you think?

**Comment by nick-alayil** [comment]
>What do you think?
Sounds good to me @jeniawhite. I'll get the info and update it here shortly.

**Comment by nick-alayil** [comment]
Let's consider the following scenario:

> What is the region of the scanner and ES (or is ES outside of AWS).

The scanner and Elasticsearch (ES) are both located within the AWS US East region (us-east-1).

> How many EC2 instances are in the region.

10 EC2 instances running

> Volume size (assuming only the root volume per instance), we can mix volumes sizes between EC2 instances as well.

Each EC2 instance has a root volume size varying between 30 GB and 100 GB. The mix of volumes sizes is as follows:
* 30 GB: 4 instances
* 50 GB: 3 instances
* 100 GB: 3 instances

> Scanner InstanceType picked by the user.

Let's go with default:  m6g.xlarge

> Approximately number of vulnerabilities found per scanned snapshot.

Let's assume customer is following very decent vulnerability practices. So, on average, the scanner detects around 100 vulnerabilities per scanned snapshot. 

If engg is planning to enumerate the above scenario for cost estimation, I'd recommend using the below highlighted community AMIs pre-baked with nginx. Let's assume customer is running the latest like AL2023 or Ubuntu22.04 LTS.

![Screenshot 2023-08-01 at 8 51 24 PM](https://github.com/elastic/cloudbeat/assets/59900203/85ab8753-185a-4b48-923c-3609611c0a25)

Please let me know if there are any further questions.
