### ISSUE TITLE
[CNVM] Sort EC2 instances in ascending order of disk size

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1118]
### Motivation
Scanning EC2 instances can take a lot of time, especially if the first instance being scanned has a large disk size. In order to reduce the time it takes to get the first vulnerability we can sort the EC2 instances that we scan based on their disk size.
Both for tests and real users it can help to get quicker feedback of the environment.

### Definition of done
- [x] EC2 fetcher should sort instances in ascending order
- [ ] Update CF

**Related tasks/epics**
Reference related issues and epics

**Comment by amirbenun** [comment]
With a short research I found that AWS go client function [ec2.DescribeVolumes](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeVolumes) returns a list of volumes with a single request. A request can also filter for volumes attached to specific instances.

In our case, after we get all the instances, with an extra single call (or paginated) we will have all the volumes attached to the instances we want to scan. then, we can compare the instance `RootDeviceName` field with the `InstanceId` and `Device` fields on the volume attachments object.

Another issue that comes to my mind is that we create snapshots for all volumes attached to an instance even though Trivy will only scan the root volume.
After implementing this feature, we will be able to create snapshots only for root volumes and **save even more time and money**.

@nick-alayil @oren-zohar I think it worths prioritizing this task for 8.10.

**Comment by oren-zohar** [comment]
We suspect (@jeniawhite, @amirbenun, @nick-alayil) that not only the size of the disk determines the scan's duration, but also the percentage of it that is used.

**Comment by amirbenun** [comment]
Reopen to track the integration changes

**Comment by kfirpeled** [comment]
@amirbenun/@oren-zohar can you please describe how to verify this ticket in our first QA cycle?

**Comment by amirbenun** [comment]
Create several instances with different disk sizes on the same region (empty region with no instances).
Run CNVM on that region, make sure that the first instance that was scanned is the one with the smallest size.

**Note:** cloudbeat compares the size of the root volume only

**Comment by mitodrummer** [comment]
QA Evidence:
EC2 volumes list sorted size ASC: (highlighting maxcold-8-10-v2-qa-1) size: 20gb
![Image](https://github.com/elastic/cloudbeat/assets/16198204/2b872e1f-4cce-4dd3-b2c8-064f75504136)

Discover sorted timestamp DESC
![Image](https://github.com/elastic/cloudbeat/assets/16198204/e1570036-5a3b-4067-a250-207f50ac1769)

EC2 volumes list sorted size ASC: (highlighting elastic-agent-instance-5fc51830) size: 8gb

![Image](https://github.com/elastic/cloudbeat/assets/16198204/de2af8aa-059a-496d-ae8c-65d79265b4dc)

Discover sorted timestamp ASC
![Image](https://github.com/elastic/cloudbeat/assets/16198204/badba171-b6ba-4e37-82ba-ea6765188698)

This only shows that the top and bottom of the latest vulns are 8gb vs 20 gb.  I will try next to create a dashboard with lens to agg the list of resources by time, and hopefully correlate that to a filtered list of volumes in EC2.

**Comment by kfirpeled** [comment]
@amirbenun is that a sufficient verification?
