### ISSUE TITLE
[Discuss] Report CNVM scan metadata

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1124]
### Motivation
Today, each Cloudbeat flavor (CNVM/CSPM/KSPM) reports 2 kinds of events: Findings and Logs.
However, there is more valuable information that we should keep that doesn't fall into one of these two kinds.
For example in CNVM:
1. Information about the snapshot creation and deletion:
  a. EC2 instance (region, volumes, size, encryption)
  b. Snapshot (volume, actual size, encryption)
  c. The duration of snapshot creation
  d. Failures
2. Information about a single scan
  a. Resource scanned (snapshot / image)
  b. The duration of scanning
  c. Failures

On one hand I would keep that information in a structured schema so it doesn't fit our logs.
On the other hand this is not a vulnerability so it doesn't fit the findings.

### Discuss
This discussion is about where and how we should keep structured data that comes from cloudbeat. In the beginning we only care about holding that information maybe in the future we will be able to show valuable visualizations on top of that data.
A few guiding questions that comes to my mind:

0. Whether or not we want to keep structured data besides the findings
1. Where we should index the data (one or more indices)
2. In what format it should be (ECS?)
3. Relations between objects (Can a vulnerability point to  scan? Is it necessary?)

### Out of scope
Visualizations on top of the data are out of the scope of this ticket

### Related tasks/epics
- https://github.com/elastic/security-team/issues/6686

**Comment by amirbenun** [comment]
### Suggestion

Cloudbeat is currently in a phase where it can gather extensive data from cloud environments. In addition to findings and vulnerabilities that it already collects, there is more valuable information that should be stored in Elasticsearch. Rather than making decisions for each new dataset we consider indexing, I propose that we begin by storing information about scans, specifically in the case of CNVM.
The scan information should be indexed to a dedicated index (better explicit than implicit):

`logs-cloud_security_posture.scan_metadata-default`.

| Field                        | Description                       | Allowed Values   | ECS                                                                                  |
|------------------------------|-----------------------------------|------------------|--------------------------------------------------------------------------------------|
| agent.id                     |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-agent.html#field-agent-id            |
| agent.type                   |                                   | Cloudbeat        | https://www.elastic.co/guide/en/ecs/current/ecs-agent.html#field-agent-type          |
| cloud.account.id             |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html#field-cloud-account-id    |
| cloud.account.name           |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html#field-cloud-account-name  |
| cloud.region                 |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html#field-cloud-region        |
| cloud.service.name           |                                   | AWS EC2          | https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html#field-cloud-service-name  |
| cloud.instance.name          |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html#field-cloud-instance-name |
| cloud.instance.id            |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html#field-cloud-instance-id   |
| cloud.machine.type           |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html#field-cloud-machine-type  |
| cloud.machine.Disk.volume    | Volume size of the instance       |                  | -                                                                                    |
| cloud.machine.Disk.encrypted |                                   | true, false      | -                                                                                    |
| os.name                      |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-os.html#field-os-name                |
| os.platform                  |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-os.html#field-os-platform            |
| os.type                      |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-os.html#field-os-type                |
| os.version                   |                                   |                  | https://www.elastic.co/guide/en/ecs/current/ecs-os.html#field-os-version             |
| event.start                  | Scan start                        |                  | https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-start         |
| event.end                    | Scan end                          |                  | https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-end           |
| event.duration               | Scan duration                     |                  | https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-duration      |
| event.outcome                | Scan outcome                      | success, failure | https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-outcome       |
| event.category               |                                   | vulnerability    | https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-category      |
| event.type                   |                                   | info             | https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-type          |
| event.module                 |                                   | CNVM             | https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-module        |
| event.provider               |                                   | Cloudbeat        | https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-provider      |
| event.original               | Raw logs of the scan              |                  | https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-original      |
| error.message                | Error message returned from trivy |                  | https://www.elastic.co/guide/en/ecs/current/ecs-error.html#field-error-message       |

@eyalkraft @oren-zohar Any thoughts?

**Comment by oren-zohar** [comment]
Thanks @amirbenun, this is a good initiative. In order to make this data we collect more accessible and forward compatible, it would be great if we could populate current ECS fields. I think it would be a good idea to cross these suggested fields with ECS.
I'm also wondering about the index, should it be public or private? what about data view? What about the index type, Why data stream?
And what is the end result here? create a dashboard to view data? integrate it with our current dashboard
