### ISSUE TITLE
[BUG] Kibana - Findings - On edit search bar filter, the popup form is empty

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#113]
**Describe the bug**
Search attributes are not being saved between edits when the filter widget is being used.

**Preconditions**
Kibana environment with CSP plugin enabled
Agent installed that generates findings

**To Reproduce**

1. Go to the findings page.
2. Add a filter using the widget.
3. Run the query.
4.  Try to edit the query using the widget ->  search attributes are not saved.

**Expected behavior**
Search context is saved and editable.

**Video**

https://user-images.githubusercontent.com/68195305/167667500-2c6fd3ec-4c56-422c-bc41-34e9ef4b4f49.mov

Kibana Version:  8.3.0-SNAPSHOT
BUILD: 52444
COMMIT: 8ace5e47555d4b01a9853c430f7adb4539d2925c

**Comment by kfirpeled** [comment]
related https://github.com/elastic/security-team/issues/3619

**Comment by orouz** [comment]
using the query service fixes this issue too.
