### ISSUE TITLE
CloudFormation template add agent tags

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1132]
### Motivation
When deploying a CloudFormation template we have no way to tell in the fleet that the elastic-agent was deployed with the stack creation. Then, it makes it hard to flag the user on an available updates in the CloudFormation template.
The `elastic-agent install` command supports a `--tag` CLI parameter which we can leverage in order to save important information about the elastic-agent.
As a first step, we should tag the elastic-agent with the following:
- `cft-arn:` - CloudFormation stack ARN
- `cft-version:` - CloudFormation template version

### Definition of done
- [ ] Compose the stack ARN from the [pseudo parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) provided by AWS
- [ ] Define a new parameter for the template version which will be replaced by the CI
- [ ] Tag the agent with those values prefixed with `cft-arn:` and `cft-version:` respectively
- [ ] Changes should apply for CSPM and CNVM
- [ ] Optionally: test the feature as part of the sanity job

### Testing
Make sure agents are properly tagged via FleetUI

### Related tasks/epics
- https://github.com/elastic/security-team/issues/5701

**Comment by amirbenun** [comment]
Example for elastic-agent tags:
<img width="457" alt="image" src="https://github.com/elastic/cloudbeat/assets/34831306/cb10f80b-a3d5-48ad-85b3-da80a3163707">

**Comment by amirbenun** [comment]
### Background
When we publish a CloudFormation template to an S3 bucket we publish it with the date and time suffix to have versioning.

### Problem
While working on the task I separated the cloudformation upload script into a separate file `scripts/publish_cft.sh`.
Since the new script also uses the current date, when it gets called by the CI, the creation date of the two CSPM templates is not necessarily identical.

When I had to update the integration with the new template I realized that there is an assumption that the two templates were named with the exact same time (differs only by the `ACCOUNT_TYPE`).
```
https://elastic-cspm-cft.s3.eu-central-1.amazonaws.com/cloudformation-cspm-ACCOUNT_TYPE-8.10.0-2023-07-24-15-10-19.yml
```

### Available solutions
1. The script will accept the date as a parameter, meaning we will keep publishing the two files with the same date.
2. Instead of having a single variable `cloud_formation_template`, we can hold two different variables: `cloud_formation_template_single_account` and `cloud_formation_template_organization_account`

The benefit of going with the second option is that we will be able in the future to support new parameters only in one of the templates.

@orestisfl Any thoughts?

**Comment by amirbenun** [comment]
I moved on with the first option, all CloudFormation templates will have an identical suffix as implemented in https://github.com/elastic/cloudbeat/pull/1211

**Comment by kfirpeled** [comment]
> @kfirpeled The second option also requires a FE implementation. What do you think?

Hi sorry for picking this up so late - if this is a techdebt you wish us to fix feel free to ping me
