### ISSUE TITLE
[BUG] Integration - On delete - Not all concrete rules are deleted

### ISSUE THREAD

**Issue by orouz** [elastic/cloudbeat#114]
**Describe the bug**

whenever we remove an integration instance from an agent policy we expect all its concrete rules to be deleted as well.

**Preconditions**
- have a CIS integration installed

**To Reproduce**

1. Delete integration
2. Go to Stack Managemtnet -> Saved Object -> Filter by `csp_rule` type
3. only 20 concrete rules are deleted (total is 83 after deletion 63 is left)

**Expected behavior**

all the `csp_rule` from this specific  `packagePolicyId` and `policyId` are deleted

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: `df225b213b188c81888141cee2ec191424fc0649`
 - Endpoint Version:
 - Other Version: 

**Additional context**

the bug is a result of the default page size returned from the saved object `find` function

- [file](https://github.com/elastic/kibana/blob/main/x-pack/plugins/cloud_security_posture/server/fleet_integration/fleet_integration.ts#L86-L89)

- suggested fix:
```diff
await soClient.find({
        type: cspRuleAssetSavedObjectType,
        filter: `${cspRuleAssetSavedObjectType}.attributes.package_policy_id: ${deletedPackagePolicy.id} AND ${cspRuleAssetSavedObjectType}.attributes.policy_id: ${deletedPackagePolicy.policy_id}`,
+       perPage: 10000,
      });

**Comment by eyalkraft** [comment]
[testrail](https://elastic.testrail.io/index.php?/tests/view/1129217&group_by=cases:section_id&group_order=asc&group_id=35144)

**Comment by CohenIdo** [comment]
Kibana PR:
- https://github.com/elastic/kibana/pull/133004
