### ISSUE TITLE
[BUG] Integrations readme section missing patch for roles & permissions required for read me

### ISSUE THREAD

**Issue by DaveSys911** [elastic/cloudbeat#116]
**Describe the bug**
CIS k8s integration readme upgrade section, lacks instruction for patching the clusterrole & role to add the missing permissions cloudbeat requires.

**Preconditions**
Environment state and/or platform specific configurations.

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Browse to the CIS integration page via the integrations page in kibana.

**Expected behavior**
To contain section adding patch instructions for permissions and rules

**Screenshots**
![image](https://user-images.githubusercontent.com/16253938/167808602-eee2afeb-611e-4ca3-8700-3330e32d34bf.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: 
 
![image](https://user-images.githubusercontent.com/16253938/167808642-a7f18927-0f0c-4367-bb98-f822724ad503.png)

 - Endpoint Version:
 Elastic-Agent 8.3.0-SNAPSHOT 
![image](https://user-images.githubusercontent.com/16253938/167808720-461a7e86-01bf-47e5-978e-9ec6e30a0b00.png)

 - Other Version: 

**Additional context**

**Comment by oren-zohar** [comment]
there's a task for that already 
- https://github.com/elastic/integrations/issues/3252
