### ISSUE TITLE
CI cache constantly above limit

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1175]
**Motivation**
The [CI cache](https://github.com/elastic/cloudbeat/actions/caches) is constantly hitting the GitHub 10GB limit.
![image](https://github.com/elastic/cloudbeat/assets/5778622/9c206d80-dbbc-412d-9b6a-f838616ec8f7)
As far as I am aware, it's not possible to increase this limit.

This likely impacts the performance of our pipelines as caches are not maintained between runs. We should investigate the impact further.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Investigate performance impact of caches becoming unavailable
- [ ] List all caches by size, which ones are the bigger offenders?
- [ ] Investigate if some of the caches do not provide benefits, e.g. they are written but never read or if their impact is minimal
- [ ] Investigate alternative caching locations, e.g. AWS
- [ ] Investigate if some caches can be merged together, e.g. the go cache with the golangci cache
- [ ] Change our pipelines to fix the problem **or** branch of to a different ticket for the actual solution

**Comment by moukoublen** [comment]
Before ci workflows refactor the github cache was used both tools (golang, go mods etc) and even for docker intermediate build cache. 

By multiplying this to every open pr the cache limit was constantly above the limit. 



After the ci workflows refactor, an attempt was made to minimize the cache usage as much as possible, using a single hermit build -> load to cache step for every job while also using the artifacts upload/download functionality for uploading and downloading docker images (as we can in file https://github.com/elastic/cloudbeat/blob/main/.github/actions/docker-images/action.yml )

It is still possible for the cache usage to exceed the limit, but currently, it's not that easy.
<img width="1378" alt="Screenshot 2024-06-05 at 5 26 32 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/cc95ff98-8aad-400b-9d8e-b9bcbd10cea0">


I think we can conclude this task and mark it as closed.
