### ISSUE TITLE
[AWS Orgs] Add fields for organizations

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1177]
**Motivation**
Currently, the AWS organization name/id is not included in resources. This ticket is about adding this information.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Investigate if there is an ECS field we can re-use
- [ ] Fetch and tag resources with new field

**Comment by kfirpeled** [comment]
- verify findings contains `cloud.organization.id` & `cloud.organization.name`

**Comment by CohenIdo** [comment]
verified (8.11 BC4 QA cycle): 

<img width="2555" alt="image" src="https://github.com/elastic/cloudbeat/assets/90558359/06312f5f-7adf-400d-9d18-4425c9c11af2">
