### ISSUE TITLE
[CIS GCP] Retrieve project id from attached service account

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#1184]
**Motivation**
When user will deploy the integration through cloudshell, the project id will not resides inside the agent policy, therefore, we want cloudbeat to be able to retrieve the project id from the attached credentials (SA).

**Definition of done**
- [ ] When the agent is deployed through cloudshell, cloudbeat is able fetch resources without getting the project id from the agent policy.

**Related tasks/epics**
-  https://github.com/elastic/security-team/issues/7185

**Comment by opauloh** [comment]
Verified



![Image](https://github.com/elastic/kibana/assets/19270322/efdf4358-8c17-4571-84ed-acdbe1195031)




![Image](https://github.com/elastic/kibana/assets/19270322/363ed577-8d04-4f64-a834-a6730ffd6aef)





![Image](https://github.com/elastic/kibana/assets/19270322/c23bc744-6a5c-4ab7-a32e-770e90acc106)



Verified - 8.10 QA Cycle

VERSION: **8.10.0**

BUILD: **66107**

COMMIT: **fa3473f42d7c5e7a3c2d66026a153e01002f5d3c**
