### ISSUE TITLE
[CIS GCP] Introduce an automation for updating the CloudShell URL in the integrations repo.

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#1185]
**Motivation**
In the integration repo we keep a cloudshell url, reponsible for redirecting the user to it's cloudshell env and checkout the right branch.
This link should be updated every minor release, whenever cloudbeat is branching out to the new version specific branch.

**Definition of done**
- [ ] Introduce a CI step that creates a new PR for the integrations repo once the cloudbeat version is being updated.

Example:
old link: `https://shell.cloud.google.com/cloudshell/?ephemeral=true&cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Felastic%2Fcloudbeat&cloudshell_git_branch=8.10&cloudshell_workspace=deploy%2Fdeployment-manager&show=terminal
`

new link: `https://shell.cloud.google.com/cloudshell/?ephemeral=true&cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Felastic%2Fcloudbeat&cloudshell_git_branch=8.11&cloudshell_workspace=deploy%2Fdeployment-manager&show=terminal`

**Related tasks/epics**
- Related: https://github.com/elastic/integrations/pull/7235/files

**Comment by orestisfl** [comment]
@uri-weisman Please take into account that after https://github.com/elastic/cloudbeat/issues/1320 this should also apply to AWS CF. My suggestion is to keep the implementation cloud-provider-agnostic to be able to handle that case later.

**Comment by orouz** [comment]
i came up with [this](https://github.com/elastic/cloudbeat/compare/main...orouz:cloudbeat:urls_automate) workflow, based on [this](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#creating-pull-requests-in-a-remote-repository) guide. haven't tested this on forks yet, but seems like the only blocking thing now would be to get the proper PAT (not my own).

**Comment by orouz** [comment]
closed in favor of https://github.com/elastic/cloudbeat/issues/1675
