### ISSUE TITLE
[CSPM] GCP log appears during AWS CSPM deployment

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#1187]
**Describe the bug**

During the deployment of AWS CSPM, an unexpected log related to GCP is appearing. The log indicates that the `elastic_agent.cloudbeat` component is trying to fetch the GCP client config, even though GCP should not be involved in the AWS CSPM deployment process.

**Preconditions**
ELK version: 8.10.0-SNAPSHOT is deployed
Beta integrations flag is ON.

**To Reproduce**
1. Create AWS CSPM integration and deploy agent.
2. Monitor the logs generated during the deployment.
3. Observe the appearance of the log message: `[elastic_agent.cloudbeat][error] failed to get GCP client config: the credentials file path or credentials JSON have not been specified.`

[Environment details](https://p.elstc.co/paste/m95k-jVe#wEEkdPkkEFmA7cZTNOnQbf3pfoQdEOIZIKiiPblUexH)

**Expected behavior**

When deploying AWS CSPM, there are no logs related to GCP. The deployment process is focusing solely on AWS resources and configurations.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5
 - Browser: Chrome
 - Kibana Version: 8.10.0-SNAPSHOT
 - Endpoint Version: 8.10.0-SNAPSHOT 
 - Other Version:

**Comment by orestisfl** [comment]
@gurevichdmitry This should be already resolved, can you check with the latest 8.10 snapshot?

**Comment by gurevichdmitry** [comment]
> @gurevichdmitry This should be already resolved by #1161, can you please check with the latest 8.10 snapshot?

You are correct, @orestisfl. After deploying the latest agent snapshot, the error no longer appears in the logs. I'm closing this issue.
