### ISSUE TITLE
[BUG][Kibana] - Findings page adding rule number to findings

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#119]
**Describe the bug**
As a user, I would like to see the rule number as part of the rule.

**In-Depth** 
It needs to be discussed where the rule number should appear.
Should it be a part of the `General` findings flyout page?

![image](https://user-images.githubusercontent.com/19221736/167835495-296df3a5-a077-4033-8355-b96b60a96ad3.png)

Maybe it needs to be a part of the findings table as well.
![image](https://user-images.githubusercontent.com/19221736/167835554-8d96a327-0227-46b7-a6ca-129677f420c2.png)

Kibana Version: 8.3.0-SNAPSHOT
BUILD: 52444
COMMIT: 8ace5e47555d4b01a9853c430f7adb4539d2925c

@einatjacoby @tinnytintin10 @tehilashn @amitkanfer

**Comment by tehilashn** [comment]
@tinnytintin10 @amitkanfer - to define the expected behaviour

**Comment by tinnytintin10** [comment]
This is a nice to have we can implement at some point, it's not a deal breaker. We are codifying the CIS benchmarks for the user, they don't necessarily need to know the rule number for a specific rule to get value out of the product. That being said, they can search for specific rule numbers and get accurate results if they want: 

https://user-images.githubusercontent.com/53792284/167958693-44d42b6c-43d8-4cfc-b125-252793cc250a.mov

When we do decide to add the rule number, we can add it directly as a value in the general tab like so: 

<img width="2032" alt="Screen Shot 2022-05-11 at 3 21 43 PM" src="https://user-images.githubusercontent.com/53792284/167957399-b1e5331b-52ba-49ce-aefc-fad7aae55a05.png">

Or show it as one of the tag values (as it's currently represented in our findings schema below): 

```json

"rule": {
    "references": "1. [https://kubernetes.io/docs/admin/kubelet/](https://kubernetes.io/docs/admin/kubelet/)\n2. [https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication](https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication)\n",
    "impact": "Anonymous requests will be rejected.\n",
    "description": "Disable anonymous requests to the Kubelet server.\n",
    "default_value": "By default, anonymous access is enabled.\n",
    "section": "Kubelet",
    "rationale": "When enabled, requests that are not rejected by other configured authentication methods are treated as anonymous requests. These requests are then served by the Kubelet server. You should rely on authentication to authorize access and disallow anonymous requests.\n",
    "version": "1.0",
    "benchmark": {
      "name": "CIS Kubernetes V1.23",
      "version": "v1.0.0"
    },
    "tags": [
      "CIS",
      "Kubernetes",
      "CIS 4.2.1",
      "Kubelet"
    ],
    "remediation": "If using a Kubelet config file, edit the file to set `authentication:\nanonymous: enabled` \nto\n`false`.\nIf using executable arguments, edit the kubelet service file\n`/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` on each worker node and\nset the below parameter in `KUBELET_SYSTEM_PODS_ARGS` variable.\n```\n--anonymous-auth=false\n```\nBased on your system, restart the `kubelet` service. For example:\n```\nsystemctl daemon-reload\nsystemctl restart kubelet.service\n```\n",
    "audit": "If using a Kubelet configuration file, check that there is an entry for\n`authentication: anonymous: enabled` set to `false`.\nRun the following command on each node:\n```\nps -ef | grep kubelet\n```\nVerify that the `--anonymous-auth` argument is set to `false`.\nThis executable argument may be omitted, provided there is a corresponding entry set to\n`false` in the Kubelet config file.\n",
    "name": "Ensure that the --anonymous-auth argument is set to false (Automated)",
    "id": "a082f4e6-67d7-56c4-9764-42db2030a552",
    "profile_applicability": "* Level 1 - Worker Node\n"
  }

```

@tehilashn @amitkanfer my suggestion is to close this out and track it as a product requirement task. wdyt?

**Comment by amitkanfer** [comment]
> my suggestion is to close this out and track it as a product requirement task. wdyt?
It's definitely not a "bug", so yes, much needed improvement IMO. ++
