### ISSUE TITLE
[BUG] Fleet UI - cloudbeat logs are not available

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#120]
**Describe the bug**

In Fleet UI screen, when viewing an agent logs, cloudbeat logs are not available to filter

**Preconditions**
Kibana environment with csp plugin enabled
Agent installed with `CIS Kubernetes Benchmark` that generates findings

**To Reproduce**

1. Go to agent logs screen
2. Try to filter by `cloudbeat`

**Expected behavior**
You should be able to filter by cloudbeat

**Screenshots 📸**

![Screen Shot 2022-05-11 at 14 28 44](https://user-images.githubusercontent.com/61654899/167838947-966f5ad1-a4ff-4f3c-8ab8-e7f062369e25.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT: [df225b213b188c81888141cee2ec191424fc0649](https://github.com/elastic/kibana/commits/df225b213b188c81888141cee2ec191424fc0649)
 - Endpoint Version:
 - Other Version: 
   - Cloudbeat Version: [9c1270716902466e02459ba252788698e4705471](https://github.com/elastic/cloudbeat/commits/9c1270716902466e02459ba252788698e4705471)

**Additional context**

**Comment by yashtewari** [comment]
Found from the Kibana code that the drop down is created by looking at the ES indices of the form `logs-elastic_agent.*-*` which are created by filebeat by scraping the log files on the running Agent.

These indices are present for all other beats, but `logs-elastic_agent.cloudbeat-*` is not present.

Digging further, and thanks to help from @kvch we found in the "filebeat monitoring" logfile present at
```
/usr/share/elastic-agent/data/elastic-agent-*/install/filebeat-*/logs/
```
the following error log:
```
{"log.level":"warn","@timestamp":"2022-05-18T14:58:07.139Z","log.logger":"elasticsearch","log.origin":{"file.name":"elasticsearch/client.go","file.line":429},"message":"Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2022, time.May, 18, 14, 58, 0, 822000000, time.UTC), Meta:{\"raw_index\":\"logs-elastic_agent.cloudbeat-default\"}, Fields:{\"agent\":{\"ephemeral_id\":\"cdcfdb97-da7e-4247-a705-d78aa08d555e\",\"id\":\"bd84ea71-f71e-4e62-9243-a43b20d0f7f3\",\"name\":\"kind-control-plane\",\"type\":\"filebeat\",\"version\":\"8.3.0\"},\"cloud\":{\"account\":{\"id\":\"946960629917\"},\"availability_zone\":\"ap-south-1b\",\"image\":{\"id\":\"ami-0851b76e8b1bce90b\"},\"instance\":{\"id\":\"i-07634295b652f85fe\"},\"machine\":{\"type\":\"c5.4xlarge\"},\"provider\":\"aws\",\"region\":\"ap-south-1\",\"service\":{\"name\":\"EC2\"}},\"data_stream\":{\"dataset\":\"elastic_agent.cloudbeat\",\"namespace\":\"default\",\"type\":\"logs\"},\"ecs\":{\"version\":\"8.0.0\"},\"elastic_agent\":{\"id\":\"bd84ea71-f71e-4e62-9243-a43b20d0f7f3\",\"snapshot\":true,\"version\":\"8.3.0\"},\"event\":{\"dataset\":\"elastic_agent.cloudbeat\"},\"host\":{\"architecture\":\"x86_64\",\"containerized\":true,\"hostname\":\"kind-control-plane\",\"ip\":[\"10.244.0.1\",\"10.244.0.1\",\"10.244.0.1\",\"172.19.0.2\",\"fc00:f853:ccd:e793::2\",\"fe80::42:acff:fe13:2\",\"172.18.0.4\"],\"mac\":[\"02:42:ac:12:00:04\",\"02:42:ac:13:00:02\",\"2e:84:91:a8:09:8c\",\"c6:aa:3e:72:c4:f8\",\"fa:cd:a9:ec:ba:b8\"],\"name\":\"kind-control-plane\",\"os\":{\"codename\":\"focal\",\"family\":\"debian\",\"kernel\":\"5.13.0-1023-aws\",\"name\":\"Ubuntu\",\"platform\":\"ubuntu\",\"type\":\"linux\",\"version\":\"20.04.4 LTS (Focal Fossa)\"}},\"input\":{\"type\":\"filestream\"},\"log\":{\"file\":{\"path\":\"/usr/share/elastic-agent/state/data/logs/default/cloudbeat-20220518-6.ndjson\"},\"offset\":270895},\"log.level\":\"info\",\"log.origin\":{\"file.line\":115,\"file.name\":\"manager/data.go\"},\"message\":\"manager finished waiting and sending data after 2 msecs\",\"service.name\":\"cloudbeat\"}, Private:(*input_logfile.updateOp)(0xc000609b00), TimeSeries:false}, Flags:0x1, Cache:publisher.EventCache{m:mapstr.M(nil)}} (status=403): {\"type\":\"security_exception\",\"reason\":\"action [indices:admin/auto_create] is unauthorized for API key id [c4T51oABGatCfySMMiGV] of user [elastic/fleet-server] on indices [logs-elastic_agent.cloudbeat-default], this action is granted by the index privileges [auto_configure,create_index,manage,all]\"}, dropping event!","service.name":"filebeat","ecs.version":"1.6.0"}
```

It details a failure to create the required index in ES due to missing permissions of the `elastic/fleet-server` user.

Now trying out changes in the following, per suggestions from @nchaulet to see if I can get it working, and hopefully come up with PRs.
1. https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/common/constants/agent_policy.ts/#L15
2. https://github.com/elastic/integrations/tree/main/packages/elastic_agent/data_stream

**Comment by yashtewari** [comment]
Should be fixed by PRs: https://github.com/elastic/integrations/pull/3378 and https://github.com/elastic/kibana/pull/132452

**Comment by yashtewari** [comment]
Merged, will wait and test with the SNAPSHOT before closing.
