### ISSUE TITLE
[BUG] Kibana - Compliance score trendline visualization 

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#121]
**Describe the bug**
When looking at the score trendline it is hard to notice/detect a change in your score

**In-depth**
In our current solution, we sample the Kubernetes cluster every 15m and we even think about extending the time interval even further.
Our graph represents the 5 latest points in time, and the trendline of the graph represents the fluctuation/trend of the score.

Since we measure only 5 points in time (and our time intervals are pretty long), we can consider this graph a discrete graph.
![image](https://user-images.githubusercontent.com/19221736/167838769-b0f44c70-e9ab-4050-b5e0-8cbb3731a0b7.png)

Therefore there are multiple ways of describing the same information (I'll describe the two that I think most relevant for us):

1. "Continous trendline"(connect the dots) -

<img width="543" alt="image" src="https://user-images.githubusercontent.com/19221736/167838560-1ad5d46b-db85-43c2-8dfc-51bb6ca4a426.png">

adv:
a. Probably the classic way to show a trendline in a graph.
dsv:
**b. It is very hard to detect changes in your score - and this is even after zooming in**

2. "discrete steps trendline"

![image](https://user-images.githubusercontent.com/19221736/167840194-5f42f029-05ea-476c-b4d8-dd788b518239.png)

adv
a. Very easy to detect score changes.
dsv
b. Less classical way of showing the data. 

I think we should consider changing the way we represent the trendline, and see what representation is the best for us.
My personal opinion here is that the `steps trendline` fits our solution more since our time intervals are big, and the fluctuation will be probably minimal. Therefore, I believe that every trend change needs to be emphasized. 

 in the current solution a user can barely see the trend of the score, so if we will choose to continue using the `Continous trendline` solution, we need to think about how we can make changes more visible for the user.

Kibana Version: 8.3.0-SNAPSHOT
BUILD: 52444
COMMIT: 8ace5e47555d4b01a9853c430f7adb4539d2925c

**Comment by kfirpeled** [comment]
Checkout [eui chart playground](https://elastic.github.io/elastic-charts/?path=/story/line-chart--with-axis&globals=theme:light)

**Comment by tehilashn** [comment]
cc @amitkanfer

**Comment by tinnytintin10** [comment]
> My personal opinion here is that the steps trendline fits our solution more since our time intervals are big, and the fluctuation will be probably minimal. Therefore, I believe that every trend change needs to be emphasized.

++ I agree! By emphasizing these changes, not only do we help the user's awareness of their overall score and trend better but also we are giving them a signal to investigate certain behaviors (like stark increases and decreases in their scores). I will create a product discovery task exploring the later idea further...

**Comment by kfirpeled** [comment]
This should be fixed once we will push:
- https://github.com/elastic/security-team/issues/3606
- https://github.com/elastic/security-team/issues/3628
- https://github.com/elastic/cloudbeat/issues/92

**Comment by JordanSh** [comment]
8.4 candidate label removed, this UX suggestion might be addressed at the future.
