### ISSUE TITLE
Fix periodic CI

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#1220]
**Motivation**

The periodic CI is currently failing due to a redundant "Build" step, which needs refactoring and updating to resolve the issue.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Fix Build job steps
- [ ] Uncomment workflow scheduler

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by oren-zohar** [comment]
It was decided to remove the Periodic CI, as it's not needed anymore. cc @gurevichdmitry
