### ISSUE TITLE
Support darwin artifacts in the release process

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#1227]
**Motivation**
In the integration, we offer to install agent artifacts on Darwin. However, our current release procedure does not include the creation of binaries specifically for OSX.

Furthermore, it will improve local testing, allowing for the convenient download of the agent snapshot directly to your local environment. This eliminates the need of copying the Cloudbeat binary and other associated files, thus expediting the testing process.

**Definition of done**
The user/dev is able to download the elastic agent binary for OSX and run it locally without any modifications.
- [ ] Update our release pipeline to create artifacts for the `darwin/amd64, darwin/arm64` platforms as well.

**Comment by oren-zohar** [comment]
I am closing this because if it has been blocked for so long, I assume it is not a top priority for us.
