### ISSUE TITLE
Update cloud security posture integration deployment instructions

### ISSUE THREAD

**Issue by eyalkraft** [elastic/cloudbeat#123]
**Motivation**

Currently the README for our integration describes how to update your deployed agent in order to make sure it has all the required permissions for cloudbeat ([PR](https://github.com/elastic/integrations/pull/3190)).
Since cloudbeat, and our integration will only be released with version 8.3 of the stack, and the agent only downloads matching version artifacts, cloudbeat will only work on agents from versions 8.3+

Also you need to validate that elastic-agent [upgrades](https://www.elastic.co/guide/en/fleet/master/upgrade-elastic-agent.html) aren't supported for containerized agents (the relevant agents for us). If these upgrades are supported it means we might have 8.3 containerized agents deployed with old yamls and for this the permission patch is still relevant.
[Support matrix
](https://www.elastic.co/support/matrix#matrix_compatibility)
**Definition of done**

- [ ] Rethink what should be written in our README about supporting agent 8.3+ and the updated deployment yamls
- [ ] Rewrite the README accordingly

**Out of scope**

- [ ] change anything but the integration

** Related issues **

- Closed duplicate https://github.com/elastic/integrations/issues/3252

**Comment by tinnytintin10** [comment]
@eyalkraft if I am understanding this issue correctly, the instruction below from our benchmark integration is no longer valid since we only support elastic agent 8.3+. Is that correct?

> Note, if you want to add this integration to existing Elastic agents (deployed prior to 8.3 release), you'll have to update your DaemonSet to include the additional required volumes and volume mounts. This can be done in a few steps:

If this is the case, IMO here are the things we should do if the user is going to add our integration to an existing deployment: 

1. Check to see if there is ANY agent in the agent policy the user selects that has a version < 8.3
          a. If there is an agent with a version < 8.3, ask the user to upgrade their agents to a version >= 8.3 in order to add our integration to their agent.  The user shouldn't be allowed to move on from this step in the installation process. 
          b. If all the agents in the agent policy the user-selected have a version >= 8.3, the user can continue their installation process and enjoy all the goodness we have to offer 🚀

When I say "if the user is going to add our integration to an existing deployment" this is what I mean: 

<img width="1624" alt="Screen Shot 2022-05-13 at 12 52 19 PM" src="https://user-images.githubusercontent.com/53792284/168384229-72874187-c9ed-4e41-96ce-c099885679a8.png">

lmk what you think.

**Comment by eyalkraft** [comment]
Hey @tinnytintin10! Thanks for your comment.
Product-wise this sounds awesome, From the technical perspective this is more complicated than just changing the README of our integration.

Estimating this will require some research, and we can prioritize it with @tehilashn

**Comment by eyalkraft** [comment]
@uri-weisman Since changing the whole installation page appears to be out of scope for the 8.3 release, Let's change this task:

1. We'll continue this research with https://github.com/elastic/security-team/issues/3044 later on
2. To close this bug, change the readme of our integration to indicate that for it to work the user has to deploy an agent version 8.3+ with the latest deployment yamls.
Remove the existing section about changing the permissions for old agent since we figured out it is irrelevant.

cc @tehilashn

**Comment by uri-weisman** [comment]
Integration PR: https://github.com/elastic/integrations/pull/3382
