### ISSUE TITLE
Shared Elastic Cloud account

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1231]
**Motivation**
We need a shared account for creating long running environments and CI environments.
Contact the Platform Security team on jira to get access to a new account.

**Definition of done**
- [ ] Get a new Elastic Cloud account that all engineers of Cloud Security team can access

**Related tasks/epics**
- https://elasticco.atlassian.net/browse/PSEC-800

**Comment by oren-zohar** [comment]
@eyalkraft they are related but this is not a duplicate, we'd still want to migrate the long-running env to the new account

**Comment by amirbenun** [comment]
The objective behind that ticket is to have a single Elastic Cloud Organization which we use for creating long-running environments, QA environments and CI environments.

Since an Elastic Cloud user can only be a member of a single organization, we won't be able to log into our shared environment with our `elastic.co` emails while we all are already members of our private Elastic Cloud Organization. ([reference](https://www.elastic.co/guide/en/cloud/current/ec-organizations.html))
 
### Alternatives:
1. Create another `elastic.co` email address (cloud_security@elastic.co?) and create a new Elastic Cloud Organization.
The new organization will be managed by the owner of the new email account.  Next, we can create an API Key to be used in our CI pipelines. Thus, implementing the process of creating a new environment for the new organization by a single click.
Disadvantages:
   - Developers will not have access to Elastic Cloud (after an environment was created, someone will have to get the credentials and publish them)
2. Close our private Elastic Cloud Organization, and join a new Organization shared by all the CloudSecurity team. Tehila and Dima can be listed as organization owners with a full access. The rest of us can be deployment admins with permissions to create, edit, view, delete data and manage the configuration of all deployments.
Disadvantages:
   - All Developers have access to all the existing environments (we cannot exclude long-running and QA environments)

I would go with option 2, it is similar to the way we work with our AWS account.
It means that we need to invite all the team members to an existing organization (it can be done in anyone of our private organizations).
Before a team member joins the new organization, he will have to actively leave his current organization.

**Comment by amirbenun** [comment]
### Decision

By using both the staging and prod Elastic Cloud environments, we can have a shared organization on prod while maintaining the private organizations on staging:
 
1. We will keep our private environment on [staging.found.no](https://staging.found.no/), the environments we create here will be used for development.
2. We will establish a shared orgaznization  on [cloud.elastic.co](https://cloud.elastic.co/), the environments we create here are for QA cycles, long-running environments, and CI.

That way, our QA environments are more reliable and, and the long running environments will hold longer.

One open question remained, is it OK if a developer uses the shared organization on `cloud.elastic.co` for development? Or should we force developers to use `staging.found.no` for development environments by limit their access to `cloud.elastic.co`?

**Comment by oren-zohar** [comment]
we've decided to go with the cloud.elastic.co organization approach using email alias
