### ISSUE TITLE
[CIS GCP] Enrich events with project and org info

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#1236]
**Motivation**
Until now, we only focused on a single project, so CIS GCP events get linked with that project's ID.
When we support an organization level, we'll gather resources from multiple projects, which means we need to change how this works.
Also, we'll include the relevant organizational details for each event.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Each event is enriched with its project info.
- [ ] Each event is enriched with the org info (`cloud.organization.id` & `cloud.organization.name`)

**Related tasks/epics**
- related: https://github.com/elastic/cloudbeat/issues/1177

**Comment by kfirpeled** [comment]
project info should be `cloud.account.id` and `cloud.account.name`

**Comment by Omolola-Akinleye** [comment]
Events are enriched for project and org info
![Image](https://github.com/elastic/cloudbeat/assets/17135495/c7e3661f-dea3-417a-8ae2-cb37179e1654)
