### ISSUE TITLE
[CIS GCP] Support a cloud native deployment for GCP organizations 

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#1237]
**Motivation**
Provide a great onboarding experience for users using our integration to assess their GCP organization resources.

**Definition of done**
Provide a similar experience to the one we have today with project assessment.
- [ ] Update the required permissions to fetch resources for the entire org. 

**Out of scope**
Modifications to Cloudshell's URL - should remain the same.

**Comment by kfirpeled** [comment]
Ask @oren-zohar or @amirbenun for organization account for testings

- verify that more than one account has been verified

**Comment by Omolola-Akinleye** [comment]
Verified that mored than one account has been under organization account.

**Comment by Omolola-Akinleye** [comment]
Events are enriched for project and org info.

1. Enter project id  and org id
2. Ran cloud shell command with ORG id
3. Agent installed
4.  Go to discover then search `agent.id : "f05eec71-dfaf-4441-825d-adad3657a760" and cloud.account.name: ` 
5. Saw multiple cloud account names with the same org id


![Image](https://github.com/elastic/cloudbeat/assets/17135495/8b5cea8e-bebb-4405-8de0-c844923a54ec)


![Image](https://github.com/elastic/cloudbeat/assets/17135495/c7e3661f-dea3-417a-8ae2-cb37179e1654)
