### ISSUE TITLE
[BUG] Fleet UI - findings datastream is not available

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#124]
**Describe the bug**

CSP solution is not exposed under available datastreams. 
I'm not sure if anything should be available there or only data streams that expose a dashboard.

**Preconditions**
Kibana environment with csp plugin enabled
Agent installed with `CIS Kubernetes Benchmark` that generates findings

**To Reproduce**

1. Go to Fleet in kibana navigation bar
2. Click on `Data streams` tab

**Expected behavior**
You should see findings data stream from cloudbeat

**Screenshots 📸**

![Screen Shot 2022-05-11 at 16 20 34](https://user-images.githubusercontent.com/61654899/167859796-bb48c3ce-239d-4aa1-8036-a6a7d8ce1c7e.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT: [df225b213b188c81888141cee2ec191424fc0649](https://github.com/elastic/kibana/commits/df225b213b188c81888141cee2ec191424fc0649)
 - Endpoint Version:
 - Other Version: 
   - Cloudbeat Version: [9c1270716902466e02459ba252788698e4705471](https://github.com/elastic/cloudbeat/commits/9c1270716902466e02459ba252788698e4705471)

**Additional context**

**Comment by tinnytintin10** [comment]
also closing this issue out in preference for https://github.com/elastic/cloudbeat/issues/237
