### ISSUE TITLE
[BUG] Kibana - Group by - Search query is ignored after a "Group by" filter is applied

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#125]
**Describe the bug**
The search query is ignored when we use the "Group by" resource option.

**Preconditions**
Kibana + ES + CIS k8s integration installed.
Elastic agent deployed on a k8s cluster.

**To Reproduce**

Enter Kibana and navigate to the Cloud Security section.
1. Go to the findings page.
2. Apply a search that will provide results.
3. Click on the `Group by` dropdown list and select `Resource`.
4. The search has been deleted and a table is presented with all the resources.

**Expected behavior**
Apply the search & present only the resources that are relevant.

**Screen record**

https://user-images.githubusercontent.com/68195305/167870708-0c03c820-f016-49ec-bfc6-90ddcfe8b5d5.mov

**Tested locally not by using a snapshot**
 Kibana Version: 8.3.0 commit sha: 63f2d6647113d66cbb97039a8a780b76644ef727

**Comment by kfirpeled** [comment]
PR 
- https://github.com/elastic/kibana/pull/132849

**Comment by orouz** [comment]
fixed. query / filters are persisted on internal app navigations.
