### ISSUE TITLE
[CIS Azure] Storage Accounts rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1254]
We would like to implement the following rules:
- [x] 3.1 Ensure that 'Secure transfer required' is set to 'Enabled'
- [x] 3.8 Ensure Default Network Access Rule for Storage Accounts is Set to Deny
- [x] 3.15 Ensure the "Minimum TLS version" for storage accounts is set to "Version 1.2"
- [ ] 3.7 Ensure that 'Public access level' is disabled for storage accounts with blob containers
- [ ] 3.2 Ensure that ‘Enable Infrastructure Encryption’ for Each Storage Account in Azure Storage is Set to ‘enabled’
- [x] 3.9 Ensure 'Allow Azure services on the trusted services list to access this storage account' is Enabled for Storage Account Access
- [ ] 3.10 Ensure Private Endpoints are used to access Storage Accounts

**Comment by orestisfl** [comment]
**3.1 verified** :heavy_check_mark: 
![image](https://github.com/elastic/cloudbeat/assets/5778622/d95fea4a-d5f2-46c8-a9fb-dd1060aadac3)
![image](https://github.com/elastic/cloudbeat/assets/5778622/7222e4b4-f0fe-434d-8285-a448faf4e67c)
![image](https://github.com/elastic/cloudbeat/assets/5778622/98407dd3-3a10-4c88-84c8-77d238deca97)

From Azure Portal
1. Go to Storage Accounts
2. For each storage account, go to Configuration
3. Ensure that Secure transfer required is set to Enabled

**Comment by orestisfl** [comment]
**3.8 verified :heavy_check_mark:**

![image](https://github.com/elastic/cloudbeat/assets/5778622/be62e1a4-f03a-4145-9dd5-d72e70cb53ca)
![image](https://github.com/elastic/cloudbeat/assets/5778622/fdfebafd-ad8c-4fdf-9c13-c394bc09073d)
![image](https://github.com/elastic/cloudbeat/assets/5778622/da39c3b6-47fe-4ac2-a8da-7afb8b931eba)
![image](https://github.com/elastic/cloudbeat/assets/5778622/61117d59-ead6-42ed-9d23-6cc5de36f197)

1. Go to Storage Accounts
2. For each storage account, Click on the Networking blade.
3. Click the Firewalls and virtual networks heading.
4. Ensure that Allow access from All networks is not selected.

**Comment by orestisfl** [comment]
**3.7 verification failed :x: **

![image](https://github.com/elastic/cloudbeat/assets/5778622/d6884948-8be4-4e90-8bf6-671167786f03)

**Comment by orestisfl** [comment]
**3.2 verification failed** :x:

Not all storage accounts show up:
![image](https://github.com/elastic/cloudbeat/assets/5778622/499ab77c-7334-450e-a93c-e4d75628d32f)
![image](https://github.com/elastic/cloudbeat/assets/5778622/4a7e4228-520a-46ab-9f0e-9fbd46c793e2)

**Comment by orestisfl** [comment]
## 3.9 verification failed

![image](https://github.com/elastic/cloudbeat/assets/5778622/aff6bb63-0e11-4081-bb1c-3b7aef73085e)
![image](https://github.com/elastic/cloudbeat/assets/5778622/1d712f66-49b5-4349-9334-c2f38637252b)
### This should fail but it passes :x:
"Public network access" set to "Disabled" should fail the rule
![image](https://github.com/elastic/cloudbeat/assets/5778622/c6ea62a4-cb52-4112-9ecc-c4b2febea55e)
### This should pass and it does :heavy_check_mark: 
"Allow Azure services on the trusted services list to access this storage account" is checked
![image](https://github.com/elastic/cloudbeat/assets/5778622/62322655-08f9-4fe5-972b-98f8435f867f)

## Instructions
1. Go to Storage Accounts
2. For each storage account, Click on the Networking blade
3. Click on the Firewalls and virtual networks heading.
4. Ensure that Enabled from selected virtual networks and IP addresses is
selected.
5. Ensure that Allow Azure services on the trusted services list to access
this storage account is checked in Exceptions.

**Comment by jeniawhite** [comment]
3.15 - Works as expected
<img width="856" alt="Screenshot 2023-10-23 at 12 02 03" src="https://github.com/elastic/cloudbeat/assets/12246907/057f527d-71a4-4bf5-9559-74e973aef476">

3.2 - There are classic storage accounts and regular storage accounts, inside the regular storage accounts there are multiple versions (`Storage, StorageV2`).
`StorageV2` has value for the encryption property:  
<img width="575" alt="Screenshot 2023-10-23 at 12 27 03" src="https://github.com/elastic/cloudbeat/assets/12246907/df7232d2-b620-4213-b64f-10c0929f7666">
`Storage` (`V1`) doesn't have that value:
<img width="574" alt="Screenshot 2023-10-23 at 12 27 44" src="https://github.com/elastic/cloudbeat/assets/12246907/9006835a-f80f-4f21-99a1-06c72296ed09">
This is why we do not evaluate such a storage account.
When I attempted to create a `V1` account with encryption, it told me that this was not supported:
<img width="1571" alt="Screenshot 2023-10-23 at 12 28 46" src="https://github.com/elastic/cloudbeat/assets/12246907/34cbcf98-d758-4fc2-835c-b44e389fbe36">
I will change to fail evaluation when there is no such property.

3.9 - Works as expected
![Screenshot 2023-10-23 at 14 25 54](https://github.com/elastic/cloudbeat/assets/12246907/28e3c7f6-ad70-452b-8d21-96d341ba444b)
![Screenshot 2023-10-23 at 14 26 33](https://github.com/elastic/cloudbeat/assets/12246907/2c8e41d8-c435-44e6-8246-8e272607feb7)
![Screenshot 2023-10-23 at 14 26 50](https://github.com/elastic/cloudbeat/assets/12246907/abfd4be4-34ab-48b0-8d63-722ab10e04ea)

3.10 - The current implementation had a problem with an empty array (apparently `every` clause on an empty array in `rego` results in success regardless of the query).
Removed to just check the count of items like the benchmark PDF (yet Azure implemented it differently, and I followed their implementation).

3.7 - Miss-type verified under `encryption` instead of root level.

**Comment by orestisfl** [comment]
> 3.9 - Works as expected

Confirmed with the cli:
```
...
    "networkRuleSet": {
      "bypass": "AzureServices",
      "defaultAction": "Deny",
      "ipRules": [],
      "resourceAccessRules": [
        {
          "resourceId": "/subscriptions/<sub-id>/providers/Microsoft.Security/datascanners/StorageDataScanner",
          "tenantId": "<tenant id>"
        }
      ],
```

I guess the UI does not reflect that but the property is there

**Comment by orestisfl** [comment]
@kfirpeled Please verify 3.2, 3.7, 3.10 again in BC4
