### ISSUE TITLE
[CIS Azure] Database Services rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1255]
We would like to implement the following rules:
- [x] 4.5.1 Ensure That 'Firewalls & Networks' Is Limited to Use Selected Networks Instead of All Networks
- [x] 4.1.2 Ensure no Azure SQL Databases allow ingress from 0.0.0.0/0 (ANY IP)
- [x] 4.1.4 Ensure that Azure Active Directory Admin is Configured for SQL Servers
- [x] 4.3.1 Ensure 'Enforce SSL connection' is set to 'ENABLED' for PostgreSQL Database Server
- [x] 4.4.1 Ensure 'Enforce SSL connection' is set to 'Enabled' for Standard MySQL Database Server

**Comment by orestisfl** [comment]
## 4.4.1 confirmed :heavy_check_mark: 

![image](https://github.com/elastic/cloudbeat/assets/5778622/7e6a1f98-bb20-4461-9b36-c75cc6bcf888)

## Instructions

1. Login to Azure Portal using https://portal.azure.com
2. Go to Azure Database for MySQL servers
3. For each database, click on Connection security
4. In SSL settings, click on ENABLED to Enforce SSL connections

Single servers are not supported in the UI anymore so I had to create them with:
```
az mysql server create --resource-group evgb --name rule-441-fail --location westus --admin-user myadmin --admin-password 'xxx' --sku-name GP_Gen5_2
```

**Comment by orestisfl** [comment]
## 4.1.4 confirmed :heavy_check_mark: 

![image](https://github.com/elastic/cloudbeat/assets/5778622/41287c91-b4f6-4971-9afc-5dfee846382e)
![image](https://github.com/elastic/cloudbeat/assets/5778622/8b170d26-a91d-4a2c-b959-1805aab340ff)

**Comment by orestisfl** [comment]
## 4.5.1 Verified :heavy_check_mark: 

![image](https://github.com/elastic/cloudbeat/assets/5778622/444a00fe-7b02-4532-a249-4dddd91eeb1c)
![image](https://github.com/elastic/cloudbeat/assets/5778622/6e43839f-574a-4ef1-9d90-ab97679957ae)
