### ISSUE TITLE
[CIS Azure] Networking rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1257]
We would like to implement the following rules:
- [ ] 6.6 Ensure that Network Watcher is 'Enabled'
- [x] 6.5 Ensure that Network Security Group Flow Log retention period is 'greater than 90 days'

**Comment by orestisfl** [comment]
## 6.6 verification failed :x:

![image](https://github.com/elastic/cloudbeat/assets/5778622/67079f78-5312-4932-8980-00d2036d84ba)

The finding page only returns the regions where a network watcher does exist. However, we must fail the rule for regions where a network watcher doesn't exist.

## Instructions

From Azure CLI
```
az network watcher list
```
This will list all regions where provisioningState is Succeeded.
Then run
```
az account list-locations
```
This will list all regions that exist in the subscription. Compare this list to the previous
one to ensure that for all regions, provisioningState is set to Succeeded.

**Comment by orestisfl** [comment]
## 6.5 verified :heavy_check_mark: 

![image](https://github.com/elastic/cloudbeat/assets/5778622/9cd152ca-3a49-4772-9125-56510f09badb)
