### ISSUE TITLE
[CIS Azure] Virtual Machines rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1258]
We would like to implement the following rules:
- [ ] 7.1 Ensure an Azure Bastion Host Exists
- [x] 7.2 Ensure Virtual Machines are utilizing Managed Disks
- [x] 7.3 Ensure that 'OS and Data' disks are encrypted with Customer Managed Key (CMK)
- [x] 7.4 Ensure that 'Unattached disks' are encrypted with 'Customer Managed Key' (CMK)

**Comment by orestisfl** [comment]
@kfirpeled Please only verify the 7.1 rule

**Comment by maxcold** [comment]
@animehart pls check this one with @jeniawhite

**Comment by animehart** [comment]
had a chat with @jeniawhite , this will be verified on next BC (BC5)
