### ISSUE TITLE
[BUG] Kibana - Can not update rules activation status, UI reflects wrong state

### ISSUE THREAD

**Issue by orouz** [elastic/cloudbeat#126]
**Describe the bug**

after changing a rule status and clicking "Save" we get a 500 error from the `/update_rules_config` API route
in addition, because our current flow is like this:
 - FE calls SO client to update the saved object rules
 - FE calls BE to update 

the UI shows the rule as **disabled** (as the saved object update call didn't fail) but the changes **will not** propagate to the beat as the server returned an error. 

**Preconditions**
- CIS integration installed

**To Reproduce**

1.  toggle a rule
2. click save 

**Expected behavior**

rules are saved without an error

**Screenshots**

### UI 
![Screen Shot 2022-05-11 at 17 23 37](https://user-images.githubusercontent.com/20814186/167873236-4bbf88bc-076d-4a3b-a1b4-2082099cb6e7.png)

### Network
<img width="1147" alt="Screen Shot 2022-05-11 at 17 23 44" src="https://user-images.githubusercontent.com/20814186/167873238-f065ad46-f32d-493f-8441-7a7fac351c1d.png">

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version:  `df225b213b188c81888141cee2ec191424fc0649`
 - Endpoint Version:
 - Other Version: 

**Additional context**

- none yet

**Comment by eyalkraft** [comment]
Seems like this is a problem with the change introduces in version 0.8 of our integration.
https://github.com/elastic/integrations/blob/main/packages/cloud_security_posture/data_stream/findings/agent/stream/stream.yml.hbs#L2
Kibana fails on formatting this since the formatting results with an illegal Yaml.
```
name: Findings
data_yaml: {{dataYaml}}
processors:
  - add_cluster_id: ~
```
Or formatted
```
name: Findings
data_yaml: active_rules: ...
processors:
  - add_cluster_id: ~
```
@kfirpeled

**Comment by yashtewari** [comment]
Interesting. When modified via the "Rules Activation Yaml" field on the edit integration page, a correct YAML is created and sent to the beat.
<img width="479" alt="Screenshot 2022-05-12 at 7 45 29 AM" src="https://user-images.githubusercontent.com/9020112/167978567-224ff442-0b10-420c-89ab-45f5ff30ef33.png">
.
<img width="703" alt="Screenshot 2022-05-12 at 7 46 25 AM" src="https://user-images.githubusercontent.com/9020112/167978659-442d3f21-dbe0-49db-9ec1-c81e94c8130d.png">

The package knows that the field is meant to be a YAML, so it could be that it applies appropriate formatting when changes are made through the auto-generated Kibana text box. I think we should add sanity checks before `/update_rules_config` is called, as well as add some formatting logic to the `.hbs` file. I'll try out the latter.

**Comment by kfirpeled** [comment]
@CohenIdo please verify if it is fixed, and attach relevant PRs to the ticket.

**Comment by CohenIdo** [comment]
Kibana PR:
- https://github.com/elastic/kibana/pull/132118
Integration PR:
- https://github.com/elastic/integrations/pull/3346
 
The 500 bug is solved, the change apply and I found the change in the cloudbeat. 

@kfirpeled, @orouz - FE calls the saved-object API and then the *update_rules_config* API, so even if the second call fails, the user will still see the change applied. 
Would we like to solve it on this ticket or to create a new one for that?

**Comment by orouz** [comment]
> FE calls the saved-object API and then the update_rules_config API, so even if the second call fails, the user will still see the change applied.
Would we like to solve it on this ticket or to create a new one for that?

true! we need to make this a transaction that fails/succeeds only if both requests worked. 

i suggest we start with the following: 
1. user makes local changes
2. user clicks "save"
3. FE sends a request to `/update_rules_config` with the new rules state in the request `body`
4. BE tries to save the new rules state to the concrete rule saved object index
-  on a failed request, return an error to FE. 
-  on a successful request, BE tries to call `PackagePolicyServiceInterface["update"]` 
-  on a failed request,  rollback rules state to previous one and return an error to FE 
- on a successful request, return 200 with no data 

then FE can use the response of `update_rules_config` to re-fetch data or show an error. 

worth noting, `PackagePolicyServiceInterface["update"]` also uses the saved-objects client to write data
so we're effectively writing to our own index, reading it and passing it to another index. we might be able to optimize this further by reusing the same index.

**Comment by kfirpeled** [comment]
> Would we like to solve it on this ticket or to create a new one for that?

Open a new one, thanks!

**Comment by CohenIdo** [comment]
https://github.com/elastic/cloudbeat/issues/155
