### ISSUE TITLE
Failure in multi-account CSPM setup when specifying non-root organization id

### ISSUE THREAD

**Issue by CohenIdo** [elastic/cloudbeat#1265]
**Describe the bug**
AWS multi organizations cloudFormation fails when specifying organization id that differ from root one. 

**Stack event logs:** 
<img width="2291" alt="image" src="https://github.com/elastic/cloudbeat/assets/90558359/a42557f6-a460-4ab5-a61c-af719032d990">

Although the error says the stack exists it was deleted before, PM to me or to @oren-zohar to get the full video which show the full installation process. (the video contains creds and therefore is not attached to the issue). 

[Test Instructions](https://elastic.slack.com/archives/C05EPKJ5XSL/p1692195672840809?thread_ts=1692195667.190889&cid=C05EPKJ5XSL)

**Comment by orestisfl** [comment]
Closing as it's not a bug: the OU id must be used in the field, not the account id
