### ISSUE TITLE
[CIS Azure] Introduce an automation for updating the ARM template URL in the integrations repo

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1276]
**Motivation**
In the integration repo we keep a ARM template url, responsible for redirecting the user to Azure portal.
This link should be updated every minor release, whenever `cloudbeat` is branching out to the new version specific branch.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Introduce a CI step that creates a new PR for the integrations repo once the `cloudbeat` version is being updated

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by orouz** [comment]
closed in favor of https://github.com/elastic/cloudbeat/issues/1675
