### ISSUE TITLE
[CIS Azure] Kibana implementation for the new integration

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1279]
**Motivation**
Make sure that the benchmark is supported in Kibana.
There are some key points:
- [ ] We would like the user to be able to assign custom credentials without assuming a role
- [ ] We would like to have a deploy link similar to `CloudFormation` but using the `Azure ARM template`, it works in a similar way and the deployment happens on the customer's Azure portal (the template link is to either GitHub or S3)

**Definition of done**
What needs to be completed at the end of this task
- [ ] The benchmark should be supported with all of the dashboards, deployment flow, manual and assume role credentials

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by kfirpeled** [comment]
closed as duplication
