### ISSUE TITLE
[BUG] Installing CSP integration when the Kibana plugin is disabled fails

### ISSUE THREAD

**Issue by eyalkraft** [elastic/cloudbeat#128]
**Describe the bug**

When installing our integration withourt first enabling our Kibana plugin, the installation fails.
This happens since the saved object type `csp-rule-template` isn't registered.

**Preconditions**

Don't enable our Kibana plugin.
(Don't do this: `xpack.cloudSecurityPosture.enabled: true`) 

**To Reproduce**

Install the integration

**Expected behavior**

No error, some indication that the `xpack.cloudSecurityPosture.enabled: true` configuration is required.

**Screenshots**
<img width="1728" alt="Screen Shot 2022-05-11 at 18 31 12" src="https://user-images.githubusercontent.com/63912106/167890440-ae75f0a4-6bb0-41f6-9419-ae58189e4dc0.png">

**Comment by amitkanfer** [comment]
@eyalkraft how about preventing this from happening in the integration itself? (not allowing to install the integration if the flag doesn't exist or is `false`)?

not sure if it's a preferred option, but just an option worth exploring...?

**Comment by kfirpeled** [comment]
@joshdover we are experiencing this issue when trying to install our integration when the SO `csp-rule-template` is being registered using our plugin. And the plugin is not running by default. 

How do you suggest to solve this?

**Comment by eyalkraft** [comment]
> Not allowing to install the integration if the flag doesn't exist or is false

@amitkanfer Sounds like a great option. It will require some research (simple though).
Also relates with other changes @tinnytintin10 suggested for this page regarding deployment:
- https://github.com/elastic/cloudbeat/issues/123#issuecomment-1126448570

Related old task:
- https://github.com/elastic/security-team/issues/3044

**Comment by amitkanfer** [comment]
Feels like worth exploring it (but only if it's relatively easy to explore and then implement) as it's probably the better UX.
Let's not invest too much here. We want to remove the feature flag in 8.4

**Comment by tinnytintin10** [comment]
> Feels like worth exploring it (but only if it's relatively easy to explore and then implement) as it's probably the better UX.
Let's not invest too much here. We want to remove the feature flag in 8.4

++. Agreed. It's a nice to have that won't be necessary in 8.4

**Comment by eyalkraft** [comment]
@uri-weisman Since changing the whole installation page appears to be out of scope for the 8.3 release, Let's change this task:
1. We'll continue this research with https://github.com/elastic/security-team/issues/3044 later on
2. Following the telemetry lecture we had, discuss with @lizozom and try to figure out if we will be able to find out how many users have tried installing our integration and failed (out of the box - is this information already collected? where could we find it?)
3. The priority for this task is being lowered, and we will not fix this bug. Our integration already has the proper documentation:
![Image](https://user-images.githubusercontent.com/63912106/168851922-56410a30-f0be-4fe0-883b-e2a6a7351f11.png)

cc @tehilashn

**Comment by uri-weisman** [comment]
> 2. Following the telemetry lecture we had, discuss with @lizozom and try to figure out if we will be able to find out how many users have tried installing our integration and failed (out of the box - is this information already collected? where could we find it?)

 
@eyalkraft, @tehilashn - "Fullstory" might provide us with the information we need - do some users fail to install our integration?
Having said that, I still need to figure out how can we trace the user identity.

It's possible to create a metric that counts the number of Ajax errors (us trying to update the fleet API with the CSP rule templates prior to their registration) for a certain URL.

![Screen Shot 2022-05-19 at 14 59 37](https://user-images.githubusercontent.com/68195305/169290750-d07f99d7-b56f-4742-935f-845c3134526e.png)
[Fullstory search query](https://app.fullstory.com/ui/G3PDG/segments/everyone/people:search:MlTJ42O1yRxG/0)

**Comment by uri-weisman** [comment]
After some fine-tuning, I was able to capture data.
Fullstory results provide screen records and some information about the user (user id, deployment URL) that will help to trace him.

**Screen records**


https://user-images.githubusercontent.com/68195305/169688558-aabba79f-368b-4a10-925a-eab1d2db9b86.mov


[FullStory query](https://app.fullstory.com/ui/G3PDG/funnels/create/1898047025/user/4799099348979712?step=1&completed=true&completeSessions=false)

Do you want me to create a metric for capturing this data?

**Comment by tinnytintin10** [comment]
very nice! Taking a step back, the higher-level question to try and answer would be "How many users are adding our integration" (something along these lines) from there we can further narrow down users that tried adding the integration without enabling the plugin, etc. I will capture this in https://github.com/elastic/security-team/issues/3732

**Comment by eyalkraft** [comment]
Really cool @uri-weisman!
@tehilashn @tinnytintin10 can we close this bug then?

**Comment by tinnytintin10** [comment]
@tehilashn and I have synced up, we can close this out. ty both!

**Comment by CohenIdo** [comment]
Verification passed. using Kibana Commit sha: 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d
