### ISSUE TITLE
[CIS Azure] Support organizations in the integration/ARM template

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1281]
**Motivation**
We would like to support organizations and multiple accounts.
This means that the user should be able to input the subscriptions and management groups that he wants to scan.

There are multiple options on how we can do this:
- Since we want to make sure that the ARM template creates the necessary permissions for these subscriptions and management accounts, this means that we would need to input these values as parameters into the template.
The user will be able to pick the necessary values in the Azure portal and they should be propogated to `cloudbeat`, either via the identity provider or in any different manner (variables).

- Implement it as parameters of the integration and let the user fill them up in the Kibana UI, but this creates a problematic flow because we cannot propagate these values to the ARM template via link.
Which means that the user would need to pick assign them once again in the Azure portal UI in order for the template to create the necessary permissions (or if we will find a different way to overcome this).
The pros of this approach is that `cloudbeat` will receive the variables as part of the agent config and we do not see to figure out how to propogate these values to it or how for him to pull them from the identity.
 
**Definition of done**
What needs to be completed at the end of this task
- [ ] Support multiple subscriptions and management groups in the integration

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by oren-zohar** [comment]
> Implement it as parameters of the integration and let the user fill them up in the Kibana UI, but this creates a problematic flow because we cannot propagate these values to the ARM template via link.
Which means that the user would need to pick assign them once again in the Azure portal UI in order for the template to create the necessary permissions (or if we will find a different way to overcome this).
The pros of this approach is that cloudbeat will receive the variables as part of the agent config and we do not see to figure out how to propogate these values to it or how for him to pull them from the identity.

@orestisfl let's open a separate ticket for it 🙏

**Comment by kfirpeled** [comment]
Will be tested as part of the new org flow

**Comment by maxcold** [comment]
I was able to use the ARM template for the org option and can see the findings in the environment from the subscriptions of that org

![Image](https://github.com/elastic/cloudbeat/assets/478762/0c3c0a60-6d17-46e4-8ecd-5ad0950651e2)
