### ISSUE TITLE
[CIS Azure] Import new benchmark into csp-security-policies

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1283]
**Motivation**
In order to support a new benchmark we need to import the CSV of the Azure benchmark as part of the repository.
Then using that CSV we will be able to generate the relevant metadata YAMLs for the rules and also the rule templates for the integration in order for Kibana to use.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Make sure that the benchmark is imported with all of the metadata that is needed and the pre-commit and CI is building the metadata for the rules and required templates

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by orestisfl** [comment]
For verification: Check that all the rules exist in "Benchmark Rules" and are in correct categories.

**Comment by animehart** [comment]
CIS Azure new rules are added in Benchmark page
<img width="1421" alt="Screenshot 2023-10-26 at 2 27 18 PM" src="https://github.com/elastic/cloudbeat/assets/8703149/b7318252-3bb1-4908-b30b-0e074cad3100">
<img width="1410" alt="Screenshot 2023-10-26 at 2 27 27 PM" src="https://github.com/elastic/cloudbeat/assets/8703149/8cc9cf24-61bc-4cca-a4d5-e37a258d65e6">
