### ISSUE TITLE
[CIS Azure] Implement auth/credentials provider (Automated)

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1289]
**Motivation**
We would like to make sure that we support manual credentials and assuming a role.
You can read more about the [authentication options](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#defaultazurecredential).

There is a similar implementation of this abstraction in the GCP benchmark using the credentials and authentication providers [here](https://github.com/elastic/cloudbeat/tree/main/resources/providers/gcplib/auth).

Implementing in a similar fashion for Azure will provide the necessary authentication data to evaluate the benchmark.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Implement Azure credentials in the `cloudbeat` config
- [ ] Implement auth and credential providers for Azure

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by animehart** [comment]
Users are able to deploy using ARM Template, CIS Azure Findings flows into Kibana
![Image](https://github.com/elastic/cloudbeat/assets/8703149/060ecb5c-caeb-4382-bc85-886cb6ec0124)
![Image](https://github.com/elastic/cloudbeat/assets/8703149/c79685fb-a46e-46c8-97dc-0818b09142e2)
![Image](https://github.com/elastic/cloudbeat/assets/8703149/92386420-0305-4e49-a470-a3f82189371b)
