### ISSUE TITLE
[BUG] Error While saving changes to a benchmark rule(s) activation state

### ISSUE THREAD

**Issue by tinnytintin10** [elastic/cloudbeat#129]
## Describe the bug

When I proceed to save the changes I make to a benchmark rule's activation state, I get an Internal Server Error which leads me to believe that my changes didn't take effect, however, when I navigate away from the benchmarks page and come back it looks like the save did work (from a UI perspective). Take a look at the video below for an example of this bug.

## To Reproduce

Activate / deactivate a rule
Save changes
Navigate to a different page
Come back to the benchmark integration page
Expected behavior

If there was an error in updating the rules, the UI should reflect that (rule activation statues should return to the original/default state)

## Screenshots

https://user-images.githubusercontent.com/53792284/167943052-bb100254-3f75-4ee7-9d5e-7b9b22117191.mov

## Additional context

Was able to reproduce this bug locally and on a cloud deployment

**Comment by tinnytintin10** [comment]
@tehilashn I don't have the necessary permissions to add this to the csp-project board...

**Comment by ari-aviran** [comment]
Duplicate: https://github.com/elastic/cloudbeat/issues/126
