### ISSUE TITLE
[CIS Azure] Add a new benchmark type for CIS Azure

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1290]
**Motivation**
Add a new benchmark type - cis_azure to support the new integration

**Definition of done**
What needs to be completed at the end of this task
- [ ] Merge new input type to [agent spec](https://github.com/elastic/elastic-agent/blob/main/specs/cloudbeat.spec.yml)
- [ ] Add input to the [manifest](https://github.com/elastic/integrations/blob/main/packages/cloud_security_posture/manifest.yml)
- [ ] `cloudbeat` should support the new benchmark type

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by jeniawhite** [comment]
Integration already has implementation for `CIS Azure`:
- https://github.com/elastic/integrations/blob/main/packages/cloud_security_posture/manifest.yml#L129-L131

**Comment by oren-zohar** [comment]
Verified: 


![Image](https://github.com/elastic/cloudbeat/assets/85433724/1f137dc2-f90e-47e3-89e2-cea4128c0a78)
