### ISSUE TITLE
[CIS Azure] Implement CIS Azure authentication methods in integration's hbs manifests

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1292]
**Motivation**
Update the integration's `hbs` manifests of the CIS Azure benchmark to support Azure's authentication methods.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Integration passes the required authentication information to `cloudbeat`
- [ ] Both manual and automatic authentication flows are supported

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by kfirpeled** [comment]
Please place new fields/variables under `azure` hierarchy 
See `gcp` as an example

**Comment by kfirpeled** [comment]
Will be tested as part of the new manual flow, skipping this issue tests
