### ISSUE TITLE
[CIS Azure] Event index mapping and construction

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1293]
**Motivation**
We would like to make sure that the index and integration mappings are configured correctly to support the CIS Azure benchmark findings data.

We need to ship metadata + ECS fields on findings.
Map the fetched metadata about resources to the appropriate ECS field set, enabling users to quickly search for relevant resources using familiar fields.

- Should contain at least an Indicator of whether this is a CSPM finding or not
- Indicator of which cloud provider
- Resource location/region
- Management group/s id/s (might be considered sensitive)?
- Subscription/s id/s (might be considered sensitive)?
- Resource group/s
- ID of the resource
- Find out if we should ship something additional

**Definition of done**
What needs to be completed at the end of this task
- [ ] Azure custom fields should be mapped and the user should be able to query them

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by kfirpeled** [comment]
@oren-zohar we're not sure what should be tested here

**Comment by opauloh** [comment]
Verified (Taking into account partial support)

Kibana 8.12.0
Commit 93cff0aacd70bd0835cd244348f742ba3cafc4aa


![Image](https://github.com/elastic/cloudbeat/assets/19270322/1daa1111-6d28-49c8-ae4d-5a93f60320ee)



![Image](https://github.com/elastic/cloudbeat/assets/19270322/7d20c539-efda-4762-b40f-5f0f525a0be3)



![Image](https://github.com/elastic/cloudbeat/assets/19270322/78e61ccb-6f61-4c20-9e6d-5bd70537ca19)
