### ISSUE TITLE
[CIS Azure] Add Azure ARM template URL for the CIS Azure integration

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1296]
**Motivation**
In order for Kibana to redirect the user to the ARM template it needs a link to the template.
This link can either be a GitHub link or an S3 link (most common options).
We need to add and maintain this link as part of the integration. 

**Definition of done**
What needs to be completed at the end of this task
- [x] Decide what should be the right approach (s3 vs GH)
- [x] Add a new input var for storing the Azure ARM template URL that will be used to redirect the client
- [x] Upload CI workflow (if S3 is chosen)

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by orouz** [comment]
8.11 BC3 

--- 

verified link to ARM template is working with paramaters:


![Screenshot 2023-10-18 at 15 34 42](https://github.com/elastic/cloudbeat/assets/20814186/a8b8b2ef-f83f-4dc8-8343-a7b69c8c3852)
