### ISSUE TITLE
[Cloud Posture][Telemetry] Add package policy id  to findings and vulnerabilities indice

### ISSUE THREAD

**Issue by Omolola-Akinleye** [elastic/cloudbeat#1298]
**Motivation**
Why are we doing this task? what is the value to the user?
We  created a [discussion ticket](https://github.com/elastic/kibana/discussions/165211)) where we wanted to start indexing the package policy ID in order for the [feature adoption telemetry epic](https://github.com/elastic/security-team/issues/7263). 

Currently, the package policy has an internal configuration in which features have been installed by an integration policy:
* cloud_formation_url vs. manual for AWS
* cloud_shell_url vs. manual for GCP
* Single vs. multi-organization accounts for AWS
 
**Definition of done**
What needs to be completed at the end of this task
- [ ] Add `cloud_security_posture.package_policy.id` and `cloud_security_posture.package_policy.revision` to **findings** index
- [ ] Add `cloud_security_posture.package_policy.id` and `cloud_security_posture.package_policy.revision` to  **vulnerabilities** index

**Out of scope**
What should not be included in this task

**Related tasks/epics**

- https://github.com/elastic/integrations/pull/7890

**Comment by CohenIdo** [comment]
CC: @oren-zohar

**Comment by Omolola-Akinleye** [comment]
@eyalkraft Thanks for the context.  `agent.policy_id`  could work well since each agent policy also stores the package policy.   @CohenIdo which method do you prefer the `agent.policy_id` or passing specific values to cloudbeat to add to findings?

**Comment by CohenIdo** [comment]
Our goal is to couple between findings and package id for supporting feature adoption requirements (checkout items 8 and 9). 


Technically we can use the agent policy id for that but it will create overhead in Kibana: 
1. Query findings by account - the account will contain the agent policy id. 
2. For each account we will need to call the agent api to get the package policies the agent id contains.
3. Filter the relevant package policy id based on the account type (CSPM / KSPM / CNVM). 

In case cloudbeat will send the package policy id on the findings no additional work is needed in Kibana (only step 1).

**Comment by oren-zohar** [comment]
> In case cloudbeat will send the package policy id on the findings no additional work is needed in Kibana (only step 1).

@CohenIdo If I understand @eyalkraft, policy id is not accessible from cloudbeat unless we change what the agent sends to every beat as part of the config, so this is not just a small change in the event information we collect from cloudbeat.

**Comment by CohenIdo** [comment]
Yes @oren-zohar, you understand correctly, But in this case cloudbeat will repeat the same values (cloud provider, deployment type, etc)  on all the findings, so on from one hand it's easier but not so efficient.  WDYT?

**Comment by oren-zohar** [comment]
@CohenIdo I'm sorry, can you clarify?

**Comment by CohenIdo** [comment]
To be on the same page  - @eyalkraft suggested taking the package policy fields (cloud provider, setup method, account type etc) and attaching them to the findings, This approach will populate our findings with the same repetitive data. 

So for example, the fields we need (i.e. `cloud_provider": "aws" / "account_type": "single" / "setup_method": "manual"` will repeat on each finding.

**Comment by oren-zohar** [comment]
Hey @eyalkraft, it looks like other integrations, such as [cloud_defend](https://github.com/elastic/integrations/blob/3a8539e31405fd24543a66241b88d3c522bec8dd/packages/cloud_defend/data_stream/file/fields/fields.yml#L4), have a mapping for `package_policy_id`. This suggests that it might not be too complicated for Cloudbeat to directly access this field and attach it to its findings. @mitodrummer, would you be able to assist with this?

**Comment by Omolola-Akinleye** [comment]
@oren-zohar I met with @mitodrummer  and informed me Cloud Defend indexes the `package_policy_id`  by extracting the `package_policy_id` from the agent config. Here [Cloud Defend's example ](https://github.com/elastic/cloud-defend/blob/7389b20e34ddb92094f585ec7569e5c27e73d270/modules/config/agent_unit.go#L220) Can Cloudbeat also get the `package_policy_id` from the agent config?

**Comment by kfirpeled** [comment]
- verify findings contains `cloud_security_posture.package_policy.id`

**Comment by JordanSh** [comment]
![Image](https://github.com/elastic/cloudbeat/assets/51442161/90658acb-f03f-4666-b00f-9ac35918675c)
