### ISSUE TITLE
[BUG] Findings page table - Fix columns spacing

### ISSUE THREAD

**Issue by tinnytintin10** [elastic/cloudbeat#130]
**Describe the bug**

The findings table (grouped by none) isn't aligned well. There is an empty gap with no content, let's stretch the other columns to fill up the space. Take a look at the screenshot below

**To Reproduce**

1. Go to the findings page grouped by none 

**Expected behavior**

The table should use all the space available to it. 

**Screenshots**

<img width="2032" alt="Screen Shot 2022-05-11 at 1 40 07 PM" src="https://user-images.githubusercontent.com/53792284/167944235-3bb3f034-6c65-44b0-ab95-d8d1a2ec2adb.png">

**Comment by tinnytintin10** [comment]
Same issue on the group by resource table: 

<img width="1624" alt="Screen Shot 2022-05-13 at 11 46 43 AM" src="https://user-images.githubusercontent.com/53792284/168347833-61f4315f-ddf8-4fda-87e2-d88ad34e5136.png">

**Comment by ari-aviran** [comment]
PR: https://github.com/elastic/kibana/pull/132793
