### ISSUE TITLE
[CIS Azure] Support organizations in ARG (Azure resource graph)

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1300]
**Motivation**
We are querying the resources with the help of [ARG](https://learn.microsoft.com/en-us/azure/governance/resource-graph/overview), it has a support for querying multiple subscriptions and management groups.

```golang
// QueryRequest - Describes a query to be executed.
type QueryRequest struct {
	// REQUIRED; The resources query.
	Query *string

	// An array of facet requests to be computed against the query result.
	Facets []*FacetRequest

	// Azure management groups against which to execute the query. Example: [ 'mg1', 'mg2' ]
	ManagementGroups []*string

	// The query evaluation options
	Options *QueryRequestOptions

	// Azure subscriptions against which to execute the query.
	Subscriptions []*string
}
```

**Definition of done**
What needs to be completed at the end of this task
- [ ] `cloudbeat` should query the relevant subscriptions and management groups

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by kfirpeled** [comment]
Will be tested as part of the new org flow

**Comment by maxcold** [comment]
tested the org flow in 
- https://github.com/elastic/cloudbeat/issues/1281
