### ISSUE TITLE
[CIS Azure] Enrich events with organization information

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1302]
**Motivation**
Until now, we only focused on a single subscription, so CIS Azure events get linked to a single "account".
When we support an organization level, we'll gather resources from multiple subscriptions and management groups, which means that we need to change how this works.
Also, we'll include the relevant organizational details for each event.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Each event is enriched with subscription/s and management group/s information

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by kfirpeled** [comment]
@oren-zohar it is not quite clear from the issue nor the PR what exactly we wish to test in the events

**Comment by orestisfl** [comment]
@kfirpeled Make sure the `cloud.Organization.{id,name}` fields are populated correctly.

**Comment by maxcold** [comment]
verified

![Image](https://github.com/elastic/cloudbeat/assets/478762/f9c05eff-e587-4419-82d2-fba03278bb17)
