### ISSUE TITLE
[BUG] Mousover text on benchmark rules page persists and covers content/buttons 

### ISSUE THREAD

**Issue by tinnytintin10** [elastic/cloudbeat#131]
**Describe the bug**

The mouseover text over the enable/disable toggle in benchmark rules persists after you have used the toggle and moved away. See the video below to see this behavior. 

**To Reproduce**

1. Go to a benchmark rules page 
2. Enable/disable the second rule 
3. Hover over the toggle above the one you click (trick step- you can't because it's blocked by the mouseover that persisted from the toggle below) 

**Expected behavior**

Mouseover text should disappear as soon as you hover away - that's why it's called mouseover ;) 

**Screenshots**

https://user-images.githubusercontent.com/53792284/167947306-de0b7f32-6601-45f0-a50b-8a4fa798d1c2.mov

**Additional context**

The mouseover text only disappears if you click on it

**Comment by gurevichdmitry** [comment]
Tooltips are disabled in 8.4 BC-1 version (58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d)
