### ISSUE TITLE
[Create Environment] Sanity tests - Add telemetry automated test for `cloud_security_posture`

### ISSUE THREAD

**Issue by CohenIdo** [elastic/cloudbeat#1315]
**Motivation**
As part of our environment sanity test, we would like to perform a telemetry test. 

It will verify that the telemetry payload includes cloud_security_posture and cloud_defend by calling the [API](https://docs.elastic.dev/telemetry/collection/snapshot-telemetry#telemetry-usage-payload-api). 

By performing the test, we will be able to verify that the telemetry data is being collected properly.

**Comment by CohenIdo** [comment]
cc: @gurevichdmitry @kfirpeled

**Comment by kfirpeled** [comment]
@CohenIdo can you elaborate on what should be tested here? what are the expected verifications?

**Comment by CohenIdo** [comment]
The test process should be as follow:
1. Verify all our products is installed and findings exists in the latest indices.
2. Execute [get telemetry API request](https://docs.elastic.dev/telemetry/collection/snapshot-telemetry#telemetry-usage-payload-api)
3. Verify the output contain the key `cloud_security_posture`. 
4. Verify the payload under the key `cloud_security_posture` contains the following keys: `indices`, `accounts_stats`, `resources_stats`, `rules_stats`, `installation_stats` and there are not empty.
5. Verify the `indices` payload contain the following keys: `findings`, `latest_findings`, `vulnerabilities`, `latest_vulnerabilities`, `score`, `latestPackageVersion`, `cspm`, `kspm`, `vuln_mgmt` and there are not empty. 
Example indices payload:
```json
              "indices": {
                "findings": {
                  "doc_count": 615,
                  "deleted": 0,
                  "size_in_bytes": 0,
                  "last_doc_timestamp": "2023-09-05T19:15:47.313Z"
                },
                "latest_findings": {
                  "doc_count": 123,
                  "deleted": 0,
                  "size_in_bytes": 0,
                  "last_doc_timestamp": "2023-09-05T19:15:47.313Z"
                },
                "vulnerabilities": {},
                "latest_vulnerabilities": {
                  "doc_count": 0,
                  "deleted": 0,
                  "size_in_bytes": 0,
                  "last_doc_timestamp": null
                },
                "score": {
                  "doc_count": 1572,
                  "deleted": 0,
                  "size_in_bytes": 0,
                  "last_doc_timestamp": null
                },
                "latestPackageVersion": "1.5.2",
                "cspm": {
                  "status": "not-installed",
                  "healthyAgents": 0,
                  "installedPackagePolicies": 0
                },
                "kspm": {
                  "status": "indexed",
                  "healthyAgents": 0,
                  "installedPackagePolicies": 1
                },
                "vuln_mgmt": {
                  "status": "not-installed",
                  "healthyAgents": 0,
                  "installedPackagePolicies": 0
                }
              },
```
7. `alerts_stats`, @opauloh can you describe how to test the alerts stats telemetry please ?
8. `cloud_defend` , @mitodrummer can you describe how to test the cloud defend telemetry please?

**Comment by opauloh** [comment]
7. Verify the payload under the key cloud_security_posture contains `alerts_stats`

7.1. For every integration installed (kspm, cspm, vuln_mgmt) with rules and alerts created, verify it contains the expected matching data.

Example of telemetry data for cspm:

```json
{
  "alerts_stats": [
    {
      "posture_type": "cspm",
      "rules_count": 1,
      "alerts_count": 2,
      "alerts_open_count": 2,
      "alerts_acknowledged_count": 0,
      "alerts_closed_count": 0
    }
  ]
}
```

Tests:

- It collects data for cspm
- It collects data for kspm
- It collects data for vuln_mgmt
- Count of rules created
- Count of Alerts
- Count of Alerts with Open Status
- Count of Alerts with Acknowledged Status
- Count of Alerts with Closed Status

**Comment by kfirpeled** [comment]
LGTM,
I would like that we would test that we do have findings, but for CNVM that might take a lot of time, so if that is the case we can skip checking vulnerabilities are more than 0

**Comment by CohenIdo** [comment]
Telemetry automation tests PR:
- https://github.com/elastic/cloudbeat/pull/1596

This PR includes automation tests for the following fetchers: 
-  indices stats
- cloud account stats
- installation stats
It doesn't include tests for:
- rules stats and resources stats since we are not using there data anymore
- The alert rules telemetry goes beyond what we've covered so far as part of this task. This involves reading the findings, creating rules based on them, triggering those rules, and then rechecking the telemetry. It seems like a lot to tackle in one go, so I'll create a separate task for this.

**Comment by CohenIdo** [comment]
Followup issues:
- https://github.com/elastic/security-team/issues/8149
- https://github.com/elastic/security-team/issues/8150

@kfirpeled
