### ISSUE TITLE
[BUG] Kibana - Group By - Resource records with zero failed findings are colored in red

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#132]
**Describe the bug**
In the `Group by` resource id table, resource records with zero failed findings are colored in red.

**Preconditions**
Kibana + ES + CIS k8s integration installed.
Elastic agent deployed on a k8s cluster.

**To Reproduce**

1. Enter Kibana and navigate to the Cloud Security section.
2. Go to the findings page.
3. Apply a search that will provide results.
4. Click on the Group by dropdown list and select Resource.
5. Notice that rows with zero failed findings are colored in red.

**Expected behavior**
Should be colored in green or any other indication for none failed findings.

**Screenshots**

<img width="1350" alt="Screen Shot 2022-05-11 at 17 36 58" src="https://user-images.githubusercontent.com/68195305/168007946-cf5ba9b2-1ce1-482a-8f99-5f3bdf8ff2e5.png">

**Tested locally, not by using a snapshot**
Kibana Version: 8.3.0 commit sha: 63f2d6647113d66cbb97039a8a780b76644ef727

**Comment by kfirpeled** [comment]
@tinnytintin10 , @einatjacoby what color would you like for `0` failed findings? black or green? or something else?

**Comment by tinnytintin10** [comment]
@kfirpeled let's go with green. Should look something like: 

![failingFindingsCountColor](https://user-images.githubusercontent.com/53792284/168548327-bab1fb79-5f31-441d-8175-39a6dc59f83d.png)

**Comment by kfirpeled** [comment]
solved in https://github.com/elastic/kibana/pull/132529
