### ISSUE TITLE
[CIS GCP] Deployment Manager Integration test

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#1323]
### Motivation
As a **premerge** test, an integration test of deploying an elastic agent with the deployment manager template can bring great coverage to the CloudShell deployment method.
The tests should cover both scopes, project and org.

### Components
- ESS stack
- GCP test account/org

### Test flow
This test should only run on PRs when the deployment-manager directory has been modified.
- Creating an agent policy with the GCP CSPM integration
- Deploy the relevant Deployment Manager stack on a GCP test project/org
- Make sure an agent has enrolled to Fleet
- Wait for Findings

### Related tasks/epics
- https://github.com/elastic/cloudbeat/issues/1322

**Comment by orouz** [comment]
https://github.com/elastic/cloudbeat/pull/1763 handles pre-merge test for changes in the deployment manager script for a **single account**

to run a test for an organization account, we'd need a dedicated gcp org which currently we don't have 

cc @oren-zohar
