### ISSUE TITLE
GCP: Resource names not filled with human-friendly names

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1324]
**Describe the bug**
The GCP integration does not display human-friendly resource names in the findings page

**Preconditions**
Tested with [8.10 BC4](https://staging.elastic.co/8.10.0-2afb299e/summary-8.10.0.html)

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Install GCP with either setup method
2. Go to findings
3. Click at any finding
4. Observe Resource ID & Name being the same

**Expected behavior**
The **Resource Name** should be filled with a human-friendly name, in the screenshots below for example, `API key 4` should be used.

**Screenshots**

![image](https://github.com/elastic/cloudbeat/assets/5778622/6a5f35f0-65dd-4973-a024-a2d3704526fa)
![image](https://github.com/elastic/cloudbeat/assets/5778622/d777e027-44a2-4655-a556-fa4cb86289aa)

**Comment by orouz** [comment]
`8.11` BC3 - (kibana `714189fa2b0f0a4d9f3865a8fce08261211570c8`)

---- 

verified 

![Screenshot 2023-10-18 at 14 25 47](https://github.com/elastic/cloudbeat/assets/20814186/dfe95320-f903-455b-b107-04a7dcaac0f1)
