### ISSUE TITLE
[KSPM EKS] EKS role is not authorized to perform the iam:ListAccountAliases action

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#1362]
**Describe the bug**
When deploying EKS KSPM integration with EKS role permissions, Cloudbeat encounters an issue that results in unexpected restarts. In the Cloudbeat log, the following error is recorded:

```
[elastic_agent.cloudbeat][error] Exiting: launcher could not run Beater: could not create beater: failed to initialize AWS config: failed to get AWS identity: failed to get aliases: operation error IAM: ListAccountAliases, https response error StatusCode: 403, RequestID: 9240fae6-dba4-4509-81c3-5e6855fbc069, api error AccessDenied: User: arn:aws:sts::704479110758:assumed-role/cloudbeat-tf-5jA/aws-go-sdk-1695130876926194821 is not authorized to perform: iam:ListAccountAliases on resource: * because no identity-based policy allows the iam:ListAccountAliases action.
```

**Workaround**
The `live-track-eks-policy` policy has been added to the `cloudbeat-tf-5jA` IAM role to grant the necessary permissions for Cloudbeat to function correctly.

**To Reproduce**

This issue has been consistently reproduced in the live track environment. To reproduce the problem, follow these steps:

1. Access the AWS IAM role named `cloudbeat-tf-5jA`.
2. Remove the `live-track-eks-policy` policy from the role.

**Expected behavior**
2. The Cloudbeat is functioning without encountering the IAM error, and there are no restarts performed.

**Desktop (please complete the following information):**
 - Kibana Version: 8.10.1
 - Endpoint Version: 8.10.1

**Comment by moukoublen** [comment]
Verified:
<img width="1349" alt="Screenshot 2024-02-22 at 1 39 11 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/4717d6e5-af8a-43e8-8e93-1eb40a16bd6f">
<img width="1348" alt="Screenshot 2024-02-22 at 1 38 53 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/9dc11a08-6282-429c-bd86-ba4eee7d64a1">
<img width="3322" alt="Screenshot 2024-02-22 at 1 38 42 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/f95dd51c-557b-42ec-bda9-2933bceb2ec3">
