### ISSUE TITLE
[GCP] Fix flaky integration test

### ISSUE THREAD

**Issue by orouz** [elastic/cloudbeat#1371]
**Describe the bug**
GCP integration test is failing in CI with the following:
```
/home/runner/work/cloudbeat/cloudbeat/tests/integration/tests/test_sanity_checks.py:153: AssertionError: The resource type 'cloud-compute' is missing
/home/runner/work/cloudbeat/cloudbeat/tests/integration/tests/test_sanity_checks.py:153: AssertionError: The resource type 'cloud-database' is missing
/home/runner/work/cloudbeat/cloudbeat/tests/integration/tests/test_sanity_checks.py:153: AssertionError: The resource type 'monitoring' is missing
/home/runner/work/cloudbeat/cloudbeat/tests/integration/tests/test_sanity_checks.py:153: AssertionError: The resource type 'cloud-storage' is missing
```

**To Reproduce**
1. see CI errors here: https://github.com/elastic/cloudbeat/actions/runs/6368950892/attempts/4?pr=1355 (4 attempts)

**Expected behavior**

CI should pass

**Comment by gurevichdmitry** [comment]
During the investigation, a new bug was discovered that prevents the tests from passing successfully. The task is now being moved to a blocked state until the bug is fixed.
- https://github.com/elastic/cloudbeat/issues/1575

**Comment by gurevichdmitry** [comment]
- https://github.com/elastic/security-team/issues/8179
