### ISSUE TITLE
[CIS Azure] Correct Type and SubType of resources

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1378]
**Describe the bug**
The FE derives the resource type from the sub type property and not from the type property.
We should refactor the types accordingly in order to make sure that the FE shows everything correctly.
This would require possible refactor in policies as well since we look at the type to decide what code to run.

**Expected behavior**
FE should show the resource types correctly and policies should evaluate correctly according to types.

**Comment by oren-zohar** [comment]
Verified: 



![Image](https://github.com/elastic/cloudbeat/assets/85433724/29430044-85d3-4708-aeed-8b9c02f1dd14)
