### ISSUE TITLE
[BUG] Kibana - My Benchmarks - `Created at` is not showing tooltip of the timestamp on hover

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#138]
**Describe the bug**

When showing a timestamp in the format of `moment ago`. It is a good practice to give the user the timestamp on hover. This is done on other screens already. We should align `My Benchmarks` page to the same behaviour

**Preconditions**
Kibana environment with csp plugin enabled

**To Reproduce**

1. Create an `CIS Kubernetes Benchmark` integration
2. Go to `My Benchmarks` page
3. Move the mouse pointer over the created time

**Expected behavior**
Timestamp showing the full timestamp

**Screenshots**
<img width="1467" alt="Screen Shot 2022-05-12 at 15 45 50" src="https://user-images.githubusercontent.com/61654899/168088031-e65a8ee6-388d-4e21-9b8e-42e93578e2b9.png">

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT: `e3e9e009fdde38c5fe51fcf2df8d5e3ecf50c7aa`
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by tinnytintin10** [comment]
We're also not showing the time in human-readable format, can we update this bug to address both?
![Image](https://user-images.githubusercontent.com/53792284/175971164-33307ff6-425c-4918-8186-5a80924d4f0c.png)

**Comment by JordanSh** [comment]
- https://github.com/elastic/kibana/pull/138227

@tinnytintin10 i missed your comment. I've kept the original behaviour of displaying the timestamp as is, i assumed we did that on purpose so it will be easier to copy-paste into the search bar.

should we change it to human readable format?

**Comment by ofiriro3** [comment]
Nice job @JordanSh - verified
