### ISSUE TITLE
[BUG] Kibana - Uninstall integration - Dashboard not showing previous result, instead it shows onboarding

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#141]
**Describe the bug**

When uninstalling an integration (aka removing assets) the user should be able to see previous results.
However the onboarding screen is being showed immediately 

**Preconditions**
Kibana environment with csp plugin enabled
Agent installed that generates findings

**To Reproduce**

1. Go to `Integrations` page
2. Click on `Installed integrations` tab
3. Go into `CIS Kubernetes Benchmark`
4. Click on `Settings` tab
5. Click on `Uninstall CIS Kubernetes Benchmark`
6. Go to `Cloud Security`

**Expected behavior**
See old results until the latest findings is empty

**Screenshots 📸**

![Screen Shot 2022-05-12 at 18 01 14](https://user-images.githubusercontent.com/61654899/168106309-587bbed4-7413-4f66-afd5-9a078e80eb43.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT: e3e9e009fdde38c5fe51fcf2df8d5e3ecf50c7aa
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by tinnytintin10** [comment]
@kfirpeled Uninstalling the integration should result in an empty state as we should be deleting all the underlying assets, no? If you agree let's close this out.

**Comment by tehilashn** [comment]
Should be resolved as part of https://github.com/elastic/security-team/issues/3764.

**Comment by JordanSh** [comment]
solved in:
- https://github.com/elastic/kibana/pull/137060

**Comment by CohenIdo** [comment]
Verification passed. using Kibana Commit sha: 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d
