### ISSUE TITLE
[CIS Azure] Microsoft Defender rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1412]
We would like to implement the following rules:
- [x] 2.1.18 Ensure That 'All users with the following roles' is set to 'Owner'
- [x] 2.1.20 Ensure That 'Notify about alerts with the following severity' is Set to 'High'
- [x] 2.1.15 Ensure that Auto provisioning of 'Log Analytics agent for Azure VMs' is Set to 'On'
- [x] 2.1.19 Ensure 'Additional email addresses' is Configured with a Security Contact Email

**Comment by romulets** [comment]
QA:

✅  2.1.15 Failed with Log Analytics agent for Azure VMs set to `off`
✅  2.1.15 Passed with Log Analytics agent for Azure VMs set to `on`
![image](https://github.com/elastic/cloudbeat/assets/5350001/a94cc483-bf1b-4210-9a4f-b6e373d63149)

✅  2.1.18 Failed with role contributor
✅  2.1.18 Passed with role Owner
![image](https://github.com/elastic/cloudbeat/assets/5350001/d5992f39-993a-4f27-88ba-1bcf00ffa897)


✅  2.1.19 Failed without email
✅  2.1.19 Passed with email
![image](https://github.com/elastic/cloudbeat/assets/5350001/b74f8f31-4d45-48dc-ac35-0b870bc2b7d4)

✅  2.1.20 Failed without notifications
✅  2.1.20 Passed with low level
✅  2.1.20 Passed with high level
![image](https://github.com/elastic/cloudbeat/assets/5350001/937d403f-3d3c-4694-b4e1-4adebd28576b)
