### ISSUE TITLE
[CIS Azure] Key Vault rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1413]
We would like to implement the following rules:
- [x] 8.5 Ensure the Key Vault is Recoverable

**Comment by orestisfl** [comment]
## 8.5 verified :heavy_check_mark:

![image](https://github.com/elastic/cloudbeat/assets/5778622/73f27a4a-e25c-4aad-aa45-8f5aacebb0d2)
![image](https://github.com/elastic/cloudbeat/assets/5778622/54d2fe67-dd77-4298-a471-030d4f020bb4)
![image](https://github.com/elastic/cloudbeat/assets/5778622/29cb72be-612f-40f3-837a-4ae9425fb11d)
