### ISSUE TITLE
[CIS Azure] Storage Accounts rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1416]
We would like to implement the following rules:
- [x] 3.11 Ensure Soft Delete is Enabled for Azure Containers and Blob Storage
- [ ] 3.5 Ensure Storage Logging is Enabled for Queue Service for 'Read', 'Write', and 'Delete' requests
- [x] 3.13 Ensure Storage logging is Enabled for Blob Service for 'Read', 'Write', and 'Delete' requests
- [x] 3.14 Ensure Storage Logging is Enabled for Table Service for 'Read', 'Write', and 'Delete' Requests

**Comment by orestisfl** [comment]
## 3.5 Failed to verify :x: 

![screenshot-2024-02-20T13:43:04 CET](https://github.com/elastic/cloudbeat/assets/5778622/097a7a2c-7b5b-4915-b602-5e7deb59e349)
![image](https://github.com/elastic/cloudbeat/assets/5778622/6a1d4d63-16b7-46aa-809f-9c595a925a09)

## 3.11 verified :heavy_check_mark: 
![screenshot-2024-02-20T12:51:28 CET](https://github.com/elastic/cloudbeat/assets/5778622/bc6983ba-5c2d-4642-8990-f22faf09945b)


## 3.13 verified :heavy_check_mark: 
![screenshot-2024-02-20T13:10:00 CET](https://github.com/elastic/cloudbeat/assets/5778622/6b3297f2-be47-4675-a7d8-1cbc02a53db3)


## 3.14 verified :heavy_check_mark: 
![screenshot-2024-02-20T13:11:44 CET](https://github.com/elastic/cloudbeat/assets/5778622/1cb7a8ab-5446-40f6-9fa5-207f85da2bd4)

**Comment by moukoublen** [comment]
@orestisfl I think to enable queue diagnostic settings, you have to follow this path:

  1. Storage Account
  2. Monitoring -> Diagnostic settings (not classic)
  3. Queue Diagnostic status should say `Enable`
  4. If not, click on it and in next screen `+ add diagnostic settings`

<img width="1932" alt="Screenshot 2024-02-20 at 4 38 26 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/a9cdae2a-3a88-4346-b0e9-dc380f566863">
<img width="2292" alt="Screenshot 2024-02-20 at 4 39 14 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/8ef12b34-d6f7-4dae-a861-98610fa8a5c2">
<img width="1102" alt="Screenshot 2024-02-20 at 4 34 16 PM" src="https://github.com/elasti
<img width="1699" alt="Screenshot 2024-02-20 at 4 40 23 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/3491a8fa-f54e-45e7-9ba8-a8325526b0e5">
c/cloudbeat/assets/1380039/7f5405eb-46d4-4c73-ad2d-ebbecda3b65d">

**Comment by orestisfl** [comment]
@moukoublen The instructions from the benchmark refer to the "classic" diagnostic settings.

![image](https://github.com/elastic/cloudbeat/assets/5778622/6f2175c7-e324-4432-827e-e2b75a7d558c)

**Comment by oren-zohar** [comment]
Closing since our implementation is following the 2.1 CIS version
