### ISSUE TITLE
[CIS Azure] Database Services rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1417]
We would like to implement the following rules:
- [x] 4.1.1 Ensure that 'Auditing' is set to 'On'
- [x] 4.1.3 Ensure SQL server's Transparent Data Encryption (TDE) protector is encrypted with Customer-managed key
- [x] 4.1.5 Ensure that 'Data encryption' is set to 'On' on a SQL Database
- [x] 4.1.6 Ensure that 'Auditing' Retention is 'greater than 90 days'
- [x] 4.2.1 Ensure that Microsoft Defender for SQL is set to 'On' for critical SQL Servers
- [ ] 4.2.2 Ensure that Vulnerability Assessment (VA) is enabled on a SQL server by setting a Storage Account
- [ ] 4.2.3 Ensure that Vulnerability Assessment (VA) setting 'Periodic recurring scans' is set to 'on' for each SQL server
- [ ] 4.2.4 Ensure that Vulnerability Assessment (VA) setting 'Send scan reports to' is configured for a SQL server
- [ ] 4.2.5 Ensure that Vulnerability Assessment (VA) setting 'Also send email notifications to admins and subscription owners' is set for each SQL Server
- [x] 4.3.2 Ensure Server Parameter 'log_checkpoints' is set to 'ON' for PostgreSQL Database Server
- [x] 4.3.3 Ensure server parameter 'log_connections' is set to 'ON' for PostgreSQL Database Server
- [x] 4.3.4 Ensure server parameter 'log_disconnections' is set to 'ON' for PostgreSQL Database Server
- [x] 4.3.5 Ensure server parameter 'connection_throttling' is set to 'ON' for PostgreSQL Database Server
- [x] 4.3.6 Ensure Server Parameter 'log_retention_days' is greater than 3 days for PostgreSQL Database Server
- [x] 4.3.7 Ensure 'Allow access to Azure services' for PostgreSQL Database Server is disabled
- [x] 4.3.8 Ensure 'Infrastructure double encryption' for PostgreSQL Database Server is 'Enabled'
- [x] 4.4.2 Ensure 'TLS Version' is set to 'TLSV1.2' for MySQL flexible Database Server

**Comment by romulets** [comment]
**[Regarding rules 4.2.2, 4.2.3, 4.2.4, 4.2.5]**

In the current state of Azure, once you enable Microsoft Defender for Cloud, the default setup for Vulnerability Assessment Settings is called "Express Configuration". The current benchmark (v2.0.0 - 02-14-2023) is based on the "Classic Settings". [Here you can find more information about them](https://learn.microsoft.com/en-us/azure/defender-for-cloud/sql-azure-vulnerability-assessment-overview#whats-the-difference-between-the-express-and-classic-configuration). But 

On the default "Express Configuration" _no_ Storage Account is possible to be configured, therefore causing any of the aforementioned rules to fail by default and not being possible to follow the remediation section of the benchmark. The solution to this would be manually reverting back to a classic configuration, that [cannot be done via the UI](https://learn.microsoft.com/en-us/azure/defender-for-cloud/faq-defender-for-databases#can-i-revert-back-to-the-classic-configuration-). It's possible as described in the [troubleshooting section of this document](https://learn.microsoft.com/en-us/azure/defender-for-cloud/sql-azure-vulnerability-assessment-manage?tabs=express#revert-back-to-the-classic-configuration) via powershell. 

This isn't, though, explained in the benchmark, what confused me at first. I can also imagine it being confusing to our customers once they need to search, understand and switch to a non standard configuration that isn't explicitly mentioned in the benchmark rule remediation.

[There is a ticket on the benchmark about deleting the rules for version v2.1.0](https://workbench.cisecurity.org/benchmarks/12346/tickets/17504).

I asked Tinsae and Smitri if we should go forward and merge https://github.com/elastic/cloudbeat/pull/1824 or not.

**Comment by romulets** [comment]
**[Regarding rules 4.2.2, 4.2.3, 4.2.4, 4.2.5]**

The rules won't be implemented because of their inconsistency with Azure UI + [they will be deleted in the next benchmark](https://workbench.cisecurity.org/benchmarks/12346/tickets/17504).
