### ISSUE TITLE
[CIS Azure] Networking rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1419]
We would like to implement the following rules:
- [x] 6.1 Ensure that RDP access from the Internet is evaluated and restricted
- [x] 6.2 Ensure that SSH access from the Internet is evaluated and restricted
- [ ] 6.3 Ensure that UDP access from the Internet is evaluated and restricted
- [ ] 6.4 Ensure that HTTP(S) access from the Internet is evaluated and restricted

**Comment by moukoublen** [comment]
Verified:

<img width="1991" alt="Screenshot 2024-02-20 at 3 11 18 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/757efb49-0089-4847-963b-ea7c8ceffde5">
<img width="1992" alt="Screenshot 2024-02-20 at 3 11 03 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/805bb379-165d-4d3e-8c71-2c849e903c2f">
<img width="2076" alt="Screenshot 2024-02-20 at 3 09 20 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/a1c1dfed-336d-4291-808a-1f4f7afce5c7">
