### ISSUE TITLE
[CIS Azure] Key Vault rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1421]
We would like to implement the following rules:
- [x] 8.1 Ensure that the Expiration Date is set for all Keys in RBAC Key Vaults
- [x] 8.2 Ensure that the Expiration Date is set for all Keys in Non-RBAC Key Vaults
- [x] 8.3 Ensure that the Expiration Date is set for all Secrets in RBAC Key Vaults
- [x] 8.4 Ensure that the Expiration Date is set for all Secrets in Non-RBAC Key Vaults

**Comment by kubasobon** [comment]
### 8.13 QA Cycle - verified

#### `result.evaluation: failed` for Vaults containing Keys/Secrets without expiration dates

<img width="2549" alt="Screenshot 2024-02-20 at 15 00 11" src="https://github.com/elastic/cloudbeat/assets/4587658/1fd3c70f-0231-4997-ba39-eda15c4e38c5">


#### `result.evaluation: passed` for Vaults where Keys/Secrets have expiration dates set

<img width="2549" alt="Screenshot 2024-02-20 at 16 24 28" src="https://github.com/elastic/cloudbeat/assets/4587658/b78e2ba4-24c3-4bcc-bd9e-aa3a1441f049">
