### ISSUE TITLE
[CIS Azure] Activity Logs Alerts rules

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#1452]
- [ ] 5.2.1 Ensure that Activity Log Alert exists for Create Policy Assignment (Automated) 
- [ ] 5.2.2 Ensure that Activity Log Alert exists for Delete Policy Assignment (Automated)
- [ ] 5.2.3 Ensure that Activity Log Alert exists for Create or Update Network Security Group (Automated)
- [ ] 5.2.4 Ensure that Activity Log Alert exists for Delete Network Security Group (Automated)
- [ ] 5.2.5 Ensure that Activity Log Alert exists for Create or Update Security Solution (Automated)
- [ ] 5.2.6 Ensure that Activity Log Alert exists for Delete Security Solution (Automated)
- [ ] 5.2.7 Ensure that Activity Log Alert exists for Create or Update SQL Server Firewall Rule (Automated)
- [ ] 5.2.8 Ensure that Activity Log Alert exists for Delete SQL Server Firewall Rule (Automated)
- [ ] 5.2.9 Ensure that Activity Log Alert exists for Create or Update Public IP Address rule (Automated)
- [ ] 5.2.10 Ensure that Activity Log Alert exists for Delete Public IP Address rule (Automated)

**Comment by orestisfl** [comment]
@oren-zohar Can you delete this ticket? Duplicate of https://github.com/elastic/cloudbeat/issues/1256
