### ISSUE TITLE
[CIS Azure] Fix 7.1 Ensure an Azure Bastion Host Exists

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1474]
https://github.com/elastic/cloudbeat/issues/1258#issuecomment-1777127858

**Describe the bug**
The 7.1 rule should fail when no bastions exist

**To Reproduce**
Delete Bastion in Azure, check for failed finding

**Comment by orestisfl** [comment]
This should be fixed again for 8.12+ in the `main` branch, https://github.com/elastic/cloudbeat/pull/1475 is only applicable for 8.11.

**Comment by kfirpeled** [comment]
We miss instructions how to remediate and how make sure it fails in order to verify it

cc: @orestisfl , @oren-zohar

**Comment by orestisfl** [comment]
> are there any pre-requisites that should be done in advnace before we start to test these rules?

Not really, bastions can be freely deleted and re-created in the team's subscription.

If needed, I can elaborate further on what is expected and what is not but that would perhaps diminish the effect of QAing a rule since I will instruct how to QA this rule according to my own understanding, which might be different from the QAers' understanding.

**Comment by orestisfl** [comment]
Verified as broken by @maxcold, working on a fix to be re-tested in next QA batch

**Comment by romulets** [comment]
Tests:

| Scenario | Evaluation Result | Expected |
|---|---|----|
| Standard Bastions present | passed | ✅ |
| No Bastions present | failed | ✅ |
| Basic Bastion present | pass | ✅ |

<img width="1461" alt="image" src="https://github.com/elastic/cloudbeat/assets/5350001/1208b6af-e513-461e-9ec1-b5ec8d147836">


LGTM 👍
