### ISSUE TITLE
Every CSPM provider should run with 24 hour cycles

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1478]
**Motivation**
I've noticed that currently, the only CSPM that runs with 24-hour cycles is AWS.
Looking at the integration you are able to see the period configured:
https://github.com/elastic/integrations/blob/main/packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs#L1

Other CSPM providers do not configure anything in the `period` and because of that they are running the default `period` 4 hours:
```
func defaultConfig() (*Config, error) {
	ret := &Config{
		Period: 4 * time.Hour,
	}
```

We should make sure that all CSPM providers run once every 24 hours.

**Definition of done**
What needs to be completed at the end of this task
- [ ] All CSPM providers' cycle time is 24 hours

**Related tasks/epics**
Reference related issues and epics

**Comment by romulets** [comment]
Verified changes by checking finding logs. Both providers ran only once in the past 3 days.


GCP:
![Image](https://github.com/elastic/cloudbeat/assets/5350001/09f2e919-64e2-4d25-812a-d6dfd7ea7886)


Azure:


![Image](https://github.com/elastic/cloudbeat/assets/5350001/0e11bf92-ae97-4f34-9d4b-9ad7a21c86d2)

**Comment by kfirpeled** [comment]
In order verify this issue: check GCP and Azure CSPM produces findings every 24 hours instead of every 4 hours

**Comment by Omolola-Akinleye** [comment]
![Image](https://github.com/elastic/cloudbeat/assets/17135495/4a1ed7af-3efa-4d18-af8d-6b168decb0ec)




![Image](https://github.com/elastic/cloudbeat/assets/17135495/4f84f2a6-d891-4835-812e-8d109470c73c)



![Image](https://github.com/elastic/cloudbeat/assets/17135495/4e3c8cfd-0c12-407d-b5b3-de135c0a1206)



![Image](https://github.com/elastic/cloudbeat/assets/17135495/f060ac87-6c25-4032-b9df-caaa5d5da43b)
