### ISSUE TITLE
GCP findings shipped without account ID

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1489]
**Describe the bug**
On CSPM for GCP Organization, some findings are indexed without the `cloud.account.id` field.
The bug causes a weird UI where the CSPM dashboard shows another account with an empty name:

![image](https://github.com/elastic/cloudbeat/assets/34831306/2dcdf656-37b8-4495-bf8e-4afef17f8250)

The cloud section of such a finding:
```json
  "cloud": {
    "Organization": {
      "name": "cspelastic.com",
      "id": "693506308612"
    },
    "provider": "gcp",
    "account": {
      "name": "",
      "id": ""
    }
  }
```

**To Reproduce**
1. Create CSPM for GCP Organization integration and deploy it
2. Check the CSPM dashboard

**Expected behavior**
1. Cloudbeat should fill this field with the information it has

**Comment by moukoublen** [comment]
In the organization account type, some assets could be organization-wide and thus not under a specific project ID/name (for example, I noticed some org-wide log buckets). 

In that case, `asset.Ancestors` contains only a single entry with the organization, so no project ID and name can be resolved. 

https://github.com/elastic/cloudbeat/blob/ac580b7e3c50e1437bb1e262421547a4e1c23807/resources/providers/gcplib/inventory/provider.go#L498-L509

https://github.com/elastic/cloudbeat/blob/ac580b7e3c50e1437bb1e262421547a4e1c23807/resources/providers/gcplib/inventory/provider.go#L444-L460

Perhaps in case of organization-wide assets, we can add a static project ID/name indicating that it is a global one?

**Comment by tinnytintin10** [comment]
Thanks for capturing this @amirbenun, and for looking into it @moukoublen! As part of the dashboard UX enhancements we're making for 8.12 the dashboard bug will be resolved as we'll not show a row per project/account but per benchmark. We can continue leaving the cloud.account.id and name fields blank for now; we can think through how to address this as part of https://github.com/elastic/security-team/issues/7658

![Screenshot 2023-11-07 at 22 12 52](https://github.com/elastic/cloudbeat/assets/53792284/c09fd9c3-3893-4647-b01a-3e3e3623518f)

**Comment by moukoublen** [comment]
After @tinnytintin10 feedback we will close this ticket without any implementation on cloudbeat's side.

**Comment by kfirpeled** [comment]
Skipping this test - resolved by design changes
