### ISSUE TITLE
Improve rule's evidence collection

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#1509]
**Context**
Currently, every rule is split into three main parts, **_filter_** where we decide if the input resource is relevant for this rule, **_evaluate_** where we evaluate the resource against the rule logic and evidence collection.

**The Problem**
When collecting the evidence, we assume that the resource will contain the relevant evidence fields, but if it doesn't, the evidence will be undefined, and as a result, no finding will be sent. This is not a good outcome, and we should address it. 
Some options:

- Wrap the evidence and make sure it's not undefined, if so, set it to some default value e.g. "Evidence collection failed".
This will be easy to implement and maintain.
- Wrap or find an alternate way of extracting fields, with default values, such as in other programming languages. 

Thoughts? @ofiriro3 @uri-weisman @eyalkraft @jeniawhite

**Comment by ofiriro3** [comment]
I agree 💯 percent.

We have to protect the evaluation result where there is no evidence.

Its a rare case but it can definitely happen.

**Comment by orouz** [comment]
another aspect of evidence collection  is the value we provide to the user. (aside from failing silently when missing, which can be addressed separately, see elastic/csp-security-policies#274 ) i had short discussion with @oren-zohar about this and he suggested we make the `result.evidence` field a `json.path` which would be a link that would lead to the relevant resource data and highlight it. 

currently we sometimes send the actual relevant fields and sometimes we send the full resource, which is less helpful and also duplicated.

**Comment by kubasobon** [comment]
After talking to stakeholders, it is clear that we need to consider two things: rules not producing findings for `undefined` evidence, and the best user-friendly evidence format.

## 1. Safe evidence collection

Regardless of the decision on **2.**, we need to prevent a missing field or a typo from completing rule evaluation and posting a finding. The solution I went with is to wrap Rego's built-in `object.get(object, path, default)` function. It never results in `undefined`, thus satisfying the condition of never interrupting rule evaluation. See the PR:
<https://github.com/elastic/cloudbeat/pull/1827>

It is important to note that there is inconsistency in the use of the `evidence` field across the bundle. Most often (~85% rules), we attach an entire resource. For ~15%, we extract and filter the input data to present reason more accurately. This brings us to part two...

## 2. Evidence presentation and UX

@tinnytintin10 & @smriti0321, I would appreciate your input and opinions on this.

There are two open questions, in my humble opinion:

**Q1**:  What would be the most useful Evidence content from an end-user perspective?

**Q2**:  What would be the most useful message if the evidence collection failed?

Towards **Q1** - I think @oren-zohar's suggestion of using JSONPaths falls into
this category.

**Comment by tinnytintin10** [comment]
Thanks for the ping @kubasobon!

> Q1: What would be the most useful Evidence content from an end-user perspective?

Full resource metadata would be ideal. Eventually, the goal of the evidence section is to highlight the exact piece of metadata that led to the failed outcome (similar to how github highlights which lines have been added and or removed during a code review). 

> Q2: What would be the most useful message if the evidence collection failed?

Something along the lines of "Something went wrong while collecting the evidence for this finding. Please check again after the next evaluation." @benironside what do ya think? @einatjacoby how do you think we should render this?

**Comment by einatjacoby** [comment]
@tinnytintin10 if we go with a callout- should we add a title?
![edivence](https://github.com/elastic/cloudbeat/assets/92093725/9ff08586-9c69-4ce9-86db-0472baab50d2)

**Comment by kubasobon** [comment]
@oren-zohar, @romulets, @moukoublen, @orouz - Let's sync on what the consensus for Rego rule implementation and refactor is.
