### ISSUE TITLE
[BUG] Kibana / My Benchmarks / Rules - Save operation should be atomic

### ISSUE THREAD

**Issue by CohenIdo** [elastic/cloudbeat#155]
**Describe the bug**
When the user enables or disables a rule and clicks "save", two requests are triggered behind the sense:
1. Save the new status of the rules using the saved-object API 
2. Create a new rule configuration based on the activated rules and send it to the beat.
Since the two calls are independent, the FE calls the saved object API first and then the */update_rule_config* API next, this means the second call won't be affected by the failed first call.
As an example: if a request to update a rule configuration fails, the user is not aware since the first request, to the saved object API, succeeds. In this case, in the UI the user will see that some rules are disabled, but they will still run when the beat is activated.

**Preconditions**
1. Add the CIS Kubernetes Benchmark package to your agent policy. 
2. Navigate to `My Benchmarks`
3. Click on your integration
4. disable \ enable rule and click save.
5. go to network and find the next two requests:
- _bulk_update
- http://localhost:5601/jxp/api/fleet/epm/packages/cloud_security_posture?experimental=true

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. `http://localhost:5601/jxp/internal/cloud_security_posture/update_rules_config`
2. `http://localhost:5601/jxp/api/saved_objects/_bulk_update`

**Expected behavior**
user makes local changes
user clicks "save"
FE sends a request to /update_rules_config with the new rules state in the request body
BE tries to save the new rules state to the concrete rule saved object index
on a failed request, return an error to FE.
on a successful request, BE tries to call PackagePolicyServiceInterface["update"]
on a failed request, rollback rules state to previous one and return an error to FE
on a successful request, return 200 with no data

credit to: @orouz 
https://github.com/elastic/cloudbeat/issues/126#issuecomment-1127454024

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: 
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by orouz** [comment]
this task will make updating rules an atomic operation. 

maybe while we're at we might want to introduce a `RulesClient` and FE would get all of the data from `/csp/api/rules` 

i'm suggesting this because currently FE uses the saved object client to fetch data and our own api to update it. it's ok, but perhaps we'd like to consolidate all rules API calls. 

@kfirpeled thoughts?

**Comment by orouz** [comment]
https://github.com/elastic/kibana/pull/137325
