### ISSUE TITLE
Include latest release branch in automatic go updates

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1550]
**Motivation**
Updating the go version can avoid us having vulnerabilities in release versions because of older versions of go.

**Definition of done**
What needs to be completed at the end of this task
- [x] Updatecli automatically runs the pipeline and creates a PR for the latest release version
- [x] Only the Go update needs to be included
- [x] This can be done either with the job matrix or with the backport labels

**Comment by romulets** [comment]
Strategies to identify latest active branch:

* Grab the defaultBeatVersion ([here](https://github.com/elastic/cloudbeat/blob/main/version/version.go)), do some parsing, decrease the minor and assume that's the latest branch to update
* Grab the last created tag, do some parsing and assume that's the latest tag.
* Grab remote branch list, clean up by MAJOR.MINOR, sort and grab the last one
```bash
            git branch -r \
              | egrep -i 'origin/[0-9]+\.[0-9]+' \
              | awk -F/ '{print $2}' \
              | sort -Vr \
              | head -n 1 >> ACTIVE_BRANCH
```
* Use [APM Pipeline Library](https://github.com/elastic/apm-pipeline-library/blob/9c712c2558ef07309c4ddf3cf02d20a1cb2b1b3a/updatecli/updatecli.d/bump-aliases.yml#L43C1-L55C31). **Seems like the most solid**
* Check [DRA](https://artifacts-staging.elastic.co/dra-info/index.html) info

**Comment by romulets** [comment]
Found another solution that might be the best: use updatecli only and leave the branch selection out of github actions (got inspired by apm)

Docs on finding branch by semver with updatecli: https://www.updatecli.io/docs/plugins/resource/gitbranch/

**Comment by romulets** [comment]
https://github.com/elastic/cloudbeat/pull/1589 As proven by this PR, it works!
