### ISSUE TITLE
[CIS Azure] Generate new templates for rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1606]
We need to make sure to merge the CSP rule templates and update the integration with the new rules prior to FF

**Comment by kfirpeled** [comment]
Verify the new rules appears under the benchmark page (because they come from a different data source)

**Comment by maxcold** [comment]
verified

![Image](https://github.com/elastic/cloudbeat/assets/478762/83437009-9d58-4e82-a4e2-8c4f306ddc39)
