### ISSUE TITLE
[CIS Azure] `cloud.*` fields missing in events

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1609]
**Describe the bug**
I am opening this after the PR that fixes it in, https://github.com/elastic/cloudbeat/pull/1605. Some more context there.

**Preconditions**
8.12 snapshot

**To Reproduce**
- Deploy Azure CSPM
- See that events are missing `cloud.account.{id,name}` and `cloud.Organization` fields.

**Comment by kfirpeled** [comment]
Verify by checking if any findings of azure is missing the following fields: `cloud.account.{id,name}` and `cloud.Organization` fields.

**Comment by maxcold** [comment]
`cloud.account.{id,name}` verified

![Image](https://github.com/elastic/cloudbeat/assets/478762/2636f38e-d85a-455f-aa32-777d168e84cf)

`cloud.Organization` tbd

**Comment by maxcold** [comment]
`cloud.Organisation` fields verified

![Image](https://github.com/elastic/cloudbeat/assets/478762/aa71d2c3-62aa-46be-af28-4128303aa620)
