### ISSUE TITLE
[CIS Azure] ARM: Failure to deploy to different region

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1619]
**Describe the bug**

With the single-account ARM template, try to create a new deployment and switch to a different region than East US:

![image](https://github.com/elastic/cloudbeat/assets/5778622/b00141cc-4bfa-4195-965b-859394322067)
![image](https://github.com/elastic/cloudbeat/assets/5778622/6d5d0f9c-7273-4121-a7e3-a14bfc118476)

**Preconditions**
East US region has previous successful deployment

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Deploy ARM template to one region
2. Try to deploy ARM template to a different region

**Expected behavior**
Deployment succeeds in both regions

**Comment by orestisfl** [comment]
Re-opening to handle management group template as well

**Comment by kfirpeled** [comment]
@oren-zohar this would be ready to be fixed for NextBC only, correct?

**Comment by orestisfl** [comment]
@kfirpeled This should work already and is ready for QA as the ARM template does not depend on BC

**Comment by opauloh** [comment]
Verified

Kibana 8.12.0
Commit 93cff0aacd70bd0835cd244348f742ba3cafc4aa



![Image](https://github.com/elastic/cloudbeat/assets/19270322/de816fb5-43f3-43a4-8a3e-42767e31362f)



![Image](https://github.com/elastic/cloudbeat/assets/19270322/0003d17b-2877-44f1-ac41-23d936db46a4)
