### ISSUE TITLE
Implement a more complex lease leader election for cloudbeat pods that are deployed on local multi-node clusters

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#162]
**Describe the enhancement**
As part of this PR: https://github.com/elastic/cloudbeat/pull/156.
There was a mock logic added in order to make sure that the lease is getting obtained for locally deployed cloudbeat agents without elastic-agent.
Since there is no actual leader election logic and we just create the lease upon deployment (without renewals).
This means that if we deploy a local multi-node cluster with multiple cloudbeat pods, each pod will assume that it is a leader and will run the k8s fetcher.

**Preconditions**
Deployed multi-node local cluster with cloudbeat pods running on every node.

**To Reproduce**
1. Deploy kind cluster with multiple nodes.
2. Create cloudbeat pod on every node.

**Expected behavior**
When running locally with multi-node clusters only the leader cloudbeat pod should run the k8s fetcher.

**Comment by eyalkraft** [comment]
Will be done as part of https://github.com/elastic/security-team/issues/4125
