### ISSUE TITLE
Disable/Move k8s flaky CI functional tests from pre-merge

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1623]
**Motivation**
The k8s CI tests are flaky and are running as pre-merge and required for every PR. Feature is in support stage, we do not touch that codebase and do any changes in our PRs.

This flakiness creates a lot of inconvenience when we want to merge PRs.

I suggest to move k8s CI tests to post-merge while we investigate and fix the flakiness.
We can also utilize @gurevichdmitry Slack notifications when the tests are failing at post-merge (can be also done after certain amount of re-triggers).

**Definition of done**
What needs to be completed at the end of this task
- [x] Allow PR merged without k8s CI
- [x] Move k8s CI to post-merge
- [x] Re-trigger k8s CI `N` times on flakiness
- [x] Send Slack notification after `N` failures

**Out of scope**
- [ ] Investigate and resolve flakiness

**Comment by gurevichdmitry** [comment]
Added rerun flaky workflows PR

**Comment by gurevichdmitry** [comment]
Built slack payload and added integration with k8s-ci workflow.
