### ISSUE TITLE
[CIS Azure] Rule 1.23 doesn't have cloud.* fields

### ISSUE THREAD

**Issue by orestisfl** [elastic/cloudbeat#1631]
**Describe the bug**
![image](https://github.com/elastic/cloudbeat/assets/5778622/e266a94c-5dd7-462c-9d6b-5573582a66ec)

Crashes the dashboard

**Related Issues**
https://github.com/elastic/cloudbeat/issues/1489

**Comment by opauloh** [comment]
Couldn't verify as this rule is missing, I see 38 out of the 40 rules

![Image](https://github.com/elastic/cloudbeat/assets/19270322/ead057b4-08f5-4b6f-b146-16fdca07b13c)


![Image](https://github.com/elastic/cloudbeat/assets/19270322/26429318-1206-42ea-9006-c4ac90bb26d5)


cc @oren-zohar, would this be a bug?

**Comment by orestisfl** [comment]
I am not sure if this rule can exist in single-subscription deployment, cc @jeniawhite

**Comment by orestisfl** [comment]
@maxcold Thank you for the screenshot

This is actually working as expected, there are no available fields so we leave them empty. The important part is that it did not crash the dashboard (which happens with missing fields). I am re-closing this but leaving the `verified` tag as your call.

**Comment by maxcold** [comment]
@orestisfl thanks for looking into it! so the change here is that we insert `cloud.account.id` even if it is missing? If so I think we can mark as verified. The CSP dashboard in 8.12 was changed to group by benchmark and not by account, so the issue won't reproduce anyway, if I'm not missing smth
