### ISSUE TITLE
Single python automation project

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#1638]
### Motivation
In cloudbeat repo there are two different python projects:
1. `deploy/test-environments/fleet_api/` - Used preparing an environment, installing integrations, interacting fleet
2. `tests/` - Pytest project used for verifying the findings with the elasticsearch SDK

There are already cases where the two projects have to share code and actually there is no visible reason not to merge them into a single project.

### Definition of done
- [x] Unify the two projects together
- [x] In case there are code duplications - delete it
- [ ] Modify the workflows accordingly to make sure "Create Environment" functions

### Out of scope
- Functionality should remain the same

### Related tasks/epics
-

**Comment by amirbenun** [comment]
An example for the workaround we had to do can be found here
https://github.com/elastic/cloudbeat/blob/ba2614aff8c0525b1b2f6e725d51c153a0c3c9b1/tests/commonlib/agents_map.py#L10

**Comment by gurevichdmitry** [comment]
The `fleet_api` folder is now part of the tests project. It's divided into two directories: `fleet_api` (common library) and `integrations_setup` (scripts and management).
