### ISSUE TITLE
Pre-allocate slices when ever is possible

### ISSUE THREAD

**Issue by moukoublen** [elastic/cloudbeat#1651]
**Is your feature request related to a problem? Please describe.**
Currently, in Cloudbeat code, the `nil` initialization is used every time a slice is created. 

e.g. 

```golang
var theSlice []string
```

The above code initializes a variable `theSlice` having `nil` value. Each append (e.g. `theSlice = append(theSlice, ?)`) will return the same or a new slice if needed. 

The first time append is used on a `nil` initialized slice, a new slice will be allocated with capacity one (`1`) then append the value to it and return it. 

Every slice append that reaches the slice capacity reallocates (creates a new internal buffer, copies all the previous values to the new one, and drops the previous one) and doubles the previous capacity. 

This results in cloudbeat having multiple reallocations for the same slice (especially for the first appends).  An example [here](https://go.dev/play/p/Cyf3VK4wBtb).

So, this performance implication might be considerable because Cloudbeat operates (transforming, appending, reading) on slices heavily. 

**Describe the solution you'd like**
An easy way to avoid that is initializing with capacity (E.g. `theSlice := make([]string, 0, capacity)`).

There are 3 cases:

  - A) The capacity is already known at the time of initialization (because a slice is a transformation of another slice within a known length). For example: `theSlice := make([]string, 0, len(anotherSlice))`
  - B) The capacity is not directly known at the time of initialization but can be found with simple operations. For example, when a flattening of multiple slices is happening, the final capacity is the sum of individual lengths. For example: `theSlice := make([]string, 0, len(anotherSliceOne)+len(anotherSliceTwo))`
  - C) The capacity cannot be known at the time of initialization. Even in this case, an "estimated" capacity can be given in order to avoid the first reallocations that are happening on first appends. For example: `theSlice := make([]string, 0, 10)`

My suggestion on that is `A` to be mandatory, `B` to be partially mandatory only in cases where it is super simple to calculate, and `C` to be optional.

Specifically, we can use the golangci-lint `prealloc` linter (doc [here](https://golangci-lint.run/usage/linters/#prealloc)) with this configuration:

```yaml
linters-settings:
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
```

This will cover `A` (and possible `B`)

And also exclude it from test files using this golangci-lint configuration:

```yaml
issues:
  exclude-rules:
    - path: _test\.go
      linters: [prealloc]
```

**Describe alternatives you've considered**

**Additional context**
Elastic https://github.com/elastic/beats has the `prealloc` linter [enabled](https://github.com/elastic/beats/blob/157b31a79e3ad52578f30399049cac030d688934/.golangci.yml#L68) with this [config](https://github.com/elastic/beats/blob/157b31a79e3ad52578f30399049cac030d688934/.golangci.yml#L157-L169).

**Comment by orestisfl** [comment]
I am going to repeat what the prealloc linter doc comment says:
```
  prealloc:
    # IMPORTANT: we don't recommend using this linter before doing performance profiling.
    # For most programs usage of prealloc will be a premature optimization.
```

So, I think we should start by identifying bottlenecks (intuitively, cloudbeat is a network-bound application). Additionally, we need to measure the impact of pre-allocation in our memory usage.

To actually accurately measure the impact of slice pre-allocation and to commit to a strategy, we need to profile with real-life workloads. Keep in mind that pre-allocation is not always better because there are cases where arrays end up being empty so pre-allocating them would mean we waste an allocation for no reason. Thus, we need to evaluate statistically the usage on each case.

**Comment by moukoublen** [comment]
> So, I think we should start by identifying bottlenecks (intuitively, cloudbeat is a network-bound application). Additionally, we need to measure the impact of pre-allocation in our memory usage.

> Keep in mind that pre-allocation is not always better because there are cases where arrays end up being empty so pre-allocating them would mean we waste an allocation for no reason.

Especially for `A` (and some simple cases of `B`), when you know that from a slice `foo` with a given known length, you want to create a transformation slice `hoo`, then there is not really something to measure. Initializing with nil will always consume more CPU and memory because of the multiple reallocations that will have to go over. 

For `C` (and thus optional) is something that only in special case we can use an "estimated" capacity.

**Comment by orestisfl** [comment]
> Especially for A (and some simple cases of B), when you know that from a slice foo with a given known length, you want to create a transformation slice hoo, then there is not really something to measure. Initializing with nil will always consume more CPU and memory because of the multiple reallocations that will have to go over.

Yes, I don't mind enabling the linter I am undecided on if it makes the code more or less readable but it's not a big issue
