### ISSUE TITLE
CSPM GCP CIS 1.5 false positives

### ISSUE THREAD

**Issue by zygis** [elastic/cloudbeat#1665]
**Describe the bug**
CSPM on GCP generates a lot of false positives with the CIS 1.5 rule. 
https://github.com/elastic/cloudbeat/blob/main/security-policies/bundle/compliance/policy/gcp/iam/ensure_user_not_editor_or_owner.rego#L14
The comment suggests that the check assumes that ALL managed roles give admin/owner rights. Which is not true. 
The rule should not match `roles/iam.workloadIdentityUser`, but service accounts with this role are reported as failed findings for some reason. 

**Preconditions**
GCP cloud
Elastic Cloud v8.11.3
Security Posture Management integration v1.6.5

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Create a GCP service account and add `workloadIdentityUser` role.
2. Come back after several hours and check the findings

**Expected behavior**
At the very least, I expect that Elastic won't create false positive findings on commonly used roles like `role/iam.workloadIdentityUser`.

**Comment by orouz** [comment]
thank you for the bug report @zygis. i've opened a PR with a fix. it will be available in the next version.
