### ISSUE TITLE
Automate cloudbeat version bump

### ISSUE THREAD

**Issue by orouz** [elastic/cloudbeat#1675]
**Motivation**
every new release we need to run a sequence of operations in order to bump cloudbeat and the integration:
1. create a release branch in cloudbeat from `main` 
2. create a PR to cloudbeat 
   - add mergify config for previous release
   - update arm template to next release (`defaultValue` and `install-agent.sh` versions)
   - update `defaultBeatVersion` to next release
   - update cloudbeat version to next release in hermit file (separate PR)
3. create a PR to the integrations repo
   - update manifest version to a production (without `-preview)` 
   - update changelog with a new entry
   - update changelog version map
   - update manifest template vars (gcp, azure, aws)
   
originally, we only wanted to automat the integrations PR which updates the manifest template vars (#1276, #1185):
- `cloud_shell_url` / `arm_template_url` both point a branch, so we can update these after creating a release branch
- `cloud_formation_template` points to a file on an S3 bucket, which is uploaded on merges to main/release whenever there are changes to a related file. 

the main question was when this workflow should run. ideally, it'd be on every release branch creation, but we can't really [filter](https://github.com/orgs/community/discussions/26286) on those. so the current approach is to bundle the entire bumping operations into a dispatch workflow we trigger manually which does the steps described above. 

**Definition of done**
- github workflow created to handle modifications and PRs to cloudbeat/integrations
- service account user obtained from IT 

**Out of scope**
-

**Related tasks/epics**
- https://github.com/elastic/it-eng/issues/2099

**Comment by orouz** [comment]
the [current](https://github.com/elastic/cloudbeat/pull/1682/files#diff-69dbd9a1529c6dcabcd45dea53b2056cb801e4d214fb9d03cd60748b2b082392) workflow handles the steps described above in the issue description. 

one of those steps is to update the integration with the new URL for the cloud formation templates which are stored in S3. we upload the templates to S3 using [this workflow](https://github.com/elastic/cloudbeat/blob/main/.github/workflows/publish-cloudformation.yml) which doesn't run if there are no changes to relevant files. this means that if we didn't change anything between versions, there won't be a template in S3 and that means we'd either need to point the integration cloud formation variable to a previous version (which would work, just odd) or to a non-existing template, which would obviously not work. to address this, we could:

1. [modify](https://github.com/orouz/cloudbeat/blob/main/.github/workflows/test_foo.yml) the current cloud-formation uploading workflow to run on branch creation as well. this modified workflow includes an additional step to exit the workflow if it shouldn't run, as we can't do this:
 ```
 on:
  create:
   branches:
      - main
      - "[0-9]+.[0-9]+"
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+"
   ```
because branch creation event [doesn't support filtering](https://github.com/orgs/community/discussions/26286) like `push` does. this means that for every new branch created, even if it's not a release branch, this workflow would execute and [bail early](https://github.com/orouz/cloudbeat/actions/runs/7330924138) if it's not a release branch, which is a bit spammy. 


2. another solution is to keep the workflow as is, but also call the `publish_cft.sh` script from the newly added version bump workflow. this would make it so that CF templates will be uploaded when:
   - CF related files are changed
   - every manual trigger of the version bump workflow

3. use git branches instead of S3 buckets, which is also consistent with other usages of cloud vendor deployment templates 


i think option 3 is probably the most fitting. thoughts? @orestisfl @oren-zohar

**Comment by oren-zohar** [comment]
> 3. use git branches instead of S3 buckets, which is also consistent with other usages of cloud vendor deployment templates

Seems like the best solution to me as long as it will not be a breaking change

**Comment by orestisfl** [comment]
> use git branches instead of S3 buckets, which is also consistent with other usages of cloud vendor deployment templates

I remember the reason we don't use direct git links with CloudFormation is because it doesn't work. This might be wrong because I've never tested that so it's worth checking first.

**Comment by orouz** [comment]
alright, [turns out](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-console-create-stack-template.html) s3 indeed prevents serving templates not from S3. so i'm leaning towards option 2. we already have automatic uploads whenever a template changed, so we're just missing uploads for when a template didn't change between versions. assuming we'll adopt the version bumping workflow, triggering a new release will also upload the CF templates. 

so [this script](https://github.com/elastic/cloudbeat/pull/1682/files#diff-ae12b434849365805a754c8ae3dfaa4a24eda4511ac19849869a7db94c3281cc) will also include the following:

```bash
upload_cloud_formation_templates() {
  aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  aws configure set region us-east-2
  scripts/publish_cft.sh
} 
```
which is essentially what `.github/workflows/publish-cloudformation.yml` does.
