### ISSUE TITLE
[CIS Azure] Implement Azure API calls for invalid ARG data rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1729]
**Describe the bug**
We've found out that some of the data that is being pulled from ARG is not updated correctly by the ARG and it returns an incorrect state of the configured properties (in our case always returns `null`).
Comment for reference:
- https://github.com/elastic/cloudbeat/issues/1420#issuecomment-1864385782

Due to that we've removed some rules until we implement them with API calls instead.
PR with removal of rules:
- https://github.com/elastic/cloudbeat/pull/1715

**Comment by moukoublen** [comment]
Rules `9.x` are implemented in [this PR](https://github.com/elastic/cloudbeat/pull/1865) using enrichers, so it seems there is no need to replace the root resource (websites) source from ARG to SDK.

**Comment by romulets** [comment]
QA: Skipping tests because it was already tested with https://github.com/elastic/cloudbeat/pull/1865
