### ISSUE TITLE
Resolve module loading issue in tests docker build (k8s workflow)

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#1739]
**Motivation**

All k8s tests are failing in the post-merge k8s workflow [run](https://github.com/elastic/cloudbeat/actions/runs/7314620764) with the following issue:
```
conftest.py:11: in <module>
    from commonlib.agents_map import AgentExpectedMapping, AgentComponentMapping
commonlib/agents_map.py:11: in <module>
    from api.agent_policy_api import get_agents  # pylint: disable=wrong-import-position # noqa: E402
E   ModuleNotFoundError: No module named 'api'
```

The current implementation in `commonlib/agents_map.py` relies on appending the relative path to the fleet API modules using `sys.path.append`. However, when building the tests Docker image, the `deploy` folder is not copied, resulting in a `ModuleNotFoundError` for the `api` module.

To solve this issue we need to update the [Dockerfile](https://github.com/elastic/cloudbeat/blob/main/tests/Dockerfile) for the tests to include the necessary files from the `deploy` folder.

**Definition of done**
- [ ] The Dockerfile for tests includes the necessary files from the deploy folder.
- [ ] K8s tests workflow is working

**Out of scope**

**Related tasks/epics**

**Comment by oren-zohar** [comment]
Will be solved by https://github.com/elastic/cloudbeat/issues/1638 so assigning @gurevichdmitry
