### ISSUE TITLE
[CIS GCP] Error 403: Permission 'resourcemanager.organizations.get' denied on resource

### ISSUE THREAD

**Issue by romulets** [elastic/cloudbeat#1748]
**Motivation**
The service account used by cloudbeat doesn't have permissions to browse on organization level, only on project level. [Testable here](https://console.cloud.google.com/iam-admin/troubleshooter;permissions=resourcemanager.organizations.get;principal=qa-cycle-812-oleg-sa@elastic-security-test.iam.gserviceaccount.com;resources=%2F%2Fcloudresourcemanager.googleapis.com%2Forganizations%2F992493199029)

The error:
```
error fetching GCP Org: googleapi: Error 403: Permission 'resourcemanager.organizations.get' denied on resource '//cloudresourcemanager.googleapis.com/organizations/992493199029' (or it may not exist).
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "cloudresourcemanager.googleapis.com",
    "metadata": {
      "permission": "resourcemanager.organizations.get",
      "resource": "organizations/992493199029"
    },
    "reason": "IAM_PERMISSION_DENIED"
  }
]
, forbidden
```

[example](https://qa-cycle-812-oleg-cfi-8-12-0.kb.us-west2.gcp.elastic-cloud.com:9243/app/discover#/doc/logs-*/.ds-logs-elastic_agent.cloudbeat-default-2023.12.24-000001?id=vhWqnIwByeskzjUxXBPQ) log line

**Definition of done**
- [ ] Understand the impact of the error, is this organization display name shown anywhere?
- [ ] If needed update SA creation to grant permissions and add required permission to the docs

**Related tasks/epics**
- Found on https://github.com/elastic/security-team/issues/8219#issuecomment-1870039617
- Investigated on https://github.com/elastic/security-team/issues/7932#issuecomment-1870310592

**Comment by orouz** [comment]
seems like a dupe of https://github.com/elastic/cloudbeat/issues/2369 which was closed in https://github.com/elastic/cloudbeat/pull/2400

the root issue is that for a project-level CSPM for GCP, we were trying to get data for an organization, which isn't permitted. 

i'm closing this as it was [verified](https://github.com/elastic/cloudbeat/issues/2369#issuecomment-2441159304) in  18.6 BC1 and this current issue is older. 

if it does come back, we'll look into it further.
