### ISSUE TITLE
[CIS AWS] Using trail.Name when should be trail.TrailARN

### ISSUE THREAD

**Issue by romulets** [elastic/cloudbeat#1750]
**Motivation**

Regarding the following errors:

> [example](https://qa-cycle-812-oleg-cfi-8-12-0.kb.us-west2.gcp.elastic-cloud.com:9243/app/discover#/doc/logs-*/.ds-logs-elastic_agent.cloudbeat-default-2023.12.24-000001?id=UBv8powByeskzjUx-v3U)
> 
> ```
> failed to get trail status arn:aws:cloudtrail:us-west-2:773216979769:trail/elastic-eng-org-cloudtrail operation error CloudTrail: GetTrailStatus, https response error StatusCode: 400, RequestID: 3febd1a2-5182-4c31-8174-5b3a237a9574, TrailNotFoundException: Unknown trail: arn:aws:cloudtrail:us-west-2:704479110758:trail/elastic-eng-org-cloudtrail for the user: 704479110758
> ```

> [example](https://qa-cycle-812-oleg-cfi-8-12-0.kb.us-west2.gcp.elastic-cloud.com:9243/app/discover#/doc/logs-*/.ds-logs-elastic_agent.cloudbeat-default-2023.12.24-000001?id=VRv8powByeskzjUx-v3U)
> 
> ```
> failed to get trail event selector arn:aws:cloudtrail:us-west-2:773216979769:trail/elastic-eng-org-cloudtrail operation error CloudTrail: GetEventSelectors, https response error StatusCode: 400, RequestID: 914eea74-8199-4782-8c86-a509e7c66d0c, TrailNotFoundException: Unknown trail: arn:aws:cloudtrail:us-west-2:704479110758:trail/elastic-eng-org-cloudtrail for the user: 704479110758
> ```

We are fetching trails with name when it should be ARN.

Example of failed call:

```bash
aws cloudtrail describe-trails --no-cli-pager --region us-east-1 | jq ".trailList.[].Name" | xargs -L1 aws cloudtrail --no-cli-pager get-trail-status --name
```

Example of call working with ARN
```bash
aws cloudtrail describe-trails --no-cli-pager --region us-east-1 | jq ".trailList.[].TrailARN" | | xargs -L1 aws cloudtrail --no-cli-pager get-trail-status --name
```

The change is simple, [on this line](https://github.com/elastic/cloudbeat/blob/aca76603b448ee73acaa2d352378a11603916940/resources/providers/awslib/cloudtrail/provider.go#L78) and [this line](https://github.com/elastic/cloudbeat/blob/aca76603b448ee73acaa2d352378a11603916940/resources/providers/awslib/cloudtrail/provider.go#L87), instead of using `trail.Name` use `trail.TrailARN` 

[Backed up by aws docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudtrail/get-trail-status.html#options)

**Definition of done**
- [ ] use `trail.TrailARN` instead of `trail.Name`
https://github.com/elastic/cloudbeat/blob/aca76603b448ee73acaa2d352378a11603916940/resources/providers/awslib/cloudtrail/provider.go#L78 https://github.com/elastic/cloudbeat/blob/aca76603b448ee73acaa2d352378a11603916940/resources/providers/awslib/cloudtrail/provider.go#L87

**Related tasks/epics**
- Found on https://github.com/elastic/security-team/issues/8219#issuecomment-1870039617
- Investigated on https://github.com/elastic/security-team/issues/7932#issuecomment-1871007917

**Comment by moukoublen** [comment]
Verified:
<img width="2218" alt="Screenshot 2024-02-21 at 6 29 09 PM" src="https://github.com/elastic/cloudbeat/assets/1380039/652b518f-5547-40d7-a7cd-d987dbe09b53">
