### ISSUE TITLE
[CIS GCP] error fetching GCP Project: googleapi: Error 400: field [parent] has issue [invalid parent name]

### ISSUE THREAD

**Issue by romulets** [elastic/cloudbeat#1752]
**Motivation**
About 

[example](https://qa-cycle-812-oleg-cfi-8-12-0.kb.us-west2.gcp.elastic-cloud.com:9243/app/discover#/doc/logs-*/.ds-logs-elastic_agent.cloudbeat-default-2023.12.24-000001?id=sBtJpowByeskzjUxbJgD)

```
error fetching GCP Project: googleapi: Error 400: field [parent] has issue [invalid parent name]
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "invalid parent name",
        "field": "parent"
      }
    ]
  }
]
, badRequest
```

More context to the log was added on https://github.com/elastic/cloudbeat/pull/1747

It's still needed to understand why the parent name is wrong and fix it

**Definition of done**
- [ ] Fix the fetch parent error

**Related tasks/epics**

- Found on https://github.com/elastic/security-team/issues/8219#issuecomment-1870039617
- Investigated on https://github.com/elastic/security-team/issues/7932#issuecomment-1871097180

**Comment by orouz** [comment]
some more context - 

this happens on when calling 

https://github.com/elastic/cloudbeat/blob/d9e123c52fb3e135dc289c85010946120eb83ca0/resources/providers/gcplib/inventory/provider.go#L528

and `keys.parentProject` is computed at 

https://github.com/elastic/cloudbeat/blob/d9e123c52fb3e135dc289c85010946120eb83ca0/resources/providers/gcplib/inventory/provider.go#L506-L507

`projectId` is assigned using the same `keys` object and from the example link we know that it is populated (`test-project-1-396010`)

https://github.com/elastic/cloudbeat/blob/d9e123c52fb3e135dc289c85010946120eb83ca0/resources/providers/gcplib/inventory/provider.go#L533

so i _think_ we can rule the possibility of issuing a request with an invalid parent name such as `projects/""` 

but the error clearly indicates an invalid parent name, so further investigation is still required. hopefully #1747 will provide the required context.

**Comment by romulets** [comment]
Deployed a 8.14.0-SNAPSHOT and can't spot the error anymore ([logs](https://rmf-8-14-gcp-test-5qs-8-14-0-snapshot.kb.us-west2.gcp.elastic-cloud.com:9243/app/logs/stream?logPosition=(position:!n)&logFilter=(filters:!(),query:(language:kuery,query:%27(elastic_agent.id:17629784-0822-4d6a-917a-ea5022ea10f1%20and%20(data_stream.dataset:elastic_agent.cloudbeat)%20and%20(log.level:error%20or%20log.level:debug%20or%20log.level:info%20or%20log.level:warning))%20and%20(message%20:%20%22error%20fetching%20GCP%20Project%22)%27),refreshInterval:(pause:!t,value:5000),timeRange:(from:now-1d,to:now))&logView=(logViewId:default,type:log-view-reference)&flyoutOptions=(flyoutId:!n,flyoutVisibility:hidden,surroundingLogsId:!n)))

**Comment by kubasobon** [comment]
@romulets Please confirm there were no changes/fixes commited for this one.

I'll check the long-living QA environment logs for occurrences of this issue.

**Comment by romulets** [comment]
@kubasobon confirmed, no fixes were commited.

**Comment by kubasobon** [comment]
### 2024.05.14 manual check

These are the only `ERROR` and `WARNING` logs I could find for GCP:
<img width="2282" alt="Screenshot 2024-05-14 at 14 17 25" src="https://github.com/elastic/cloudbeat/assets/4587658/f80ddfa0-3537-44ba-98c7-6e6efc111eee">

The issue has not come up so far. I'll check once more on Friday.

**Comment by kubasobon** [comment]
### 2024.05.16 manual check

No change. Marking this as `Verified`.
