### ISSUE TITLE
[CIS AWS] fail to parse root account password last used, error: parsing time "no_information"

### ISSUE THREAD

**Issue by romulets** [elastic/cloudbeat#1754]
**Motivation**
About

[example](https://qa-cycle-812-oleg-cfi-8-12-0.kb.us-west2.gcp.elastic-cloud.com:9243/app/discover#/doc/logs-*/.ds-logs-elastic_agent.cloudbeat-default-2023.12.24-000001?id=MRsrpowByeskzjUxIX_u)

```
fail to parse root account password last used, error: parsing time "no_information" as "2006-01-02T15:04:05Z07:00": cannot parse "no_information" as "2006"
```

Validated by 

```
aws iam get-credential-report --no-cli-pager | jq .Content -r | base64 --decode | csvcut -c user,password_last_used
```

I can see multiple `no_informations`, and the [docs also states](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html) the `no_information` as a valid value.

[We need to validate the value before trying to convert](https://github.com/elastic/cloudbeat/blob/b9e127e849f6faae2eedc3e6b0eb619b8b290807/resources/providers/awslib/iam/root_account.go#L42) and allowing lastUsed to be `nil`

**Definition of done**
- [x] validate if the `PasswordLastUsed` has value `no_information`. If it has, don't convert and keep pwdLastUsed nil.

**Out of scope**
What should not be included in this task

**Related tasks/epics**
- Found on https://github.com/elastic/security-team/issues/8219#issuecomment-1870039617
- Investigated on https://github.com/elastic/security-team/issues/7932#issuecomment-1871117227

**Comment by kubasobon** [comment]
Fixed ([code](https://github.com/elastic/cloudbeat/blob/d2d6891409b466a29560188fabc787a4185fc871/internal/resources/providers/awslib/iam/root_account.go#L42-L51)) as part of https://github.com/elastic/cloudbeat/pull/2050
