### ISSUE TITLE
[CIS Azure] Identity and Access Management rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1756]
We would like to implement the following rules:
- [ ] 1.3 Ensure that 'Users can create Azure AD Tenants' is set to 'No'

**Comment by orouz** [comment]
seems like this can't be automated?

from the CIS benchmark: 

> Please note that at this point of time, there is no Azure CLI or other API commands
available to programmatically conduct security assessment for this recommendation.

so far i haven't found how to get data for `User settings -> Users can create Azure AD Tenants` using ARG or Azrue Go SDK

**Comment by oren-zohar** [comment]
@jeniawhite wdyt?
