### ISSUE TITLE
[CIS Azure] 9.4 Rule wrongful evaluation

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1828]
**Describe the bug**
Configured according the benchmark to fail:
![Screenshot 2024-01-18 at 15 25 03](https://github.com/elastic/cloudbeat/assets/12246907/f596abb0-abe5-467f-9727-c5d11ba9f3c2)

Listing in ARG:
![Screenshot 2024-01-18 at 15 25 52](https://github.com/elastic/cloudbeat/assets/12246907/00663038-7d73-46a8-92cd-61a749bc905e)

This creates a wrong evaluation.

We can look at different value like the benchmark suggests:
![Screenshot 2024-01-18 at 15 30 54](https://github.com/elastic/cloudbeat/assets/12246907/e1ce665c-7a2a-4017-95c0-0601b4e4dd75)

**Preconditions**
Environment state and/or platform-specific configurations.

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1.

**Expected behavior**

**Comment by kubasobon** [comment]
I have performed a little test and it looks like we should be checking the `clientCertEnabled` property, as suggested in the benchmark PDF.


### Options presented by Azure UI
![Options presented by Azure UI](https://github.com/elastic/cloudbeat/assets/4587658/bb60b4dd-4b1c-47f9-960a-2c9d318f5ab8)

### Effects of setting the option via UI or CLI
| Option | Effect when set |
|--------|-----------------|
| `Require` | `clientCertEnabled = true`, `clientCertMode = "Required"` |
| `Allow` |  `clientCertEnabled = true`, `clientCertMode = "Optional"` |
| `Optional` |   `clientCertEnabled = true`, `clientCertMode = "OptionalInteractiveUser"` |
| `Ignore` | `clientCertEnabled = false` |

❗ Please note setting `Ignore` option does not affect `clientCertMode` property, which sticks to last selected mode other than `Ignore`. It simply sets `clientCertEnabled` to `false`.

**Comment by kubasobon** [comment]
Proof of said behavior when using Azure CLI:

![Proof of said behavior when using Azure CLI](https://github.com/elastic/cloudbeat/assets/4587658/837fe3c0-7202-4f1d-b534-e1c84e432355)

**Comment by kubasobon** [comment]
To ensure the mode is set to `Required` both have to be true:
- `clientCertEnabled: true`
- `clientCertMode: "Required"`
