### ISSUE TITLE
[CIS GCP] End of life for the Theia cloud shell

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1971]
**Describe the bug**
During the deployment of GCP agent, I've encountered a message of end of life in the cloud shell.
<img width="893" alt="Screenshot 2024-02-20 at 15 46 04" src="https://github.com/elastic/cloudbeat/assets/12246907/31db36c8-f5ae-4458-9a11-4e53e8872fe3">

Clicking on trying new shell resulted in the session being initialized and required me to pull code again (steps that we do not have documented).

We should investigate and understand the behavior after end of life and how this will affect our customers during deployment.

**Expected behavior**
Customers should be able to deploy GCP integration in a frictionless manner.

**Comment by uri-weisman** [comment]
UPDATE 02/04/24
The deprecation warning still appears for users using the old editor.
However, the context persists for users who opt for the new editor, so there shouldn’t be any issue.
Closing as a non-issue.
