### ISSUE TITLE
Account for rate limiting in AWS fetchers

### ISSUE THREAD

**Issue by orouz** [elastic/cloudbeat#2074]
**Motivation**
we need to account for rate limiting in our AWS fetchers to avoid losing resources we want to evaluate.

**Definition of done**
- figure out the quotas for each AWS fetcher 
- when applicable, AWS fetchers method usage does not exceed the default quota 
- add a retry (with backoff) mechanism for failed requests

**Out of scope** 
- synced cloudbeat instances consuming the same quota

**Comment by orouz** [comment]
turns out AWS Go SDK v2 comes with a built-in retry mechanism. verified by modifying the aws clients config to include logging:
```
awsConfig.Logger = logging.NewStandardLogger(os.Stdout)
awsConfig.ClientLogMode = aws.LogRetries | aws.LogRequestWithBody | aws.LogResponseWithBody 
```

the important log we get to see is:
```
Amz-Sdk-Request: attempt=1; max=3
```

which corresponds to the default settings of the [Standard](https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html) retry of 3 attempts. 

regarding quotas for AWS APIs, there doesn't seem to be any publicly defined general limits nor does the client tries to take that into account, and looks like retrying-with-backoff is the approach taken. 


in terms of modifications to cloudbeat, i think adding `429` HTTP status code to [Retryable Errors](https://github.com/aws/aws-sdk-go-v2/blob/7ed7b4fc6595a7e554796424f3470b37287dde5c/aws/retry/standard.go#L44-L49) would be sufficient to ensure we retry when APIs are rate limited (this is a safe-measure addition, as a similar retry condition is already [present](https://github.com/aws/aws-sdk-go-v2/blob/7ed7b4fc6595a7e554796424f3470b37287dde5c/aws/retry/standard.go#L65))

adding the additional retry condition, should also be done with consolidation of AWS config initialization as we're currently doing it in 2 ways:
1. using the config provider, which uses libbeat
2. directly using libbeat

**Comment by kubasobon** [comment]
Verified, no rate limit messages in long-living environment's log.
