### ISSUE TITLE
Facing issues while running Docker file 

### ISSUE THREAD

**Issue by manu-207** [elastic/cloudbeat#2146]
![docker issues](https://github.com/elastic/cloudbeat/assets/117650246/bc8bf2c0-f4b3-4c18-93de-40de61db3858)

 export BASE_IMAGE="docker.elastic.co/beats/elastic-agent:8.13.0-SNAPSHOT"
 docker pull $BASE_IMAGE
 export STACK_VERSION=$(docker inspect -f '{{index .Config.Labels "org.label-schema.version"}}' $BASE_IMAGE)
 export VCS_REF=$(docker inspect -f '{{index .Config.Labels "org.label-schema.vcs-ref"}}' $BASE_IMAGE)
 docker buildx build \
     -f cloudbeat/scripts/packaging/docker/elastic-agent/Dockerfile \
     --build-arg ELASTIC_AGENT_IMAGE=$BASE_IMAGE \
     --build-arg STACK_VERSION=$STACK_VERSION \
     --build-arg VCS_REF_SHORT=${VCS_REF:0:6} \
     --platform linux/$(go env GOARCH) \
     -t "docker.elastic.co/beats/elastic-agent:DEVEL" \
     .
# While running above docker build command i got error

**Comment by moukoublen** [comment]
Hello @manu-207 👋 , 

this docker file copies these three files (`cloudbeat` binary, `bundle.tar.gz` and `cloudbeat.yml`) from the root folder for cloudbeat repo into the container image. 

Could you verify that you execute the above `docker buildx build` from inside the root folder of the cloned cloudbeat repo and that the docker file is not edited?

What I see from your screenshot is 
<img width="674" alt="Screenshot 2024-04-22 at 11 15 42 AM" src="https://github.com/elastic/cloudbeat/assets/1380039/7b187ce3-f1cf-4f48-89fa-46122664f32b">
this:


While this should be shown:
<img width="545" alt="Screenshot 2024-04-22 at 11 15 50 AM" src="https://github.com/elastic/cloudbeat/assets/1380039/2c8c810f-e177-415d-8f77-08788d18f25e">


Thanks!

**Comment by hemalathah** [comment]
Hello @moukoublen 

![image](https://github.com/elastic/cloudbeat/assets/163277943/eb33e231-b506-489e-9e38-5e95419a0590)

**Comment by moukoublen** [comment]
Hello @hemalathah 👋 

Did you follow the step 3 of the readme?

> 3. Build cloudbeat binary and opa bundle (inside `cloudbeat` folder)
>    ```bash
>     GOOS=linux mage build
>    ```

This step will provide the `cloudbeat` binary and the `bundle.tar.gz` that the Dockerfile will later try to copy.

**Comment by hemalathah** [comment]
> Hello @hemalathah 👋
> 
> Did you follow the step 3 of the readme?
> 
> > 3. Build cloudbeat binary and opa bundle (inside `cloudbeat` folder)
> >    ```shell
> >     GOOS=linux mage build
> >    ```
> 
> This step will provide the `cloudbeat` binary and the `bundle.tar.gz` that the Dockerfile will later try to copy.

Hello @moukoublen Its working fine, thank you
