### ISSUE TITLE
Cloudbeat CI - couple build and integration test steps

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#215]
**Problem:**
During the build step, we build and archive the docker images for the next step, after some time those archives are deleted.
In the next step, the integration test, those archives are loaded to a kind cluster, in case the integration test is failing for some reason re-running it will throw the following error:
```
Run kind load image-archive /tmp/cloudbeat-2697324b6001ab022821bd25f6b5b1ccc3e5f925.tar --name=kind-mono & kind load image-archive /tmp/pytest-2697324b6001ab022821bd25f6b5b1ccc3e5f925.tar --name=kind-mono
ERROR: stat /tmp/cloudbeat-2697324b6001ab022[8](https://github.com/elastic/cloudbeat/runs/6862084551?check_suite_focus=true#step:8:9)21bd25f6b5b1ccc3e5f925.tar: no such file or directory
```

It happens because we are deleting the archives and not re-running the build step.

**Comment by uri-weisman** [comment]
FYI - @DaveSys911 @gurevichdmitry

**Comment by uri-weisman** [comment]
It will happen every time the integration test fails and we re-run the fail step.
All I'm saying is that we need to couple both steps (build & integration test) because of the dependency on the generated archives in the build step.

[Example GH run](https://github.com/elastic/cloudbeat/runs/6862084551?check_suite_focus=true)

**Comment by DaveSys911** [comment]
@uri-weisman.
The ci was designed like that to allow us modularity and parallel execution of builds & test suites. Which we plan to extend on in the upcoming tasks.

What you are describing is a minor edge case ci bug that can be easily side-stepped temporarily by re-running both jobs. While your proposed solution impacts other things and creates more issues than it solves. So it isn't a logical tradeoff.

**Comment by uri-weisman** [comment]
@DaveSys911 
I don't think it's an edge case because it will happen every time the integration test step fails.
But I guess we can just re-run both jobs to solve this...
Anyway, thank you for your comments.
