### ISSUE TITLE
Mage is not installating on my Ubuntu Server. 

### ISSUE THREAD

**Issue by sajida2000** [elastic/cloudbeat#2152]
I have used the below commands to install mage on my ubuntu server 
```
git clone https://github.com/magefile/mage
cd mage
go run bootstrap.go
```

and then I am getting the issue as 
![image](https://github.com/elastic/cloudbeat/assets/117704550/60b70950-e887-4f0b-b88c-11fd40529c4e)

Then if i run the command to check whether mage is installed or not. 
![image](https://github.com/elastic/cloudbeat/assets/117704550/4bcacb0b-7f84-4de1-a722-ea0d90a6387d)

As I am not familiar with GO Lang, please help me regarding this issue.

**Comment by sajida2000** [comment]
Hey @moukoublen, Please help me on this.

**Comment by sajida2000** [comment]
Hey @Shankar-Mendyala, you can also help

**Comment by orestisfl** [comment]
From the cloudbeat repo, try `source bin/activate-hermit` which should dynamically load the required binaries.

**Comment by ShankarMendyala** [comment]
Thanks @orestisfl , It worked!
