### ISSUE TITLE
[BUG] Duplicated OPA findings from evaluation for rules on resources

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#219]
**Describe the bug**
We can see that we receive duplicate findings for every resource rule that is being evaluated

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Run cloudbeat and evaluate a resource against a rule
2. Notice that there will be two findings for every resource rule evaluated

**Expected behavior**
Should receive one finding per evaluated resource rule

**Comment by JordanSh** [comment]
This bug was closed without a PR, assuming the work has not been done, removed `8.4 candidate` label

**Comment by eyalkraft** [comment]
@JordanSh this is the fix
- https://github.com/elastic/csp-security-policies/pull/104
