### ISSUE TITLE
how to configure elastic search details in Cloud beat EKS?

### ISSUE THREAD

**Issue by sirishas23** [elastic/cloudbeat#2193]
I have installed the CLOUEBEAT plugin via EKS. My Elasticsearch and Kibana are installed on another EC2 instance. I have configured Elasticsearch details in the following files:

cloudbeat-eks/cloudbeat.yml
base/daemonset.yml

I'm encountering the following error:

{"log.level":"error","@timestamp":"2024-05-08T10:55:07.644Z","message":"Failed to connect to backoff(elasticsearch(http://elasticsearch:9200)): Get \"http://elasticsearch:9200\": lookup elasticsearch on 172.20.0.10:53: no such host","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-default","type":"system/metrics"},"log":{"source":"system/metrics-default"},"log.origin":{"file.line":148,"file.name":"pipeline/client_worker.go"},"service.name":"metricbeat","ecs.version":"1.6.0","log.logger":"publisher_pipeline_output","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-05-08T10:55:07.644Z","message":"Attempting to reconnect to backoff(elasticsearch(http://elasticsearch:9200)) with 11 reconnect attempt(s)","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-default","type":"system/metrics"},"log":{"source":"system/metrics-default"},"service.name":"metricbeat","ecs.version":"1.6.0","log.logger":"publisher_pipeline_output","log.origin":{"file.line":139,"file.name":"pipeline/client_worker.go"},"ecs.version":"1.6.0"}
 {"log.level":"warn","@timestamp":"2024-05-08T10:55:07.647Z","message":"DNS lookup failure \"elasticsearch\": lookup elasticsearch on 172.20.0.10:53: no such host","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-default","type":"system/metrics"},"log":{"source":"system/metrics-default"},"service.name":"metricbeat","ecs.version":"1.6.0","log.logger":"transport","log.origin":{"file.line":52,"file.name":"transport/tcp.go"},"ecs.version":"1.6.0"}

I assume I made mistakes in configuring Elasticsearch details. Please guide me on how to configure Elasticsearch details in EKS.

**Comment by moukoublen** [comment]
duplicate of: https://github.com/elastic/cloudbeat/issues/2170
