### ISSUE TITLE
[CIS AZURE][Dependency Lock] 2.1.20 List security contact data - payload changed

### ISSUE THREAD

**Issue by moukoublen** [elastic/cloudbeat#2242]
**Motivation**
The payload of security contacts details that is used in CIS Rule 2.1.20 has changed from 

```json
{
  "id": "/subscriptions/<subID>/providers/Microsoft.Security/securityContacts/default",
  "name": "default",
  "type": "Microsoft.Security/securityContacts",
  "properties": {
    "alertNotifications": {
      "state": "On",
      "minimalSeverity": "High"
    },
    "notificationsByRole": {
      "state": "On",
      "roles": [
        "Owner"
      ]
    },
    "emails": "...",
    "phone": ""
  }
}
```

to
https://learn.microsoft.com/en-us/rest/api/defenderforcloud/security-contacts/list?view=rest-defenderforcloud-2023-12-01-preview&tabs=HTTP#list-security-contact-data
```json
{
  "id": "/subscriptions/<Your_Subscription_Id>/providers/Microsoft.Security/securityContact/default",
  "name": "default",
  "type": "Microsoft.Security/securityContact",
  "properties": {
    "notificationsByRole": {
      "state": "On",
      "roles": [
        "Owner",
        "Admin"
      ]
    },
    "isEnabled": true,
    "emails": "john@contoso.com;Jane@contoso.com",
    "phone": "(214)275-4038",
    "notificationsSources": [
      {
        "sourceType": "AttackPath",
        "minimalRiskLevel": "Critical"
      },
      {
        "sourceType": "Alert",
        "minimalSeverity": "Medium"
      }
    ]
  }
}
```

For the same reason, the latest Azure SDK arm security version has [breaking changes](https://github.com/elastic/cloudbeat/pull/2230) in our code.  

Because of [this](https://github.com/Azure/azure-sdk-for-go/issues/19740) pre-existing bug in this specific call of Azure SDK in Cloudbeat, a generic arm.NewClient was used as described [here](https://github.com/Azure/azure-sdk-for-go/issues/19740#issuecomment-1914253067). 

It seems we can now revert to using the specialized client and not the generic one. 

The current Cloudbeat's code should work as expected since it uses `2020-01-01-preview` version of the API and the new payload introduced in `2023-12-01-preview`.

**Definition of done**
Cloudbeat's code and possible rego rule need to be updated according to the latest SDK version / new payload.

**References**
https://learn.microsoft.com/en-us/rest/api/defenderforcloud/security-contacts/list?view=rest-defenderforcloud-2023-12-01-preview&tabs=HTTP#list-security-contact-data

https://github.com/Azure/azure-sdk-for-go/pull/22668/files#diff-a077f61aaeaeaab8f5eb2aea4011aa1f67ae05f2c4fc16840f97afcc47e7a14cR2458-R2460

https://github.com/Azure/azure-sdk-for-go/pull/22668/files#diff-a077f61aaeaeaab8f5eb2aea4011aa1f67ae05f2c4fc16840f97afcc47e7a14cR2458-R2460

https://github.com/Azure/azure-sdk-for-go/pull/22668/files#diff-a077f61aaeaeaab8f5eb2aea4011aa1f67ae05f2c4fc16840f97afcc47e7a14cR5901-R5940

**Comment by kubasobon** [comment]
Verified
![Image](https://github.com/user-attachments/assets/8f931a86-2b23-412d-8aea-25644a3c117f)
