### ISSUE TITLE
[BUG] Deletion of policy and integrations left undeleted csp rule templates

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#229]
**Describe the bug**
When deleting the agent policy and the integration (including assets), I saw that the csp rule templates from the saved objects are not being deleted and are left over.

**Preconditions**
Deployed cloud environment with local agent and integration running

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Delete agent policy
2. Uninstall integration

**Expected behavior**
I've expected the csp rule templates to be deleted from the saved objects

**Screenshots**
<img width="1728" alt="Screen Shot 2022-06-20 at 20 11 21" src="https://user-images.githubusercontent.com/12246907/174650904-4edc894f-ff92-4ff4-bb9d-31a1e5688a1b.png">
<img width="1728" alt="Screen Shot 2022-06-20 at 20 11 02" src="https://user-images.githubusercontent.com/12246907/174650922-72b93822-aa02-4a03-8cc0-efbba1ceca98.png">
<img width="1728" alt="Screen Shot 2022-06-20 at 20 10 40" src="https://user-images.githubusercontent.com/12246907/174650926-88f623c4-f0d9-47ec-93dc-a3dc5005f410.png">

**Comment by eyalkraft** [comment]
I think this is fleet related and not on our side.
@orouz are you familiar with this? @gurevichdmitry says you might know about this already

**Comment by orouz** [comment]
@eyalkraft 

i need to look into this. according to @CohenIdo, fleet installs the templates so it's expected they'd remove it too.

**Comment by kfirpeled** [comment]
duplicated https://github.com/elastic/kibana/issues/137023
