### ISSUE TITLE
[BUG] Cloudbeat period stops when container is stopped

### ISSUE THREAD

**Issue by eyalkraft** [elastic/cloudbeat#230]
**Describe the bug**
When cloudbeat's process "sleeps", cloudbeat doesn't take into account the time passed for the next period.
When cloudbeat is continued, it will still wait for the whole period to pass before producing new findings.

**Preconditions**
Your Mac should go to sleep upon lid closing.
The agent runs on kind cluster on you local machine.

**To Reproduce**
1. Run a full setup with an agent + integration
2. close the lid of your Mac for X time. (I think this could also be achieved by running `docker pause` on the kind nodes)
3. When reopening you computer, after a few minutes the agents will show as healthy again in the fleet UI. (or `docker unpause`)
4. Even if the period time have passed since the last cycle, new cycle will not be triggered until the full cycle period has passed while cloudbeat is awake.

**Expected behavior**

This is low priority since cloudbeat would normally run in k8s cluster that isn't suspended.
Still, the expected behavior would be to immediately run another cycle if the period time has passed.

**Screenshots**

The agent's time is in sync with the host.
<img width="790" alt="Screen Shot 2022-06-21 at 10 27 13" src="https://user-images.githubusercontent.com/63912106/174743439-6b7e55c8-0257-49db-a7e9-f581ef0ddee1.png">

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: 
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by tinnytintin10** [comment]
@eyalkraft do you foresee a scenario where this happens on a prod cluster?

**Comment by eyalkraft** [comment]
Not really.
[Pod Lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/):
> Pods are only scheduled once in their lifetime. Once a Pod is scheduled (assigned) to a Node, the Pod runs on that Node until it stops or is terminated.

**Comment by tehilashn** [comment]
@eyalkraft - do you think it's a bug that customers can encounter?
