### ISSUE TITLE
[CSPM][GCP] 403 Error When Fetching Organization Information

### ISSUE THREAD

**Issue by CohenIdo** [elastic/cloudbeat#2369]
**Describe the bug**
When installing CSPM GCP using either manual installation or Cloud Shell, Cloudbeat logs the following error:

```
[elastic_agent.cloudbeat][error] error fetching GCP Org: organizations/992493199029, error: googleapi: Error 403: Permission 'resourcemanager.organizations.get' denied on resource '//cloudresourcemanager.googleapis.com/organizations/992493199029' (or it may not exist).
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "cloudresourcemanager.googleapis.com",
    "metadata": {
      "permission": "resourcemanager.organizations.get",
      "resource": "organizations/992493199029"
    },
    "reason": "IAM_PERMISSION_DENIED"
  }
]
, forbidden
```

**To Reproduce**
1. Install CSPM GCP integration.
2. Deploy an agent.
3. Check the logs.

**Related links**
- [Slack thread](https://elastic.slack.com/archives/C03E5KGNWT1/p1722254309679389)

**Comment by gurevichdmitry** [comment]
Verified in version 8.16.0 BC1 – the "error fetching GCP org" message no longer appears.
![Image](https://github.com/user-attachments/assets/029843fc-5255-447f-bb4f-fe6bbab36777)
