### ISSUE TITLE
[BUG] Object resource type failed to send events without recovery

### ISSUE THREAD

**Issue by CohenIdo** [elastic/cloudbeat#241]
**Describe the bug**
After cloudbeat was running for 8 cycles (~28 hours), k8s object resource types were no longer sent.

![image](https://user-images.githubusercontent.com/90558359/175811711-7fa1b8e9-32c3-41cb-8376-54278389f0f9.png)

In the graph, we can see that other resource types are sent while `k8s_object` stop.

**Preconditions**

**To Reproduce**
1. Cloud environment with 8.3 latest
2. EC2 instance that runs a basic cluster with 1 node. 

**Expected behavior**
Fetcher should be recovered in case of failure.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: 
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by oren-zohar** [comment]
can you please attach cloudbeat logs? is the instance still online? can you share access to it?

**Comment by tinnytintin10** [comment]
@CohenIdo let's wait for the resolution of https://github.com/elastic/cloudbeat/issues/145 and see if that solves the bug here.
