### ISSUE TITLE
Support configuration of watched Kubernetes resources 

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#246]
**Motivation**
As a developer, I would like to be able to configure what Kubernetes resources are watched. 

**In-depth**
Currently, there is a hard-coded configuration that determines what Kubernetes resources should be collected.
Since different benchmark requires different Kubernetes resources we should be able to configure what resources are being collected from Kubernetes.

 
**Definition of done**
- Cloudbeat receives configuration that determines what Kubernetes resources it needs to collect.

**Related tasks/epics**
[#2468
](https://github.com/elastic/security-team/issues/2468)

**Comment by tehilashn** [comment]
Currently in our solution there is no need to configure which k8s objects are collected, closing this as "won't do"
