### ISSUE TITLE
Workflows updates after `8.x` branch-out

### ISSUE THREAD

**Issue by moukoublen** [elastic/cloudbeat#2492]
**Motivation**
We branched out of the [8.x](https://github.com/elastic/cloudbeat/tree/8.x) branch, and both [8.x](https://github.com/elastic/cloudbeat/tree/8.x) and the main (9.x) branches will be long-lived branches from which we will branch out of the `8.x.y` and `9.x.y` releases.

Because of that we need to update our [bump-version.yml](https://github.com/elastic/cloudbeat/blob/main/.github/workflows/bump-version.yml) and [updatecli.yml](https://github.com/elastic/cloudbeat/blob/main/.github/workflows/updatecli.yml) workflows to follow that logic. 

### [A] `bump-version.yml`
The [bump-version.yml](https://github.com/elastic/cloudbeat/blob/main/.github/workflows/bump-version.yml) should either be able to handle version bump for both `9.x.y` and `8.x.y` releases, or keep working for the latest version `9.x.y` and we will handle `8.x.y` bumps manually. 

### [B] `.github/workflows/publish-cloudformation.yml`
We should adjust the cloudformation deployment for the `8.x` branch (or ignore it). 

### [C] Dependencies and tools (updatecli.yml && dependabot)
The flow stays the same for the `main` branch as it currently is. 

For the `8.x` branch, we need to keep backporting everything (expect from beats) from the `main` up to the point that the two major releases will have different features planned (features/fixes in the `9.0.0` release that are not scheduled for the `8.x.y` release). 

But regarding dependencies updates, we should decide on one of the following: 
  1. Backport each dependency update PR and solve the conflict on each PR (if occurs).
  2. Establish a process in which we merge the dependencies updates PR to take place in the same order (when we merge the bump A for main next thing is to merge bump A for 8.x)
  3. Do not backport bumps and have a standalone updatecli +dependabot over the 8.x

More specifically the `beats` updates perhaps needs to follow the beats `8.x` branch for `cloudbeat` `8.x` branch and `beats` `main` branch for `cloudbeat` `main` branch.

Based on that we need to update [updatecli.yml](https://github.com/elastic/cloudbeat/blob/main/.github/workflows/updatecli.yml) and dependabot accordingly.

**Comment by romulets** [comment]
Reopening because we need to think about the bump flow

**Comment by kubasobon** [comment]
### Update
ad. A: I opened a PR to fix the issue https://github.com/elastic/cloudbeat/pull/2757
ad. B: After investigation, I concluded the current workflow works for every minor release. Integrations will never point to `8.x`, `9.x`, or any non-release version of Cloud Formation, ARM templates etc. No change required.

**Comment by kubasobon** [comment]
Related: https://github.com/elastic/cloudbeat/issues/2563
