### ISSUE TITLE
[CSPM] [Azure] [SDH] Timeout on Azure fetchers

### ISSUE THREAD

**Issue by moukoublen** [elastic/cloudbeat#2624]
**Describe the bug**
Azure fetchers in accounts with large number of resources take more time than anticipated and exceed the timeout in cloudbeat internal fetchers handling that is [hardcoded](https://github.com/elastic/cloudbeat/blob/6e7b8521343411244d7f0f6f3af828681cad16fc/internal/flavors/benchmark/azure.go#L52-L53) to 20 mins.

**Preconditions**
CSPM Azure is a subscription with a large number of resources.

**Potential Solutions**
We should either increase the hardcoded fetcher timeout to e.g. 3 hours (it seems there is no reason for less since the cycle is usually 24h) [quick fix].

or

Change the approach entirely and not limit each fetcher with a standalone timeout, but instead, use a context with a timeout from the beginning of the cycle + `cycle time`.

**Comment by orouz** [comment]
the second approach sounds better. i think we should utilize `period` (from cloudbeat config) and let the fetchers take as much time as the it allows.

**Comment by moukoublen** [comment]
The quick fix was merged to: 
  * `main` (`9.x`).
  * `8.x` (will be included to `8.16.0` BC2).
  * `8.15` will be included to `8.15.4`.
