### ISSUE TITLE
[Asset Inventory] Cloudbeat panics if SNS topic fetching returns error

### ISSUE THREAD

**Issue by moukoublen** [elastic/cloudbeat#2640]
**Describe the bug**
When 

The problem exists in code: [here](https://github.com/elastic/cloudbeat/blob/59b2ffd8ae0c272ab87d7b63fad438ad4eb632fa/internal/resources/providers/awslib/sns/provider.go#L93-L96) and [here](https://github.com/elastic/cloudbeat/blob/59b2ffd8ae0c272ab87d7b63fad438ad4eb632fa/internal/resources/providers/awslib/sns/provider.go#L49-L52).

While handling `ListTopics` and returning an error, a break/continue is required and missing. Thus the code attempts to access parts of the nil pointer and panics.

The fix is low-effort and could be backported to the next 8.16.0 BC. 

![Image](https://github.com/user-attachments/assets/c6c1212b-9212-4961-b825-555b0d2961ea)

**Comment by uri-weisman** [comment]
@oren-zohar @jeniawhite - isn't it already verified for 8.16/8.17?
