### ISSUE TITLE
`cloud.instance.id` and `resource.id` missing `i-` prefix for CNVM

### ISSUE THREAD

**Issue by maxcold** [elastic/cloudbeat#2645]
**Describe the bug**
In AWS Instance ids usually start with `i-` prefix, but in the data coming from CNVM integration this prefix is stripped 

**Preconditions**
Have an environment with the data ingested from CNVM

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Open any vulnerability finding and look for `cloud.instance.id` and `resource.id` fields, they will be missing `i-` prefix

**Expected behavior**

The instance id should not be stripped out of any symbols

![Image](https://github.com/user-attachments/assets/6d1ac7f3-9573-4240-9de8-d756d618b4e6)

**Comment by animehart** [comment]
![Image](https://github.com/user-attachments/assets/df523447-e019-49e2-9a86-fe1394a14ef0)
![Image](https://github.com/user-attachments/assets/054d05a6-34e3-4e55-9bee-c4f5e249e79b)

`cloud.instance.id` and `resource.id` has i- prefix now
Verified
