### ISSUE TITLE
Agent fails to start - Cloudformation deployment for an organization

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#2681]
**Describe the bug**
Failed to deploy cloudbeat using cloudformation for an organization.

Error message:

```
Error: Resource handler returned message: "Resource of type 'Stack set operation [0c370d76-10db-491f-ac3f-1f4a90d42b50] was unexpectedly stopped or failed. status reason(s): [Target organizational unit could not be found]' with identifier 'cloudbeat-role-stackset:c5c0cef9-1750-4b2a-bf11-acbc9d20fdd0' did not stabilize." (RequestToken: 75e6f4e0-5300-b392-d274-2d7e395b3567, HandlerErrorCode: NotStabilized)
```

**Preconditions**
Serverlesss/ESS environment

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Deploy an agent using cloudformation (AWS), use the team's organization account.
2. In the CloudFormation template I picked the following organizations: `OU: ou-second-organization,ou-test-organization`

**Expected behavior**

-  Findings should be ingested

**Comment by kubasobon** [comment]
For the record, the Cloud Formation template specifies that it expects the unique ID of the OU, not the name. [link](https://github.com/elastic/cloudbeat/blob/main/deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml#L6-L12)

In case presented by the attached picture, you'd input `ou-rnzf-50ahay8z`, not `test-ou`.

![Image](https://github.com/user-attachments/assets/c7103d48-91a3-494f-afd1-793845f29828)

Given the examples of OU IDs you've attached in the issue (`OU: ou-second-organization,ou-test-organization`), I'd wager those are `ou-<NAME>`, not `ou-<AWS-UNIQUE-ID>`.

**Comment by oren-zohar** [comment]
according to @kfirpeled we can close this as this is not relevant anymore
