### ISSUE TITLE
Pagination support for EKS requests

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#283]
**Motivation**
As a developer, I would like to support fetching a provider that uses paginated requests.

**In-depth**
Some of the EKS providers support paginated requests. I.e when cloudbeat calls the AWS provider's API, the API will return the first 100 results along with a pagination token. 
This pagination token should be used to continue to get the rest of the results.

Currently, we only ship the first paginated results (100 results) but we would like to ship all the results to the evaluator.

This PR might result in a fetcher design change that will affect the entire fetcher interface.

**Definition of done**
- Get all the relevant results from ECR+ELB using paginated requests.

**Comment by ofiriro3** [comment]
In order to validate this ticket, we will need to create 100 different private ECR repositories, and deploy them all on ECR.

It is possible doing it, but since we haven't run a big cluster against Cloudbeat, it might cause all sorts of different problems.

**Comment by oren-zohar** [comment]
or change the page size and check locally

**Comment by orouz** [comment]
this would be tested before we go GA @ofiriro3
