### ISSUE TITLE
[BUG]Fixing EKS CIS_3_2_9 - Ensure that the --event-qps argument is set to 0 or a level which

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#284]
**Describe the bug**
As part of performing the E2E integration test (https://github.com/elastic/security-team/issues/3003), we found that EKS rule CIS_3_2_9 is not being evaluated.

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
0. Run an EKS cluster
1. Open Kibana 
2. Add the `CIS Kubernetes Benchmark`
3. Enable the EKS benchmark.
4. Add the relevant access key + secret and add the integration.
5. Deploy the elastic agent into your EKS cluser
6. Wait for the first cycle of findings to appear - there is no finding to rule `CIS_3_2_9`

**Please verify**
Please verify that the rule is enabled in the `data.yaml`

**Expected behavior**
- Rule `CIS_3_2_9` should be evaluated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome
 - Kibana Version: 8.4, Build 54051, Commit 39af11af42cf1a0a7f35dc3cf76d8f24af624149
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by ofiriro3** [comment]
E2E validation was made

![Image](https://user-images.githubusercontent.com/19221736/181724275-1287c8e7-6705-4d06-b4e8-7f3f9b83886a.png)

**Comment by JordanSh** [comment]
@ofiriro3 please comment about the verification status of this bug
