### ISSUE TITLE
[BUG]Fixing EKS CIS_5_4_3 - Ensure clusters are created with Private Nodes

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#285]
**Describe the bug**
As part of performing the E2E integration test (https://github.com/elastic/security-team/issues/3003), we found that EKS rule CIS_5_4_3  is not being evaluated.

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
0. Run an EKS cluster
1. Open Kibana 
2. Add the `CIS Kubernetes Benchmark`
3. Enable the EKS benchmark.
4. Add the relevant access key + secret and add the integration.
5. Deploy the elastic agent into your EKS cluser
6. Wait for the first cycle of findings to appear - there is no finding to rule `CIS_5_4_3 `

**Please verify**
Please verify that the rule is enabled in the `data.yaml`

**Expected behavior**
- Rule `CIS_5_4_3` should be evaluated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: chrome
 - Kibana Version: 8.4.0, build 54051, commit 39af11af42cf1a0a7f35dc3cf76d8f24af624149
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by ofiriro3** [comment]
E2E validation was made 



![Image](https://user-images.githubusercontent.com/19221736/181724444-7089c416-2171-4f59-83c8-7a8b3130a7b6.png)

**Comment by CohenIdo** [comment]
QA Cycle 1 : verifying failed. 
Assuming that the cloudbeat that we are using is not part of the BC but for now
