### ISSUE TITLE
[Discussion] - What should happen when entering wrong AWS credentials

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#307]
**Motivation**
Currently, cloudbeat crushes if the AWS credentials are not valid.

We would like to check other integration, and according to it, decide what should happen when a user provides the wrong AWS credentials.

DOD:
- Adding this case to testtrail

**Comment by ofiriro3** [comment]
After a short investigation, our current behavior works as the following suggests:

- When using wrong credentials Cloudbeat manager tries to create the relevant AWS fetchers, but it encounters an error when trying to get the user identity related to these credentials. This result in a fetcher factory failure, which makes the beat `launcher` returns an error. 

`[elastic_agent.cloudbeat][error] Could not run Beater: %!w(*fmt.wrapError=&{Could not create beater: could not retrieve user identity for ECR fetcher: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 649b00cd-b05c-4a30-a6f1-2fac75ef08ad, api error InvalidClientTokenId: The security token included in the request is invalid. 0xc0002e3ca0})`

After the beats launcher throws an error, cloudbeat is restarted and tries to run itself again and again.

**Comment by ofiriro3** [comment]
When looking into other beats it seems that they crash too when they are provided with the wrong credentials:

- AWS Dynamo DB integration: it seems that giving the wrong credentials crushes the metric beat. 
The status of Metricbeat changed to `FAIL`.
- Logs are attached:

`	* 1 error: Error creating runner from config: 1 error: error creating aws metricset: failed DescribeRegions: AuthFailure: AWS was not able to validate the provided access credentials.

`[elastic_agent.metricbeat][info] Status change to Failed: 1 error occurred:
	* 1 error: Error creating runner from config: 1 error: error creating aws metricset: failed DescribeRegions: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: 249d1ffc-d301-4095-b2d1-fdd070437940`

`[elastic_agent][error] 2022-08-08T19:02:34+03:00 - message: Application: metricbeat--8.3.3[2b0e14fe-3875-4f37-8867-c72f2e8752b4]: State changed to FAILED: 1 error occurred:`

- EC2 logs + metrics - looks like the same behavior is the Dynamo DB. Logs are attached.

`[elastic_agent][error] 2022-08-08T19:18:24+03:00 - message: Application: metricbeat--8.3.3[2b0e14fe-3875-4f37-8867-c72f2e8752b4]: State changed to FAILED: 1 error occurred:
	* 1 error: Error creating runner from config: 1 error: error creating aws metricset: failed DescribeRegions: AuthFailure: AWS was not able to validate the provided access credentials
`

**Comment by ofiriro3** [comment]
To resolve this discussion I suggest two optional solutions:

**Option 1**- Crush Cloudbeat when receiving wrong credentials.
Adv: 
1. It is aligned with the rest of the other Beats behaviors.
2. The user does not receive any findings so it will be easier for him to detect that there is a problem. For further information, he can access the agent log.

Dsv:
1. There are some resources that can be collected, and we don't collect them.


**Option 2 **- When a user inserts wrong credentials, Cloudbeat won't crush and will fetch the resources available to it.

Adv:
1. Cloudbeat can still collect many resources relevant to the benchmark - files, processes, and K8s objects.

Dsv:
2. It might not be clear to the user that there is a problem since findings will be collected. He will find the error only if he will try to look for an error in the agent logs.


**My opinion**
I think that we should stick with the first solution since the rest of the beats behave that way. 
As a company, I believe that most of our products need to be aligned with each other so we will be able to educate our customers with common patterns.
Moreover, in this case, I believe that the `fall fast` approach will help to the user to easily detect problems sooner.

Would like to hear your thoughts on this one.

@tehilashn @tinnytintin10 @amirbenun @kfirpeled @eyalkraft

**Comment by amirbenun** [comment]
Thanks @ofiriro3 for this documentation of the current behavior and your great input regarding the desired state.
I absolutely agree with **Option 1**, when wrong credentials are provided - cloudbeat should crush. Mainly because I can't think of a better way to tell the user that something went wrong. On any other option where cloudbeat keeps running in partial mode, the user will have to search the logs in order to find out that the credentials are wrong.

Having said that, I think we should improve the log message in such a case. The log message you shared is coming from a fetcher which is a deeper piece of our code. Maybe instead we can verify the credentials at the beginning of the flow, to have a short circuit and fail in an earlier state, ideally with a more clear log message.

**Comment by eyalkraft** [comment]
++ option 1

Later on we should make sure the "wrong credentials error" is reflected in cloudbeat's health status introduced by the agent architecture v2.
See related issue
- https://github.com/elastic/cloudbeat/issues/239

**Comment by kfirpeled** [comment]
Option 1 is not ideal. Having wrong credentials crashing a process is something I would do only if it is a must, and I don't think it is a must. 

As Eyal mentioned going forward we would definitely report statuses from the beat back to kibana. And I'm happy to see that there's an existing solution that we could use.

**Comment by tehilashn** [comment]
For 8.4 let's keep it as it is. pushing it for 8.5 (GA) to finalize the discussion.

**Comment by ofiriro3** [comment]
@tehilashn @amirbenun 

So what is the final decision?

I can fix it with no backporting to 8.4.

**Comment by amirbenun** [comment]
Tehila meant that the current behavior is good enough for 8.4.
But we still need to better define the required behavior for the long term.

**Comment by tinnytintin10** [comment]
Thank you for the thoughtful explanation Ofir <3

++ for 8.4, let's keep it as is. After BH, I will document exactly what behavior I want to see from a product perspective and share it with y'all. Thanks for your thoughtful explanation Ofir <3

**Comment by amirbenun** [comment]
Pushing to sprint 16

**Comment by olegsu** [comment]
Do we want to distinguish between a setup configuration ( when the cloudbeat process starts ) and an update from the console?
IMO, during the setup, it is a good approach to exit with an error. On the other hand, when configuration changes during runtime it is better to report the error back to the console so the user can handle it.

**Comment by ofiriro3** [comment]
@olegsu good question.

As far as I know, every time a new configuration is sent from the agent, the Cloudbeat restarts itself and loads all the fetchers and the rest of the config from the ground up.
So I am not sure if such a distinguish is possible.

**Comment by olegsu** [comment]
@ofiriro3 Thanks, this is a good point.
So right, in that case, we don't have that option anyway.

**Comment by olegsu** [comment]
A [task](https://github.com/elastic/cloudbeat/issues/388) was created, closing this discussion.
