### ISSUE TITLE
[BUG] OPA can't evaluate k8s object correctly

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#316]
**Describe the bug**
When running the EKS benchmark, it seems that one of the complete rules produces multiple outputs, which is not allowed by rego.

**Preconditions**
EKS cluster 
ELK stack

**To Reproduce**
1. Run the EKS integration
2. Look at the cloudbeat logs, you should see the following error:

`{"log.level":"error","@timestamp":"2022-07-31T17:18:11.304Z","log.logger":"cloudbeat","log.origin":{"file.name":"pipeline/pipeline.go","file.line":40},"message":"error running the policy: /compliance/lib/data_adapter/data_adapter.rego:122: eval_conflict_error: complete rules must not produce multiple outputs","service.name":"cloudbeat","ecs.version":"1.6.0"}`

**Expected behavior**
1. Multiple evaluations for complete rules should not be happening. 

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: 8.4.0, build 55079 commit 5cb4e6be2cc65a4d2e353711adf26d4d723d9ef6
 - Endpoint Version:
 - Other Version:

**Comment by ofiriro3** [comment]
After a short investigation, it appears that there are 8 rules related to this topic. 
Disabling all of these 8 rules, made OPA stop producing this error.

`{"log.level":"error","@timestamp":"2022-08-02T13:59:54.517Z","log.logger":"cloudbeat","log.origin":{"file.name":"pipeline/pipeline.go","file.line":40},"message":"error running the policy: /compliance/lib/data_adapter/data_adapter.rego:122: eval_conflict_error: complete rules must not produce multiple outputs","service.name":"cloudbeat","ecs.version":"1.6.0"}`

Which relates to https://github.com/elastic/csp-security-policies/blob/main/bundle/compliance/lib/data_adapter/data_adapter.rego#:~:text=is_service_account_or_pod%20%3D%20service_account-,containers%20%3D%20c%20%7B,-input.resource.kind.

These eight rules are related:
EKS
- 4.2.1
- 4.2.5
- 4.2.6
- 4.2.9

Vanilla 
- 5.2.2
- 5.2.6
- 5.2.7
- 5.2.10

**Comment by ofiriro3** [comment]
I am assigning @oren-zohar  to this one since he is familiar with the Rego code and asked to be assigned to it.

**Comment by oren-zohar** [comment]
**Update**
The issue is only replicated on EKS.
Trying to debug this bug I encountered the following issues:
- The debug logs we have in cloudbeat are not useful for me to extract the relevant resource that causes the error since we only print the resource on successful evaluation 😢 
- I could not enable the OPA decision logger, because of the issues @amirbenun found.
