### ISSUE TITLE
[BUG]Cloudbeat crashes after few findings cycles

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#319]
**Describe the bug**
After running cloudbeat for some time, and waiting for it to perform a number of cycles, cloudbeat crashes. 

**Preconditions**
- ELK stack
- EKS cluster

**To Reproduce**
1. Run the EKS integration.
2. Wait for a few cycles to run.
3. After a few cycles Cloudbeat will crush and will stop working.

**Investigation conclusions so far**
- The bug is non-determinsitic - sometimes the bug is reproduced after 2 cycles, sometimes after 10 cycles.
-  We suspect it related to this error `[elastic_agent][error] cloudbeat stderr: "fatal error: concurrent map writes\n"`

**Mesures took**
- Added a lot of logs in cloudbeat

**Expected behavior**
Cloudbeat should not crush.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Kibana Version: 8.4.0, Build: 55079 Commit: 5cb4e6be2cc65a4d2e353711adf26d4d723d9ef6
 - Endpoint Version:
 - Other Version:

**Comment by oren-zohar** [comment]
from the way the logs are structured, It looks to me like an error in OPA, also not the first time it happened, see [here](https://github.com/open-policy-agent/opa/blob/9a9504940f3fcbf64820c85c597517feb0c3cb57/CHANGELOG.md#0134) and [here](https://github.com/open-policy-agent/opa/blob/9a9504940f3fcbf64820c85c597517feb0c3cb57/CHANGELOG.md#fixes-63). Did we change anything in the way we work with OPA?

**Comment by ofiriro3** [comment]
One assumption that is currently under investigation:

We have another bug [complete rule produces multiple outputs](https://github.com/elastic/cloudbeat/issues/316).

we suspect that the complete rule causes multiple outputs throws `panic` and crushes OPA.
Then when the OPA server is dead, cloudbeat crushes as well.
I am adding some logs now to verify this is the case.


I was able to reproduce the bug in both EKS and Vanilla setups.

**Comment by ofiriro3** [comment]
We thought that the error message `fatal error: concurrent map writes\n` implies that OPA is about to crush.
We found out that there are eight rules that are related to it, 4 EKS and 4 vanilla - after disabling them the error doesn't appear anymore but cloudbeat continues to crush.

**Comment by ofiriro3** [comment]
In the end, @amirbenun found the root cause of the problem.
It appears that the beats' version Cloudbeat uses had a bug - https://github.com/elastic/elastic-agent-system-metrics/blob/v0.4.3/metric/system/process/process.go#L137.
(10 days ago we updated Cloudbeat to use this beats version)

Once we upgraded the version of the beat, the problem was solved.


<img width="1630" alt="image" src="https://user-images.githubusercontent.com/19221736/182583094-51d413b2-c84b-4e28-a49e-01ce38f6b4a1.png">
