### ISSUE TITLE
Support EKS and vanilla with Kustomize framework

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#332]
**Motivation**
As we progress and move forward there are many deployment files we edit and change.
It causes misconfiguration and weird behavior when trying to deploy our services.

**In-Depth**
Initially, this task was created to provide a cloudbeat-eks standalone `YAML` file.
But, we exposed a bigger issue, that once in a while we break deployment files and spend a lot of time fixing them and maintaining them.

As part of this task, we will do a broad cleanup in old configurations and use only (`Kustomize`) [https://github.com/kubernetes-sigs/kustomize]

**DOD:**
- Move all deployment creation to use Kustomize
- Fixing relevant READMEs
- Aligning the JUST commands with the Kustomize eco-system.

**Comment by ofiriro3** [comment]
Add to the DOD: how to maintain this file

**Comment by tehilashn** [comment]
This does not seem as an 8.4 candidate, removing that label.

**Comment by ofiriro3** [comment]
I delivered a working `.yaml` file to @DaveSys911.

We wish to easily maintain this file, so I'll dedicate some time to make it work with `customize` framework.

**Comment by DaveSys911** [comment]
As discussed good idea to update the cloudbeat.reference.yml & cloudbeat.yml(the ones generated by mage) with the config options missing from it, but present in `config.go` https://github.com/elastic/cloudbeat/blob/main/config/config_test.go
Like the streams section & data.yml, perhaps with some comments/examples on defaults.

**Comment by gurevichdmitry** [comment]
Cloudbeat deployment for Vanilla and EKS is created using kustomize. just commands exist, and Cloudbeat readme provided.
Verified in version 8.5 BC-1 - fixed.
