### ISSUE TITLE
Fixing Kustomize CI 

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#348]
**Motivation**
We would like to fix the broken unit tests regarding the new `Kustomize` feature that is now fully supported.

**In-Depth**
After emerging the EKS support using the `Kustomize` feature, some of the `strict` checks were broken.
Since it wasn't a mandatory check in the CI, the content was merged regardless of the failed tests.

**Definition of done**
- Fix the broken CI tests.
- Consider making these tests mandatory for the CI to pass.

**Related tasks/epics**
- https://github.com/elastic/cloudbeat/issues/332

**Comment by oren-zohar** [comment]
@DaveSys911 any reason why we don't have these checks as required in the first place?
