### ISSUE TITLE
CUSTOMER FEATURE REQUEST: support gathering aws credentials from the instance metadata or from kubernetes service account

### ISSUE THREAD

**Issue by alexcote1** [elastic/cloudbeat#365]
**Motivation**

it might be easier to scale or more secure in a given environment to make aws credentials needed for the KSPM audit in an alternative way. Instead of having statically defined long lived credentials, this also has the benefit of working out of the box in some environments 

**Definition of done**

the integration is able to operate in eks mode with no credentials directly defined, and when in that situation trys to gather the needed credentials from the IMDS server or by trying to exchange its service account of aws credentials (docs here https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) . Both methods are already natively supported in the go aws-sdk already in use
**Out of scope**

to be defined

**Related tasks/epics**

Reference related issues and epics

**Checklist**

Please follow the following checklist in the beginning of your work, please comment with a suggested of high level solution. It should include:
- [ ] Comment describing high level implementation details
   - [ ] Include API and data models
   - [ ] Include assumptions being taken
   - [ ] Provide backward/forward compatibility when changing data model schemas and key constants
   - [ ] Mention relevant individuals with a reason (getting feedback, fyi etc)
- [ ] Submit a PR for our [technical index](https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/Technical_Index.mdx) that includes breaking changes/ new features

**Before closing this ticket**
- [ ] Commit the [technical index](https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/Technical_Index.mdx) PR
- [ ] Reference to tech-debts that shall be solved as we move forward
- [ ] Run the [ECS mapping generator](https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/tools/ecs/README.mdx) in case of an ECS schema updates and commit the auto-generated mappings to the integration repo

**Comment by eyalkraft** [comment]
Thanks for opening this issue @alexcote1!
We're definitely looking to further reduce UX friction and improve security (minimum configuration, work out-of-the-box, eliminate the need for hardcoded credentials).
Your suggestion is great and definitely resonates with some ideas we already have.

We'll take your request into consideration and update when this enhancement could be expected.

**Comment by olegsu** [comment]
Hey @alexcote1 https://github.com/elastic/kibana/pull/140272 includes additional authentication options, similar to other AWS integrations.
It will be available on the 8.5 release.

**Comment by alexcote1** [comment]
great thanks alot
