### ISSUE TITLE
Add cluster name to findings - using existing impl. in libbeat 

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#391]
**Motivation**

Currently, there is an existing heuristic that gets the cluster name. We wish to leverage that capability and use it when it is possible.

**Definition of done**

- [x] Add the existing solution of cluster name to `orchestrator.cluster.name`
- [x] Add to the integration the mapping for this field in `ecs.yml`
- [x] Update technical index of findings

**Out of scope**

- Improving current heuristic impl.
- https://github.com/elastic/security-team/issues/3929

**Related tasks/epics**

- https://www.elastic.co/guide/en/ecs/current/ecs-orchestrator.html#field-orchestrator-cluster-name
- https://github.com/elastic/beats/issues/30229

**Checklist**

Please follow the following checklist in the beginning of your work, please comment with a suggested of high level solution. It should include:
- [ ] Comment describing high level implementation details
   - [ ] Include API and data models
   - [ ] Include assumptions being taken
   - [ ] Provide backward/forward compatibility when changing data model schemas and key constants
   - [ ] Mention relevant individuals with a reason (getting feedback, fyi etc)
- [ ] Submit a PR for our [technical index](https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/Technical_Index.mdx) that includes breaking changes/ new features

**Before closing this ticket**
- [ ] Commit the [technical index](https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/Technical_Index.mdx) PR
- [ ] Reference to tech-debts that shall be solved as we move forward
- [ ] Run the [ECS mapping generator](https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/tools/ecs/README.mdx) in case of an ECS schema updates and commit the auto-generated mappings to the integration repo

**Comment by oren-zohar** [comment]
I see you already went with creating a new processor [here](https://github.com/elastic/cloudbeat/pull/455):
If all this processor does is add the cluster name I would just merge it with our current processor and maybe let's edit its name from `add_cluster_id` to `add_cluster_metadata`.

**Comment by ofiriro3** [comment]
![image](https://user-images.githubusercontent.com/19221736/196385822-3acd8468-7d01-4f4f-8eb3-4574892dfef1.png)

**Comment by ofiriro3** [comment]
@oren-zohar Sounds like a good suggestion.

I am just wondering about the name and the purpose of this processor.
Do we wish to limit the processor to only `cluster_metadata` or to rename it to `add_orchestrator_metadata`?

There are pros and cons to each approach.

**Comment by oren-zohar** [comment]
> Therefore, I suggest keeping the same add_cluster_id as the processor key but changing its logic and its relevant files to add_orchestrator_metadata.

since this would be the safest option in terms of backward compatibility, and since this processor is for internal use only I think the old name is good enough, as long as we document it properly.

**Comment by ofiriro3** [comment]
From the integration -     
```
orchestrator.cluster.name:
      dashed_name: orchestrator-cluster-name
      description: Name of the cluster.
      flat_name: orchestrator.cluster.name
      ignore_above: 1024
      level: extended
      name: cluster.name
      normalize: []
      short: Name of the cluster.
      type: keyword
```

**Comment by tehilashn** [comment]
Thanks @ofiriro3 , did you also verify that the cluster name shows up in the dashboard?

**Comment by kfirpeled** [comment]
> Thanks @ofiriro3 , did you also verify that the cluster name shows up in the dashboard?

@ofiriro3 I've tested your change, my documents do have `orchestrator.cluster.name` however it doesn't appear on the dashboard, can you check that and add a fix?

**Comment by ofiriro3** [comment]
As far as I understand, the usage of `orchestrator.cluster.name` in the dashboard wasn't defined in the ticket, which is why I haven't checked it.

I will create another PR for updating the UI with the `orchestrator.cluster.name`

**Comment by oren-zohar** [comment]
Verified 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/85433724/205765040-9e6d607d-03f0-4f00-855d-f47e6a4af574.png">
