### ISSUE TITLE
Add version information to findings metadata

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#412]
**Motivation**
Including cloudbeat and policy versions in the findings will help us in the debug process.

**Definition of done**

What needs to be completed at the end of this task
- [ ] Cloudbeat version is included in the findings
- [ ] Rego Policy version is included in the findings
- [ ] Both semantic versions and commit SHA

**Comment by kfirpeled** [comment]
Can we add also the kubernetes version?

**Comment by oren-zohar** [comment]
Verified
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/85433724/205764538-b240f32c-f72b-4f02-8877-fb82be7e194f.png">
