### ISSUE TITLE
[BUG] Cloudbeat fails to fetch k8s objects on Kubernetes v1.25

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#424]
**Describe the bug**
When deploying Cloudbeat / elastic agent on Kubernetes v1.25 k8s objects are failed to be fetched.
According to the logs
"Failed to list *v1beta1.PodSecurityPolicy: the server could not find the requested resource"

According to Kubernetes documentation [PSP is deprecated and removed in v1.25](https://kubernetes.io/blog/2022/08/25/pod-security-admission-stable/)

**Preconditions**
Upgrade kind tool to version 0.15+ ([version releases](https://github.com/kubernetes-sigs/kind/releases))
Starting from version 0.15 the default kubernetes version is v1.25

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Create kind cluster by executing just command: `create-kind-cluster`
2. Deploy elastic agent / cloudbeat
3. Verify that all object types are fetched

**Expected behavior**
Process, file and k8s objects are fetched

Logs are attached:
[elastic-agent-sqxvd.log](https://github.com/elastic/cloudbeat/files/9674178/elastic-agent-sqxvd.log)

**Desktop (please complete the following information):**
 - Kibana Version: Version 8.5 BC-1
 - Endpoint Version: Elastic Agent 8.5 BC-1

**Comment by gurevichdmitry** [comment]
@oren-zohar other resources are collected but I didn't checked if count is correct.

**Comment by oren-zohar** [comment]
_update_ per @ofiriro3 it still collects other k8s objects

**Comment by oren-zohar** [comment]
as the first step in our way to address this issue, we should start by documenting the relevant supported Kubernetes version in the documentation page @tinnytintin10 @tehilashn

**Comment by ofiriro3** [comment]
Hi,

I tried to deploy our agent on the staging environment using my Kind cluster and I see no K8s findings.

Environment details:
**ELK**
- Kibana : SNAPSHOT-8.6 commit: `8094003b4664dbb5c802d90d3e1bda7422327d1f`
Stack environment - https://staging.found.no/home
- Integration 1.0.6
- build: cc550b3c804ed70441e7d537796ebad2c640d7a6


**Kind** 
```
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.2
```

**Comment by oren-zohar** [comment]
@ofiriro3 do you see any relevant logs?

**Comment by tinnytintin10** [comment]
https://github.com/elastic/security-docs/pull/2707

@oren-zohar I created this PR in the security docs adding the supported k8s version in the FAQ section for KSPM. can you review for accuracy? thanks

**Comment by tinnytintin10** [comment]
> as the first step in our way to address this issue, we should start by documenting the relevant supported Kubernetes version in the documentation page @tinnytintin10 @tehilashn

@oren-zohar, this has been completed via the PR above. The relevant supported Kubernetes versions is being tracked in our documentation page in the FAQ section https://www.elastic.co/guide/en/security/current/kspm-faq.html#_kubernetes_clusters ✅
