### ISSUE TITLE
[BUG] After changing agent logging level using Fleet UI, cloudbeat failing to increase log level.

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#428]
**Describe the bug**
After changing agent logging level using Fleet UI, cloudbeat failing to increase log level.

The following message appears in the agent's log:
`[elastic_agent][error] cloudbeat stderr: "failed to IncreaseLevel: invalid increase level, as level \"info\" is allowed by increased level, but not by existing core\n"`

**Preconditions**
ELK stack is deployed
Vanilla kubernetes cluster is deployed
Elastic fleet managed agent is deployed and connected

**To Reproduce**
1. Navigate to Fleet UI
2. Select connected agent
3. Select logs tab
4. Change agent's logging level to **warning** for example
5. Apply changes

**Expected behavior**
Cloudbeat changes notification level and notifies that logging level is changed.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Kibana Version: 8.5-BC1
 - Endpoint Version: 8.5-BC1

**Comment by amirbenun** [comment]
After the fix https://github.com/elastic/cloudbeat/pull/490, in order to enable decision logs you will also have to run cloudbeat on debug log level.

**Comment by CohenIdo** [comment]
QA cycle test for 8.7.0 BC6 covered [here](https://github.com/elastic/cloudbeat/issues/600)
