### ISSUE TITLE
[BUG] EKS integration - cloudbeat does not crash when updating with bad credentials

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#444]
**Describe the bug**

When providing bad credentials to EKS, cloudbeat does not crash as expected.
Instead, it logs the following:

`
[elastic_agent.cloudbeat][error] Failed to update Beater config: could not create beater: could not retrieve user identity for ECR fetcher: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: d132180b-670e-4895-961e-0d8fba171f69, api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
`

**Preconditions**
Running 8.5.0-latest and eks deployment (containing two nodes) ready for use

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Set up kspm-eks integration in kibana with proper aws credentials (ACCESS_KEY+SECRET)
2. Deploy the elastic-agent
3. Wait for first results
4. Add '@' character in end of the SECRET
5. Save and deploy
6. Check the logs/ verify if cloudbeat crashes

**Expected behavior**
Cloudbeat should crash

**Additional context**
 - Kibana Version: 8.5.0 BC2 dc769f45a5a6dafb0a8c8f0c0cabcced4df45e11
 - elastic-agent version: BC2 elastic-agent:8.5.0-ca5dd693
 - https://github.com/elastic/cloudbeat/issues/388

**Comment by oren-zohar** [comment]
need to verify three cases:
- [ ] no credentials are provided
- [ ] invalid credentials are provided
- [ ] credentials with not enough privileges are provided 

all should match our docs.

@olegsu can you please take it as part of the QA Cycle?

**Comment by olegsu** [comment]
## No credentials
When no credentials are provided cloudbeat will use the ec2 attached IAM role and try using it when calling AWS APIs.
This means that it will continue reporting events based on the permissions it has (files, processes, k8s)

<img width="2546" alt="image" src="https://user-images.githubusercontent.com/23185631/195087644-dba06196-3b72-4f9d-a60c-a7643cb706d5.png">


## Update VS New Agent
The cloud beat crash depends on whether the configuration was invalid ( or wrong ) at the beginning or streamed from Kibana.
When the configuration is invalid when the cloudbeat starts, it will write an error to the log and [return](https://github.com/elastic/cloudbeat/blob/main/launcher/launcher.go#L129) it, which will cause the crash at the end (after 2 min approximately )
The error: `could not create beater ....`

When the wrong configuration was a result of an update through Kibana, cloudbeat will write the error to the log and will **not** crash (https://github.com/elastic/cloudbeat/blob/main/launcher/launcher.go#L177)
The error: `Failed to update Beater config....`

**Comment by gurevichdmitry** [comment]
verified in version 8.6.0-BC 9 (kibana commit: 93183bddac40f8a7ee8e566d1651f9f3b586a520) - fixed.
