### ISSUE TITLE
Document Cloudbeat missing kube permissions cases

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#471]
**Summary**
It's possible that the user will deploy cloudbeat without the required permissions (by editing the deployment manifest). We need to verify that we ship the relevant logs from the kube API into the agent logs, and that they make sense. 
We also need to document this case and the expected logs in our internal docs.

**Comment by gurevichdmitry** [comment]
Task Progress:
Deployment manifest has critical sections related to our product. Changes in these sections may directly lead to missing findings data. 
After initial investigation the following sections/components were modified:

- ClusterRole resource ( influences on k8s object findings)
    -  serviceaccounts rules
       <img width="400" alt="Screen Shot 2022-11-06 at 15 46 27" src="https://user-images.githubusercontent.com/99176494/200174450-5732489b-418d-4cf2-a038-1d918dc67f9b.png">

    - rbac.authorization (roles, cluster roles)
       <img width="420" alt="Screen Shot 2022-11-06 at 15 48 17" src="https://user-images.githubusercontent.com/99176494/200174543-8d42485f-e6aa-4fbe-ad0d-4ea55aa8c889.png">

    - policy (pod security policies)
       <img width="374" alt="Screen Shot 2022-11-06 at 15 49 29" src="https://user-images.githubusercontent.com/99176494/200174590-9aef8a74-ee44-478f-a0fd-bffa7eabe2a4.png">

- DaemonSet (influences on file and process findings)
    - Volume Mount 
       <img width="516" alt="Screen Shot 2022-11-06 at 15 50 53" src="https://user-images.githubusercontent.com/99176494/200174733-89b10bd0-285e-48e2-9231-85be003b349f.png">

The results of removing each critical section are documented in the table below:
| Resource Kind| Missing Permission  | Expected Log | Comments |
| ------------- | ------------- |-------------|---------------|
| ClusterRole   | serviceaccounts| [elastic_agent.cloudbeat][error] Error running fetcher for key kube-api: fetcher kube-api reached a timeout after 60 seconds [elastic_agent][error] cloudbeat stderr: "W1106 10:36:34.896677    1721 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User \"system:serviceaccount:kube-system:elastic-agent\" cannot list resource \"serviceaccounts\" in API group \"\" at the cluster scope\nE1106 10:36:34.896719    1721 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.ServiceAccount: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User \"system:serviceaccount:kube-system:elastic-agent\" cannot list resource \"serviceaccounts\" in API group \"\" at the cluster scope\n"|           |
|ClusterRole|roles|[elastic_agent][error] cloudbeat stderr: "W1106 10:54:35.261451    4748 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1.Role: roles.rbac.authorization.k8s.io is forbidden: User \"system:serviceaccount:kube-system:elastic-agent\" cannot list resource \"roles\" in API group \"rbac.authorization.k8s.io\" at the cluster scope\nE1106 10:54:35.261483    4748 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Role: failed to list *v1.Role: roles.rbac.authorization.k8s.io is forbidden: User \"system:serviceaccount:kube-system:elastic-agent\" cannot list resource \"roles\" in API group \"rbac.authorization.k8s.io\" at the cluster scope\n"||
|ClusterRole|policy|[elastic_agent][error] cloudbeat stderr: "W1106 11:13:09.301779    5181 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PodSecurityPolicy: podsecuritypolicies.policy is forbidden: User \"system:serviceaccount:kube-system:elastic-agent\" cannot list resource \"podsecuritypolicies\" in API group \"policy\" at the cluster scope\nE1106 11:13:09.301816    5181 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PodSecurityPolicy: failed to list *v1beta1.PodSecurityPolicy: podsecuritypolicies.policy is forbidden: User \"system:serviceaccount:kube-system:elastic-agent\" cannot list resource \"podsecuritypolicies\" in API group \"policy\" at the cluster scope\n"||
|DaemonSet|mount files|None|Depends on missing volume mount, count of findings is changed and there are no logs notifying about missing mounts |

Summarizing the investigation, when there is a problem with Cluster Role resource fields, Cloudbeat notifies with general error about a problem on running fetcher for key kube-api, and on elastic agent's level more specific message is provided (policy / account / role). Note that any problem with one of kube-api resources will lead to absence of **all** kube-api findings.
In case of volume mount issue, there is no notification through logs, and the way to understand the issue with files and process is through comparing current finding results of file and process to expected results for version 8.x.

@kfirpeled, @oren-zohar, @eyalkraft fyi.

**Comment by eyalkraft** [comment]
Amazing work @gurevichdmitry !

> In case of volume mount issue, there is no notification through logs, and the way to understand the issue with files and process is through comparing current finding results of file and process to expected results for version 8.x.

@oren-zohar sounds like we would like to log these cases as well right?
