### ISSUE TITLE
cloudbeat CLI - `ccli`

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#487]
```
 .d8888b.  888                        888 888                        888         .d8888b.  888      8888888
d88P  Y88b 888                        888 888                        888        d88P  Y88b 888        888  
888    888 888                        888 888                        888        888    888 888        888  
888        888  .d88b.  888  888  .d88888 88888b.   .d88b.   8888b.  888888     888        888        888  
888        888 d88""88b 888  888 d88" 888 888 "88b d8P  Y8b     "88b 888        888        888        888  
888    888 888 888  888 888  888 888  888 888  888 88888888 .d888888 888        888    888 888        888  
Y88b  d88P 888 Y88..88P Y88b 888 Y88b 888 888 d88P Y8b.     888  888 Y88b.      Y88b  d88P 888        888  
 "Y8888P"  888  "Y88P"   "Y88888  "Y88888 88888P"   "Y8888  "Y888888  "Y888      "Y8888P"  88888888 8888888
```

**Motivation**

We wish to have better productivity tooling than what we have today.

**Definition of done**

- [ ] Skeleton of ccli
- [ ] Include one dummy command as an example with arguments
- [ ] Include documentation for the command
- [ ] Include auto-completion for the command
- [ ] Include tests for the dummy command

**Out of scope**

- Migrate existing command into the cli

**Related tasks/epics**

- https://typer.tiangolo.com/
- https://cobra.dev/
- https://github.com/elastic/observability-test-environments/tree/main/tools/oblt_cli
- https://studious-disco-k66oojq.pages.github.io/tools/oblt-cli/
- https://github.com/elastic/ecctl
- https://github.com/elastic/beats/tree/main/libbeat/cmd

**Commands**
- https://github.com/elastic/cloudbeat/issues/524
- https://github.com/elastic/cloudbeat/issues/528
- https://github.com/elastic/cloudbeat/issues/527
- https://github.com/elastic/cloudbeat/issues/526
- https://github.com/elastic/cloudbeat/issues/549

**Comment by kfirpeled** [comment]
**Suggesting structure of new commands:**

`ccli build cloudbeat` -- builds cloudbeat
`ccli build agent --agent-base 8.6.0-abc123` -- builds agent image containing local cloudbeat based on specific agent image
`ccli deploy cloudbeat --context kind-mono` -- deploys cloudbeat on given context
`ccli deploy cloudbeat --build` -- builds and deploys cloudbeat on current context
`ccli deploy agent` -- deploys agent image
`ccli deploy cloud` -- deploys agent on cloud (see [apm-server example](https://github.com/elastic/apm-server/tree/main/testing/cloud))
`ccli test cloudbeat --suite functional` -- runs functional test suite for cloudbeat
`ccli test cloudbeat --suite integration` -- runs integration test suite for cloudbeat
`ccli test agent --suite eks:functional` -- runs EKS functional test suite for agent

Alternative for deployment, using run/stop (similar experience when using `elastic-package stack up`)
`ccli run cloudbeat --config eks --context kind-mono` -- runs cloudbeat configured with EKS fetchers and rules on kind-mono context
`ccli stop cloudbeat --context kind-mono` -- tears down cloudbeat from kind-mono
`ccli run cloudbeat --config self-managed -d` -- deploys cloudbeat on current context with self managed fetchers and config in the background (-d)

**What we should stop doing** 
`ccli builddeploycloudbeat`
`ccli builddeployagent`


**NOTE: in these examples `ccli` is just a code name, it can be `mage` or CLI program that we manage**

**Comment by kfirpeled** [comment]
Attaching a skeleton using cobra https://github.com/kfirpeled/stringer

**Comment by oren-zohar** [comment]
:(
