### ISSUE TITLE
Test index creation when using non default spaces and namespaces 

### ISSUE THREAD

**Issue by CohenIdo** [elastic/cloudbeat#494]
While our Findings index suffix always uses `-default`, the suffix of data streams indicates what namespace it uses. 

Furthermore, Kibana spaces are used to organize dashboards and other saved objects into meaningful categories. Since our rule templates are saved in one space, but can be used in another, this also may cause bugs. 

In this task we will install KSPM in different scenarios to verify its behavior in this task

**Comment by CohenIdo** [comment]
Bug was found - Findings page is not avliable while the dashboard is valid. 
Steps to reproduce: 
1. In default space - Install KSPM integration on agent policy 1 (not needed to add agent).
2. Change space - Install KSPM integration on another agent policy and add agent.  


* [environment](https://test-spaces.kb.us-west2.gcp.elastic-cloud.com:9243/s/testspace/app/home#/) creds: `elastic` `8M2tOhPwozKGUy0Vs5GrKauV`
![Image](https://user-images.githubusercontent.com/90558359/200521215-a60967f2-1b83-4d7a-9472-2f46d97979e9.png)



![Image](https://user-images.githubusercontent.com/90558359/200521287-c3edab3c-e202-46df-a3b6-b6077cd54b2d.png)

**Comment by CohenIdo** [comment]
Following the previous test senario after one cycle the agent become offline, when I checked the cloudbeat logs the following error reapted: 
```
[elastic_agent][error] cloudbeat stderr: "W1108 09:26:29.851512    1776 reflector.go:324] k8s.io/client-
go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PodSecurityPolicy: the server could not find the requested 
resource\nE1108 09:26:29.851674    1776 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to 
watch *v1beta1.PodSecurityPolicy: failed to list *v1beta1.PodSecurityPolicy: the server could not find the requested 
resource\n"
```

The full logs can be found [here](https://test-spaces.kb.us-west2.gcp.elastic-cloud.com:9243/s/testspace/app/fleet/agents/1e18039a-b403-4338-aac7-3edace51ea75/logs)

**Comment by JordanSh** [comment]
Only difference between the dashboard and findings are the data source
the dashboard gets data from es, but findings from data view.
as we saw at our daily today, the data view is missing in one of the spaces, probably because we set it only during integration installation.

**Comment by CohenIdo** [comment]
Bug was [created](https://github.com/elastic/security-team/issues/5377), closing this issue.
