### ISSUE TITLE
New `build` cobra command

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#524]
**Motivation**
As part of our effort to improve development productivity, we are redesigning the build command.
This is the first phase of the build command

```sh
> ccli build cloudbeat -o dist
```

**Commands**
build (main build command)
build cloudbeat (subcommand)

**Optional Flags**
--output, -o       destination folder (default `dist`)
--os                    target os (default is all support os)
--arch                 target arch (default is all supported arch)

**Output**
Outputs different cloudbeat processes in the following pattern: `cloudbeat-{{os}}-{{arch}}` to the output directory
- `cloudbeat-linux-amd64`
- `cloudbeat-linux-arm64`
- `cloudbeat-darwin-amd64`
- `cloudbeat-darwin-arm64`

**Definition of done**
- [ ] Introduce new build command under `cmd/build.go`
- [ ] Introduce command tests under `cmd/build_test.go`
- [ ] Add tests to CI
- [ ] CI should use the new build command
- [ ] Justfile should use the new build command

**Out of scope**
- agent build
- packaging

**Related tasks/epics**
- #487

**Comment by oren-zohar** [comment]
What about the `type` flag? i.e. docker, tar, binary, etc?

**Comment by kfirpeled** [comment]
use `strings XXX | grep GOARCH` and `strings XXX | grep GOOS` to check if the built binary was built correctly
