### ISSUE TITLE
Decision logs should appear properly on fleet UI logs screen

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#533]
**Motivation**
The fleet UI shows only selected fields of every log message.
As a result, decision logs don't expose any important information.
![image](https://user-images.githubusercontent.com/34831306/203295869-c89c7214-3513-4c13-8f8e-f2aaa83b27a8.png)

**Definition of done**
- [ ] Modify the CSP integration and add the required decision log fields to be present on the fleet UI log screen

**Related tasks/epics**
- https://github.com/elastic/cloudbeat/issues/416

**Comment by olegsu** [comment]
This is how it printed to the console.
I was unable to verify this in the console. 
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/23185631/218529288-a429e570-798d-4256-b4ab-d596ec42c15a.png">

Two issues I think might be here that are related to the issue
1. `cloudbeat.evaluator.decision_logs` is not part of the policy that was sent to the agent (which is false by default) so I am not sure not it been printed.  
<img width="460" alt="image" src="https://user-images.githubusercontent.com/23185631/218526607-0a2dd4cf-621b-499f-9f1d-c39c89c10168.png">
2. Although the log level has been changed in the agent UI to debug, no debug option is been shown in the drop-down<img width="955" alt="image" src="https://user-images.githubusercontent.com/23185631/218527192-d7809427-5f36-4766-a0c5-98d6aebb0550.png">

**Comment by amirbenun** [comment]
Thanks @olegsu
We decided to deprecate the `cloudbeat.evaluator.decision_logs` flag. Instead, decision logs will be sent in debug mode.
