### ISSUE TITLE
Implement an AWS CloudWatch Provider

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#537]
**Motivation**
Create a fetcher to collect the CloudWatch data to be evaluated by OPA.

**Definition of done**
What needs to be completed at the end of this task
- [ ] All the relevant CloudWatch data is collected.
- [ ] Fetcher's implementation is provider agnostic.

**Related tasks/epics**
- https://github.com/elastic/csp-security-policies/issues/148

**Comment by olegsu** [comment]
Closed part of https://github.com/elastic/csp-security-policies/issues/148
