### ISSUE TITLE
Implement an AWS Network fetcher

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#543]
**Motivation**
Create a fetcher to collect VPC data to be evaluated by OPA.

**Definition of done**
What needs to be completed at the end of this task
- [ ] use defsec 3rd party to fetch the data from the AWS account. 
- [ ] All the required VPC data is collected.
- [ ] Fetcher's implementation is provider agnostic.

**Related tasks/epics**
- https://github.com/elastic/csp-security-policies/issues/149 probably

**Comment by olegsu** [comment]
Rules to implement
- [x] 5.1 Ensure no Network ACLs allow ingress from 0.0.0.0/0 to remote server administration ports 
- [ ] 5.2 Ensure no security groups allow ingress from 0.0.0.0/0 to remote server administration ports
- [ ] 5.3 Ensure no security groups allow ingress from ::/0 to remote server administration ports
- [ ] 5.4 Ensure the default security group of every VPC restricts all traffic
