### ISSUE TITLE
New `mock` cobra command

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#549]
**Motivation**
As part of our effort to improve development productivity, we are redesigning the build command.
This is the first phase of the build command

```sh
> ccli mock findings --host localhost:9200
```

**Commands**
mock (main mock command)
mock findings (subcommand)

**Optional Flags**
```bash
--host, -h        target elasticsearch host (default `localhost:9200`)
--index, -i       target index name (default `logs-cloud_security_posture.findings`)
```

**Output**
Using OPA and mocked resources, it will evaluate them against the latest bundle and send the findings to the target ES.

**Definition of done**
- [ ] Introduce new build command under `cmd/mock.go`
- [ ] Introduce command tests under `cmd/mock_test.go`
- [ ] Add tests to CI

**Out of scope**

**Related tasks/epics**
- #487

**Comment by oren-zohar** [comment]
@orouz @kfirpeled fyi

**Comment by eyalkraft** [comment]
maybe `ccli mock findings` instead of `ccli mock --findings`

**Comment by orouz** [comment]
> I've recently heard there are tools in kibana that do exactly that

@kfirpeled can you elaborate? if there's an existing tool that would be perfect. i'm just not sure how will it know what Findings to index, as opposed to `cloudbeat` which does.
