### ISSUE TITLE
Cloudbeat fail due to fatal

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#553]
**Describe the bug**
Cloudbat enters a crash loop-back after continuously receiving new configurations from fleet server. This leads to continuous restarting of the fetching cycle and shipping lots of findings.

Relevant logs:
```
[elastic_agent.cloudbeat][info] Got config update from fleet with 59 keys
...
[elastic_agent.cloudbeat][fatal] Failed due to panic.
```

**Preconditions**
8.6.0 BC3

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Deploy 8.6.0 BC3 agent with KSPM configured
2. Go to the agent logs

 - OS: linux
 - Arch: and64 
 - Agent Version: 8.6.0 BC3
 - Cloudbeat Version:  8.6.0 BC3
 - Kibana Version: 8.6.0 BC3

**Comment by cmacknz** [comment]
The underlying bug here should be fixed in agent, have you confirmed this is fixed in Cloudbeat?

**Comment by oren-zohar** [comment]
Yes the issue is solved @cmacknz
