### ISSUE TITLE
update expected findings for 8.6.0

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#566]

**Comment by CohenIdo** [comment]
**EKS multi node:**
- k8s_object -> 74 findings as expected ✅ 
- process -> 22 findings as expected ✅ 
- file -> 60 findings as expected ✅ 
- loadBalancers ✅

Regarding ecrImages resource type, I pushed images to ecr and not see any finding from [rule 5.1.1](https://docs.elastic.dev/security-solution/cloud-security-posture/expected-findings#aws-eks-benchmark) @oren-zohar

**Comment by ofiriro3** [comment]
Sounds about right.

If you would like to see findings for the `ecr` type you'll need to deploy a private ecr image to your cluster - I can help if needed 👍
