### ISSUE TITLE
Send cloudbeat logs to shared environemnt

### ISSUE THREAD

**Issue by CohenIdo** [elastic/cloudbeat#570]
**Motivation**
Our ability to receive logs from customers' deployments is useful in a variety of ways:
1. Analyze issues raised by customers without requesting logs.
2. We can monitor cloudbeat behavior and find bugs before users experience them by having a centralized dashboard with all cloudbeat logs (info/warning error).

It's seems that part of the beats are already sending [there logs](https://overview.elastic-cloud.com/s/platform-ingest/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(message,agent.id,service.name,log.logger),filters:!(),index:'66396b74-4210-4ee5-ba24-b4dffb5fbe98',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))): 
> <img width="2468" alt="image" src="https://user-images.githubusercontent.com/90558359/206144119-1506af35-1ea2-423e-a20d-4b3a6b46983a.png">

[Here](https://overview.elastic-cloud.com/s/cspm/app/r/s/Vly71) we can see the power of having centralized Kibana logs dashboard
> <img width="2548" alt="image" src="https://user-images.githubusercontent.com/90558359/206143678-47226f0c-4ead-4caf-a571-db47bed90359.png">

**Definition of done**
What needs to be completed at the end of this task
- [ ] Receiving cloudbeat logs from any deployment to one remote environment. 

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by CohenIdo** [comment]
cc: @kfirpeled

**Comment by oren-zohar** [comment]
According to what I understand, users' Kibana and metadata logs are collected by Filebeat, which runs on their cluster's hosted agent. Logs from beats that run on user-deployed agents cannot be collected. Moreover, there might be legal issues associated with collecting all of these logs from the beats running on user-deployed agents. As a result, collecting cloudbeat logs from deployed user agents will also face the same issues and will not be supported by the Elasticsearch/Kibana platform as well. @CohenIdo
