### ISSUE TITLE
Define and implement resource metadata for CSPM finding

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#586]
**Motivation**
We need to have a clear definition of how resource metadata for CSPM findings looks like. This is required for user interactions with the data in Kibana.

**Definition of done**
Define and implement the following:
- [ ] Logic to create resource IDs
- [ ] Definition of resource types/subtypes
- [ ] Additional metadata fields:
  + Indicator of whether this is CSPM finding or not
  + Cloud provider name (e.g. GCP, AWS)
  + Account name
  + Account ID
  + ARN
- [ ] Document thoroughly in our technical index each and every field and it's contents for every new resource type

  
Metadata should be as compliant to ECS as possible, and ECS can help us find more useful metadata we can ship

**Comment by oren-zohar** [comment]
can we push this to 8.8 or do you think this is critical for 8.7?

**Comment by ari-aviran** [comment]
This is a must for 8.7 for the basic experience

**Comment by oren-zohar** [comment]
this also means updating the script to support the new format

**Comment by ari-aviran** [comment]
> this also means updating the script to support the new format

@oren-zohar what script is that?

**Comment by oren-zohar** [comment]
https://github.com/elastic/csp-security-policies/tree/main/cis_policies_generator

**Comment by kfirpeled** [comment]
> Indicator of whether this is CSPM finding or not
> Cloud provider name (e.g. GCP, AWS)

Regarding these two values, we do pass them in the agent policy.

**References**
https://github.com/elastic/integrations/blob/main/packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
```yaml
config:
  v1:
    posture: {{posture}}
    deployment: {{deployment}}
    benchmark: cis_aws
```

**Comment by uri-weisman** [comment]
What have we decided regarding the posture (CSPM/KSPM) attribute?
1. Will it be propagated by the agent policy to Cloudbeat's findings?
2. Will be part of the rule metadata?
3. Maintains a benchmark id - posture mapping in Kibana?

Option **2** makes more sense to me and requires minor changes in the generator script.

**Comment by oren-zohar** [comment]
@uri-weisman I agree. Just take into account that it will require editing cloudbeat to support the new field, and adding a mapping for it in the integration.

**Comment by uri-weisman** [comment]
I've opened a ticket for this task: https://github.com/elastic/security-team/issues/5732
