### ISSUE TITLE
Publish findings failed on bulk index operation

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#587]
**Describe the bug**
The following logs:
```
00:02:15.612 [elastic_agent.cloudbeat][error] failed to perform any bulk index operations: Post "https://a2d1c538822d46f290f0dc04bb29cdd9.us-west2.gcp.elastic-cloud.com:443/_bulk": EOF
00:02:17.470 [elastic_agent.cloudbeat][error] failed to publish events: Post "https://a2d1c538822d46f290f0dc04bb29cdd9.us-west2.gcp.elastic-cloud.com:443/_bulk": EOF
```

**Preconditions**
On an elastic cloud environment 8.6.0-SNAPSHOT.

**To Reproduce**
1. Local Kind cluster
2. Laptop is closed for a while (?)
3. The bug is not consistent, I see findings from 10 hours ago ( when the period is 4h).

**Expected behavior**
All findings should be successfully indexed in elasticsearch

**Comment by oren-zohar** [comment]
It won't reproduce on EC2 so I'm closing this
