### ISSUE TITLE
Support multi region for CIS AWS integration

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#592]
**Issue:**
Currently, we assume that the agent will be deployed on an EC2 instance and based on that collect the resources from the machine's region, bounds us only to a single region.

**Motivation:**
According to @tinnytintin10 
Fetching and evaluating resources from only a specific region is not ideal and falls short of the goal of the CSPM product we're building, enumerating and evaluating all relevant AWS resources for conformance to the rules in the [CIS AWS Foundations Benchmark v1.5.0](https://github.com/elastic/security-team/files/9603210/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.5.0.pdf). 

**DOD:**
Fetch and evaluate resources in all regions. 
From a UX/UI perspective, the user doesn't need to provide any region.

**Comment by uri-weisman** [comment]
Implementation details:

1. Maintain regions mapping for each cloud service.
2. In every provider's construction generate a list of clients according to the mapping.
3. In the provider code invoke each initialized client in a new go routine to perform its API calls.



A simple pseudo-code:
```
// regions.go
"aws-iam": ["us-east-1", "eu-west-2"]


// iam.go
func NewIAMProvider(log *logp.Logger, cfg aws.Config) *Provider {
	var clients []Client
	for _, region := range regions.IAMType {
		cfg.Region = region
		clients = append(clients, iamsdk.NewFromConfig(cfg))
	}
	
	return &Provider{
		log:    log,
		clients: clients,
	}
}


// iam_provider.go
func (p Provider) GetUsers(ctx context.Context) ([]awslib.AwsResource, error) {
    var users []User
    var wg sync.WaitGroup
    for _, client := range p.clients {
        wg.Add(1)
        go func(client string) {
            defer wg.Done()
            result, err := client.ListUsers(nil)
            users = append(users, result.Users)
        }(client)
    }
    wg.Wait()
    return users
}
```

@elastic/cloudbeat  - would appreciate your feedback

**Comment by eyalkraft** [comment]
@uri-weisman How does the region configured for the client effects the collected resources?

In your example you list IAM users, which are global (region-less) entities. So I'm not sure why you'd need multiple clients. Seems like [ListUsers](https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListUsers.html) will just return all existing users.

I think we first have to map which resources could be listed in a global manner? (IAM Users for example, possibly [S3 buckets](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListBuckets.html#API_ListBuckets_ResponseSyntax), other resources).

For the resources that couldn't be listed in a global matter, I think we can think of some optimizations but your suggestion could be a good (naive) starting point.

**Comment by eyalkraft** [comment]
I remember we’ve known [AWS Config](https://aws.amazon.com/config/) for a while but I now wonder if it could have been/would be useful for CSPM.

[Check out](https://docs.aws.amazon.com/config/latest/APIReference/Welcome.html) the multi-regional discovery capabilities.

**Comment by uri-weisman** [comment]
Thanks @eyalkraft.
Yeah you're right IAM is a global service, it was only a simple example (probably not the best one).
According to the CIS benchmark (p5), the relevant services are:

• AWS Identity and Access Management (IAM) - Global
• IAM Access Analyzer - Regional
• AWS Config - Regional
• AWS CloudTrail - Global
• AWS CloudWatch - Regional
• AWS Simple Notification Service (SNS) - Regional
• AWS Simple Storage Service (S3) - Global
• Elastic Compute Cloud (EC2) - Regional
• Relational Database Service (RDS) - Regional
• AWS VPC - Regional

For efficiency purposes, I tried to figure out how can I pick only active regions with services' resources.
Not the result that I was hoping for but I was able to find how to list the Regions that are enabled for the client's AWS account [(ec2 - DescribeRegions)](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.DescribeRegions).
Error handling in this flow should be descriptive and comprehensive as we need to differentiate between a failed request to a valid region vs an unsupported service region.

IMO it can be a good start - wdyt?

**Comment by eyalkraft** [comment]
> IMO it can be a good start - wdyt?

Agreed. I suspect It will result with a lot of redundant API calls as users might have regions enabled and not used. But this is good enough as a start.
Also the doc you linked for [(ec2 - DescribeRegions)](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.DescribeRegions) is pretty ambiguous:
> Describes the Regions that are enabled for your account, **or all Regions**.

Reading more about AWS config I've also opened https://github.com/elastic/security-team/issues/5721 for us to evaluate if it could be a future alternative solution.

**Comment by uri-weisman** [comment]
> Also the doc you linked for [(ec2 - DescribeRegions)](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.DescribeRegions) is pretty ambiguous:
> 
> > Describes the Regions that are enabled for your account, **or all Regions**.

I think they are referring to the [AllRegions](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#DescribeRegionsInput) field.

**Comment by tinnytintin10** [comment]
++ let's send this information

**Comment by tehilashn** [comment]
@oren-zohar - do we have a task to track this?

**Comment by ari-aviran** [comment]
> @oren-zohar - do we have a task to track this?

@tehilashn 
https://github.com/elastic/cloudbeat/issues/745
