### ISSUE TITLE
update cloudbeat's libs to fix the logging issue

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#600]
**Motivation**

Following v2 changes, the log level wasn't propagated correctly to the beats. following their fix we need to do the following:

**Definition of done**
- [ ] Update the beats lib and agent lib to support the fix
- [ ] Test and confirm that the fix is working
- [ ] Backport to 8.6

**Comment by CohenIdo** [comment]
qa cycle update:
- cloudbeat process not killed once we change log level.
- cloudbeat flow is restarted and sends new findings.
- I changed first the log level to warning and the change works.
 Than I changed the log level to debug and the logs not showing up in Kibana anymore. When I ssh to cloudbeat and l found that there are logs:


![Image](https://user-images.githubusercontent.com/90558359/209987123-41987242-7850-4dcf-8219-a0653631c6e3.png)



![Image](https://user-images.githubusercontent.com/90558359/209987150-593f4017-48e0-48e6-ad10-46358e5bb65d.png)

- it seems that any of the beats sends debug logs: 


![Image](https://user-images.githubusercontent.com/90558359/209987618-d32dbc0c-8a42-4519-a32a-9afb4083b157.png)


- in addition there are messages that arrives from cloudbeat without any log level. 
I checked that with @oren-zohar and he found that those message [added months](https://github.com/elastic/cloudbeat/pull/271/files) ago but we see them now first.


![Image](https://user-images.githubusercontent.com/90558359/209987412-0b7c498c-bef2-4eeb-8257-0344e6ead190.png)

**Comment by CohenIdo** [comment]
Second check: When changing for debug log, it changes on cloudbeat, but the debug logs don't arrive in Kibana

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/90558359/209996198-1a826c23-fbe7-4e36-83e5-003a3b4bd48f.png">

![Uploading image.png…]()

**Comment by CohenIdo** [comment]
- https://github.com/elastic/cloudbeat/issues/623
