### ISSUE TITLE
Ensure cloudbeat can access AWS using default EC2 attached role

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#604]
**Motivation**
Ensure cloudbeat can access AWS using the default EC2 attached role with no creds or role ARN (or anything) configured through the integration policy

- [ ] Remove the credentials override from our codebase
- [ ] Verify it works with our CloudFormation script
- [ ] Verify it uses the fallback resolver on a local machine

**Comment by oren-zohar** [comment]
Not working on EC2 out of the box will be handled here. Closing

**Comment by amirbenun** [comment]
Reopened as the duplicate task didn't cover working with the cloudformation deployment but rather any EC2 instance.
This task will be focused on testing the attached role and the permissions it has.

**Comment by JordanSh** [comment]
verified 



![Image](https://user-images.githubusercontent.com/51442161/236678044-8e330df9-2481-41e9-833b-203e1dd518c0.png)
