### ISSUE TITLE
Define and add support new input type

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#608]
**Summary**

- [x] Define new input type 
- [ ] Add type to the configuration
- [x] Add support to cloudbeat (new flow based on the new type)
- [x] Add new input type to [spec file](https://github.com/elastic/elastic-agent/blob/main/specs/cloudbeat.spec.yml)

**Suggested:** `cloudbeat/vuln_mgmt_aws`

**Comment by amirbenun** [comment]
We still cannot test the integration as Cloudbeat fails the package step.
A fix in beats repo: https://github.com/elastic/beats/pull/34723

**Comment by amirbenun** [comment]
Some dependencies could not get tracked by the go-license-detector.
Here is a PR https://github.com/elastic/go-licence-detector/pull/21.
Once merged, I will open a PR to the beats repo to update it and later to cloudbeat.

**Comment by amirbenun** [comment]
A new PR was opened to beats in order to override the undetected repository.
https://github.com/elastic/beats/pull/34902

**Comment by amirbenun** [comment]
Validated with `8.8.0-SNAPSHOT`.
