### ISSUE TITLE
Add non-SSL deployment option

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#618]
**Motivation**
As a kibana developer, working locally does not require any SSL setup

Ever since elastic-package moved to secure all the pieces: elasticsearch, kibana, package-registry, fleet & agent. Moving cloudbeat's deployment to support that, broke the kibana's developers experience.

The simplest solution for them is to allow cloudbeat deployment without using elastic-package certificates

**Comment by kfirpeled** [comment]
Currently, by removing the ssl patch

```diff
- patches:
-   - path: ./patches/patch-add-ssl-certs.yaml
-     target:
-       kind: DaemonSet

- secretGenerator:
-   - behavior: create
-     name: elastic-package-certs
-     files:
-       - ./ca-cert.pem
```

and removing the certificate handling from `just deploy-cloudbeat` command:

```diff
deploy-cloudbeat:
-  cp {{env_var('ELASTIC_PACKAGE_CA_CERT')}} {{kustomizeVanillaOverlay}}
-  kubectl delete -k {{kustomizeVanillaOverlay}} -n kube-system & kubectl apply -k {{kustomizeVanillaOverlay}} -n kube-system
-  rm {{kustomizeVanillaOverlay}}/ca-cert.pem
+  kubectl apply -k {{kustomizeVanillaOverlay}} -n kube-system
```

Solves the issue, so we need to allow that kind of deployment
