### ISSUE TITLE
Terraform refactoring

### ISSUE THREAD

**Issue by olegsu** [elastic/cloudbeat#622]
**Motivation**
At the moment we have one root module with 4 sub-modules that use it
As our Terraform module grows, we need a better structure so that the user is more clear.

We should have logical modules that are doing everything that it needs
1. Elastic-Stack should include the dashboards built-in
2. EKS should be creating the package policy
3. Ec2 should be creating the package policy

DOD
- [ ] Spin up all the modules in one command
- [ ] Be able to spin up on Elastic-stack module
- [ ] All the resources have some common property ( tag, label, name prefix, etc ), we can use [random_pet](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/pet) to generate human-readable name
- [ ] Don't assume the existence of IAM policies but instead create them
- [ ] Lock down the versions of all imported modules so things won't break - specifically the apm tf module we're using
- [x] Set up ECR image pull for the vanilla cluster (See [comment](https://github.com/elastic/security-team/issues/5689#issuecomment-1376018205) for details)

**Related tasks/epics**
Tech debt ticket for https://github.com/elastic/security-team/issues/5656

**Comment by eyalkraft** [comment]
> - [ ] All the resources have some common property ( tag, label, name prefix, etc ), we can use [random_pet](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/pet) to generate human-readable name

I think currently only the resources related to the vanilla deployment lack the common prefix. random_pet looks cool.

Also adding these tasks from my last list that weren't competed yet:

> 2. Currently the script assumes the existence of the IAM policies
    ```
    Developers_eks = "arn:aws:iam::704479110758:policy/Developers_eks"
    EKS_ReadAccess = "arn:aws:iam::704479110758:policy/EKS_ReadAccess"
    ```
    A more proper way would be to have the tf script provision the required policy itself.

> 6. Lock down the versions of all imported modules so things won't break

**Comment by ofiriro3** [comment]
I think it would be nice also to add an owner tag, so we can easily track our EKS clusters/Ec2 machines

**Comment by uri-weisman** [comment]
I've encountered several quotas limits while creating a new environment.
Would be nice if we'll use existing resources if possible (NAT Gateway, VPC).

**Comment by ofiriro3** [comment]
Another gap that I think we should address is that the EC2 deployment is strongly dependent on an EKS deployment I.E you cannot currently deploy and EC2 machine without deploying an EKS cluster

**Comment by olegsu** [comment]
Require tags to keep an environment up https://elastic.slack.com/archives/C02EXA5621E/p1676300388415619

**Comment by amirbenun** [comment]
Some gaps we had during the last QA cycle that we can bridge as part of that task:
- Terraform commands should be more clear. We could have one-liner for creating the elastic stack. Then we could have more one-liners for installing eks, one-liner for vanilla, one-liner for cspm.
- Fix the documentation about how to delete cloud resources (now it appears as an inner section)
- Support env var to override elastic-agent image (As the BC is not public)

@olegsu Can I update the definition of done?

**Comment by olegsu** [comment]
Thank you @amirbenun 
> Terraform commands should be more clear. We could have one-liner for creating the elastic stack. Then we could have more one-liners for installing eks, one-liner for vanilla, one-liner for cspm.

I am not sure we will be able to achieve that, as some modules depended on elstic-cloud deployment. Does it make sense to install CSPM module without Elastic Deployment installed previously?  with stand-alone one-liners it can be done. In general, I think it's more error prune.
To support the idea of one-line installation I think we can have variables like `with-kspm-vanilla` or `with-kspm-eks` (or `without`) that will install elastic and the other components.
Does it answer your use case?

> Fix the documentation about how to delete cloud resources (now it appears as an inner section)

Correct

> Support env var to override elastic-agent image (As the BC is not public)

Imo should be part of the DOD

**Comment by ofiriro3** [comment]
Few other suggestions that will help us consolidate the weekly environment with the current Terraform modules. Currently, the weekly job uses scripts rather than using provisioners on the EC2 machine. After the Terraform code will be refactored we will be able to avoid these duplications.

1. Currently we cannot deploy an EC2 machine without deploying EKS, since these two flows are strongly dependent on each other. The EC2 terraform depends on the `module.api` which depends on the `module.iam_eks_role` which depends on `module.eks`. 

2. Creation of new resources happens every time - there are a lot of resources that we don't have to create on every deployment and we can reuse them (VPC and etc).

3. The creation of the EC2 happens in the same scope as deploying the agent on the EC2. The weekly job will deploy a new agent in each deployment but would not want to deploy a new EC2 each time.

4. API module - I think that we should consider using a bash script instead. There is a dependency between the "Vanilla" benchmark and the "EKS" benchmark, as well as a lot of code duplications that can be resolved by using parameters. Moreover, Terraform does not support `depends_on` when using providers as the ["restapi" provider](https://github.com/ofiriro3/cloudbeat/blob/2f337e75625c276fd5d2377610bec62fd6c1d3f9/deploy/cloud/main.tf). I suggest using similar scripts to what I introduced in the weekly job.

**Comment by amirbenun** [comment]
Thanks @olegsu, I agree with what you said, there are of course some ways to go and I just suggested one.

**Comment by olegsu** [comment]
Update
My proposed [solution](https://github.com/elastic/cloudbeat/issues/622#issuecomment-1437409760) will not work. The `restapi` [provider](https://github.com/elastic/cloudbeat/blob/main/deploy/cloud/main.tf#L90) needs to be configured before any resource is created. It is possible to overcome 2/3 required properties:
1. `username` and `password` value can be predictable and the actual user will be created later, just before the module using it.
2. `kibana_uri` is not something that we can easily know before that.

Instead, will continue with multiple one-liners that will install different applications (as @amirbenun suggested), where an application is one of

1. Elastic Cloud
2. KSPM - Vanilla: the creation of agent policy and package policy, later create all the required AWS resources and installed the agent on kind cluster that is running in ec2 instance.
3. KSPM - EKS: similar to KSPM - Vanilla installation, but the target is EKS cluster
4. CSPM - AWS: similar to  KSPM - Vanilla, but installing cloudbeat on ec2 directly

The end result will be 4 terraform scripts, a readme, and a script that will 
1. Run "Elastic Cloud" script
2. Get the output and apply all the others
3. Print nicely the output and summary

DOD
- [ ] One line to install all the components via script
- [ ] Readme that explains different installation methods (Elastic Stack and CSPM only, KSPM Vanilla, etc)
- [ ] All the resources have common tags and follow https://elastic.slack.com/archives/C02EXA5621E/p1676300388415619
- [ ] Elastic agent version can be changed both KSPM/CSPM (image/binary)

**Comment by eyalkraft** [comment]
Additional tech debt:

- [ ] Provision the eks cluster with a cluster role binding allowing all the developers to connect to the cluster, similar to what's described in the [guide](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html).
