### ISSUE TITLE
cloudbeat does not update log levels

### ISSUE THREAD

**Issue by CohenIdo** [elastic/cloudbeat#623]
**Describe the bug**
Changing the log level in fleet-ui does not update the log level in cloudbeat.

**Preconditions**
Environment state and/or platform-specific configurations.

**To Reproduce**
1. Create Kibana environment. 
2. add agent with KSPM package policy 
3. Wait for the agent to connect and verify that logs are arriving 
4. change the log level to `debug`

### **debug logs from filebeat:**
![image](https://user-images.githubusercontent.com/90558359/210216425-969061fb-d528-4307-a02f-1e2e0b61fd2c.png)

### **debug logs from cloudbeat:** 
![image](https://user-images.githubusercontent.com/90558359/210216572-004c84a6-7cdc-4fe0-b623-82c55eeb4224.png)

### ** all cloudbeat logs: **
![image](https://user-images.githubusercontent.com/90558359/210222184-d994f0c2-a87e-427d-b1f4-397f6dd20f24.png)

**cloudbeat version:** [0d31ac7352706eaadbded5da4f270e8eac701884](https://github.com/elastic/cloudbeat/commits/0d31ac7352706eaadbded5da4f270e8eac701884)
**elastic agent version:** [3bff6ff456946a30f5b743e6d36902e472c67e48](https://github.com/elastic/elastic-agent/commits/3bff6ff456946a30f5b743e6d36902e472c67e48)

**Comment by oren-zohar** [comment]
@CohenIdo it's unclear to me what's the case here, does cloudbeat log-level change, and the logs are not shown on the fleet UI, or does cloudbeat log-level not change at all? also, can you please attach the logs file?

**Comment by CohenIdo** [comment]
@oren-zohar I updated the description, let me know if there are any other questions.

**Comment by oren-zohar** [comment]
Yes, I just verified it also on 8.6. In my test, it seems like both cloudbeat and elastic agent log level is left on `info`, yet filebeat and metricbeat log-level does change to `debug`:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/85433724/210365624-513b1145-f4b5-47db-8140-4b8c81d92296.png">

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/85433724/210365675-1059f816-9ecd-4fb1-b3b7-94a9b9b037ee.png">

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/85433724/210365712-a453ac90-3e54-4ec7-9eb4-13d72ebbf4f3.png">

more information:

The agent status shows degraded, even though all beats are healthy:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/85433724/210365807-0a85703f-3aba-414a-ba70-10ef12be3c41.png">

The process `logging.level` is still set `info` (is this by design?)

```zsh
root@ip-172-31-41-101:/usr/share/elastic-agent# ps aux | grep logging.level
root      5037  0.2  1.8 1363824 146252 ?      Sl   12:44   0:07 /usr/share/elastic-agent/data/elastic-agent-a160c0/components/cloudbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${CLOUDBEAT_GOGC:100} -E http.enabled=true -E http.host=unix:///usr/share/elastic-agent/state/data/tmp/cloudbeat-cis_eks-default.sock -E path.data=/usr/share/elastic-agent/state/data/run/cloudbeat/cis_eks-default
root      6527  0.1  1.5 1461900 119104 ?      Sl   12:47   0:03 /usr/share/elastic-agent/data/elastic-agent-a160c0/components/filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${FILEBEAT_GOGC:100} -E filebeat.config.modules.enabled=false -E http.enabled=true -E http.host=unix:///usr/share/elastic-agent/state/data/tmp/log-default.sock -E path.data=/usr/share/elastic-agent/state/data/run/log-default
root      6589  0.9  2.1 1505636 171140 ?      Sl   12:47   0:21 /usr/share/elastic-agent/data/elastic-agent-a160c0/components/metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${METRICBEAT_GOGC:100} -E metricbeat.config.modules.enabled=false -E http.enabled=true -E http.host=unix:///usr/share/elastic-agent/state/data/tmp/system-metrics-default.sock -E path.data=/usr/share/elastic-agent/state/data/run/system/metrics-default
root     10954  0.0  1.4 1385864 111792 ?      Sl   12:54   0:00 /usr/share/elastic-agent/data/elastic-agent-a160c0/components/filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${FILEBEAT_GOGC:100} -E filebeat.config.modules.enabled=false -E http.enabled=true -E http.host=unix:///usr/share/elastic-agent/state/data/tmp/filestream-monitoring.sock -E path.data=/usr/share/elastic-agent/state/data/run/filestream-monitoring
root     28005  1.1  1.9 1429152 151296 ?      Sl   13:24   0:00 /usr/share/elastic-agent/data/elastic-agent-a160c0/components/metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${METRICBEAT_GOGC:100} -E metricbeat.config.modules.enabled=false -E http.enabled=true -E http.host=unix:///usr/share/elastic-agent/state/data/tmp/http-metrics-monitoring.sock -E path.data=/usr/share/elastic-agent/state/data/run/http/metrics-monitoring
root     28006  1.3  1.9 1429152 153772 ?      Sl   13:24   0:00 /usr/share/elastic-agent/data/elastic-agent-a160c0/components/metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${METRICBEAT_GOGC:100} -E metricbeat.config.modules.enabled=false -E http.enabled=true -E http.host=unix:///usr/share/elastic-agent/state/data/tmp/beat-metrics-monitoring.sock -E path.data=/usr/share/elastic-agent/state/data/run/beat/metrics-monitoring
root     28492  0.0  0.0   3440   724 pts/0    S+   13:25   0:00 grep --color=auto logging.level
```

@blakerouse @cmacknz can you please assist here?

FYI @tehilashn

**Comment by cmacknz** [comment]
The log level set with `-E logging.level=info` is the default log level the process is initialized with. To update the log level you see on the command line we would need to restart the processes, which we don't do when changing the log level. Instead effective log level should be updated dynamically via the Elastic agent control protocol.

Specifically this should be handled by libbeat [on this line](https://github.com/elastic/beats/blob/75ebd50e5d6a87eff626a502d63a8360a6c5cf00/x-pack/libbeat/management/managerV2.go#L438) which was introduced by https://github.com/elastic/beats/pull/34066

I don't know that we have observed this not working. I'll see if I can reproduce. If you can provide agent diagnostics while this isn't working we can investigate.

**Comment by cmacknz** [comment]
I can confirm I don't see agent debug logs, likely because the Beats log so much at debug level that the agent files rotate too fast to catch them: https://github.com/elastic/elastic-agent/issues/1955

Using a lower log level like warning to verify this, the change is respected by the agent.

**Comment by blakerouse** [comment]
@oren-zohar We need to improve the human readable output of the `elastic-agent status` command. You should use `elastic-agent status --output=yaml` to see the status information for each unit. There should be a unit reporting error in the YAML output.

I believe @cmacknz is correct that it is possible that beats its spewing too many logs as it does in debug mode for them to be caught.

@oren-zohar We do support a unique log level on an input if you want to try that. You can add `log_level: debug` on the input only keeping agent at `info` then see if you get the debug messages for cloudbeat.

**Comment by oren-zohar** [comment]
> I don't know that we have observed this not working. I'll see if I can reproduce. If you can provide agent diagnostics while this isn't working we can investigate.

@cmacknz Is there anything specific I should share? The agent logs or is there another command to extract diagnostics I'm unfamiliar with?

> Using a lower log level like warning to verify this, the change is respected by the agent.

@cmacknz oh nice idea, I'll do the same with cloudbeat and see if it works.

> @oren-zohar We need to improve the human readable output of the `elastic-agent status` command. You should use `elastic-agent status --output=yaml` to see the status information for each unit. There should be a unit reporting error in the YAML output.

This is the output for it (doesn't look like there's a unit in error state):

```terminal
root@ip-172-31-31-190:/usr/share/elastic-agent# elastic-agent status --output=yaml
info:
  id: a3e02e7e-4e4f-4e69-9451-276fa69aad6f
  version: 8.7.0
  commit: 047c1b534ef68d52a3c17bed270f74a522c37069
  build_time: 2023-01-01 01:40:39 +0000 UTC
  snapshot: true
state: 3
message: 1 or more components/units in a failed state
components:
- id: log-default
  name: log
  state: 2
  message: 'Healthy: communicating with pid ''15095'''
  units:
  - unit_id: log-default-logfile-system-99b0aed8-8d43-43b4-a4d5-6481ab58c499
    unit_type: 0
    state: 2
    message: Healthy
  - unit_id: log-default
    unit_type: 1
    state: 2
    message: Healthy
  version_info:
    name: beat-v2-client
    version: 8.7.0
    meta:
      build_time: 2022-12-30 20:02:19 +0000 UTC
      commit: 75ebd50e5d6a87eff626a502d63a8360a6c5cf00
- id: system/metrics-default
  name: system/metrics
  state: 2
  message: 'Healthy: communicating with pid ''15116'''
  units:
  - unit_id: system/metrics-default-system/metrics-system-99b0aed8-8d43-43b4-a4d5-6481ab58c499
    unit_type: 0
    state: 2
    message: Healthy
  - unit_id: system/metrics-default
    unit_type: 1
    state: 2
    message: Healthy
  version_info:
    name: beat-v2-client
    version: 8.7.0
    meta:
      build_time: 2022-12-30 19:57:24 +0000 UTC
      commit: 75ebd50e5d6a87eff626a502d63a8360a6c5cf00
- id: cloudbeat/cis_eks-default
  name: cloudbeat/cis_eks
  state: 2
  message: 'Healthy: communicating with pid ''15125'''
  units:
  - unit_id: cloudbeat/cis_eks-default-42a56759-ceb9-4dd5-a90d-666e9507e95b
    unit_type: 0
    state: 2
    message: beat reloaded
  - unit_id: cloudbeat/cis_eks-default
    unit_type: 1
    state: 2
    message: reloaded output component
  version_info:
    name: beat-v2-client
    version: 8.7.0
    meta:
      build_time: 0001-01-01 00:00:00 +0000 UTC
      commit: unknown
- id: http/metrics-monitoring
  name: http/metrics
  state: 2
  message: 'Healthy: communicating with pid ''19905'''
  units:
  - unit_id: http/metrics-monitoring-metrics-monitoring-agent
    unit_type: 0
    state: 4
    message: '[output unit has no config]'
  - unit_id: http/metrics-monitoring
    unit_type: 1
    state: 4
    message: '[output unit has no config]'
  version_info:
    name: beat-v2-client
    version: 8.7.0
    meta:
      build_time: 2022-12-30 19:57:24 +0000 UTC
      commit: 75ebd50e5d6a87eff626a502d63a8360a6c5cf00
- id: filestream-monitoring
  name: filestream
  state: 2
  message: 'Healthy: communicating with pid ''15140'''
  units:
  - unit_id: filestream-monitoring-filestream-monitoring-agent
    unit_type: 0
    state: 2
    message: Healthy
  - unit_id: filestream-monitoring
    unit_type: 1
    state: 2
    message: Healthy
  version_info:
    name: beat-v2-client
    version: 8.7.0
    meta:
      build_time: 2022-12-30 20:02:19 +0000 UTC
      commit: 75ebd50e5d6a87eff626a502d63a8360a6c5cf00
- id: beat/metrics-monitoring
  name: beat/metrics
  state: 2
  message: 'Healthy: communicating with pid ''31221'''
  units:
  - unit_id: beat/metrics-monitoring-metrics-monitoring-beats
    unit_type: 0
    state: 2
    message: Healthy
  - unit_id: beat/metrics-monitoring
    unit_type: 1
    state: 2
    message: Healthy
  version_info:
    name: beat-v2-client
    version: 8.7.0
    meta:
      build_time: 2022-12-30 19:57:24 +0000 UTC
      commit: 75ebd50e5d6a87eff626a502d63a8360a6c5cf00
```

> I believe @cmacknz is correct that it is possible that beats its spewing too many logs as it does in debug mode for them to be caught.

How can we confirm it? why this never was an issue beforehand? [I verified that it works a around a week ago](https://github.com/elastic/cloudbeat/pull/599) and it worked as expected? was there a new change in that area, or did I miss something?

I can try testing it without the other beats (only agent and cloudbeat), I'll update the results here.

> @oren-zohar We do support a unique log level on an input if you want to try that. You can add `log_level: debug` on the input only keeping agent at `info` then see if you get the debug messages for cloudbeat.

I'm not sure where to add this log level, can you clarify?

**Comment by cmacknz** [comment]
> @cmacknz Is there anything specific I should share? The agent logs or is there another command to extract diagnostics I'm unfamiliar with?

`elastic-agent diagnostics collect` will output a zip file with the agent logs, policy, current state of the running processes, etc.

**Comment by oren-zohar** [comment]
@cmacknz here it is
[diagnostics.tar.gz](https://github.com/elastic/cloudbeat/files/10339407/diagnostics.tar.gz)

**Comment by cmacknz** [comment]
In those diagnostics I see `log_level: info` in the state.yml file with each unit also having `log_level: 2` which [maps to info](https://github.com/elastic/elastic-agent-client/blob/4477e3ace394ef1abfec55afa5cc5e1f6f87980c/pkg/proto/elastic-agent-client.pb.go#L219)

> How can we confirm it? why this never was an issue beforehand? https://github.com/elastic/cloudbeat/pull/599 and it worked as expected? was there a new change in that area, or did I miss something?

I haven't noticed any issues with this myself either and our QA team actively tests log level changes. There were no changes that I know about that should cause this.

**Comment by cmacknz** [comment]
> I'm not sure where to add this log level, can you clarify?

I think you'd want it on the cloudbeat input in the agent policy, but it is probably generated by Fleet so you likely can't edit it by hand:

```yaml
- data_stream:
    namespace: default
  id: 42a56759-ceb9-4dd5-a90d-666e9507e95b
  meta:
    package:
      name: cloud_security_posture
      version: 1.2.1
  name: cloud_security_posture-1
  package_policy_id: 42a56759-ceb9-4dd5-a90d-666e9507e95b
  revision: 1
  streams:
    data_stream:
      dataset: cloud_security_posture.findings
      type: logs
  # ...
  type: cloudbeat/cis_eks
  use_output: default
  log_level: debug # Add the log level here, disclaimer that I didn't test this YAML snippet
```

**Comment by oren-zohar** [comment]
>  In those diagnostics I see log_level: info in the state.yml file with each unit also having log_level: 2 which [maps to info](https://github.com/elastic/elastic-agent-client/blob/4477e3ace394ef1abfec55afa5cc5e1f6f87980c/pkg/proto/elastic-agent-client.pb.go#L219)

@cmacknz so this raises two questions:

1. Why didn't the log level change?
2. Why other beats did send debug-level logs after the change?

**Comment by oren-zohar** [comment]
> Using a lower log level like warning to verify this, the change is respected by the agent.

@cmacknz Still seeing `info` level logs after changing to `warning` 
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/85433724/210549755-42117e7d-5fbf-4fad-bc74-24022135d2ce.png">

The state.yml also shows `log_level: 1` (warning) so the log level did change, yet we still see info-level logs.

here's the [elastic-agent-diagnostics-2023-01-04T11-33-02Z-00.zip](https://github.com/elastic/cloudbeat/files/10343801/elastic-agent-diagnostics-2023-01-04T11-33-02Z-00.zip)

**Comment by blakerouse** [comment]
Side-note on why your Elastic Agent is degraded, you do have a failing unit:

```
- id: http/metrics-monitoring
  name: http/metrics
  state: 2
  message: 'Healthy: communicating with pid ''19905'''
  units:
  - unit_id: http/metrics-monitoring-metrics-monitoring-agent
    unit_type: 0
    state: 4
    message: '[output unit has no config]'
  - unit_id: http/metrics-monitoring
    unit_type: 1
    state: 4
    message: '[output unit has no config]'
  version_info:
    name: beat-v2-client
    version: 8.7.0
    meta:
      build_time: 2022-12-30 19:57:24 +0000 UTC
      commit: 75ebd50e5d6a87eff626a502d63a8360a6c5cf00
```

**Comment by cmacknz** [comment]
> Side-note on why your Elastic Agent is degraded, you do have a failing unit:

That is a symptom of https://github.com/elastic/beats/issues/34137, which was fixed yesterday. The output unit Beat config generation correct handles the missing config and reports it but the input unit generation segfaults. This was only fixed yesterday so unlikely to be in the version Oren is testing with.

**Comment by cmacknz** [comment]
Looking at the diagnostics from @oren-zohar's last comment, I can see three info logs are generated from the agent seemingly after the warning logs from the Beats:

```json
{"log.level":"info","@timestamp":"2023-01-04T11:23:36.952Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":729},"message":"Updating running component model","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-01-04T11:28:18.921Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":729},"message":"Updating running component model","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-01-04T11:28:42.865Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":729},"message":"Updating running component model","ecs.version":"1.6.0"}
```

Those `Updating running component model` log lines are actually generated as part of the process of changing the agent log level, and it looks like they are generated asynchronously to the actual global log level change in the agent itself.

The call stack as I see it is:

1. Handling of the log level change action: https://github.com/elastic/elastic-agent/blob/ab2cf8a6caea84f48a43e8d61fd4a5ff6aa221bc/internal/pkg/agent/application/coordinator/coordinator.go#L312-L322
2. In a separate goroutine, we receive from the channel: https://github.com/elastic/elastic-agent/blob/ab2cf8a6caea84f48a43e8d61fd4a5ff6aa221bc/internal/pkg/agent/application/coordinator/coordinator.go#L624-L632
3. That then calls `process`:https://github.com/elastic/elastic-agent/blob/ab2cf8a6caea84f48a43e8d61fd4a5ff6aa221bc/internal/pkg/agent/application/coordinator/coordinator.go#L702-L715
4. Process then generates the INFO logs @oren-zohar is observing: https://github.com/elastic/elastic-agent/blob/ab2cf8a6caea84f48a43e8d61fd4a5ff6aa221bc/internal/pkg/agent/application/coordinator/coordinator.go#L717-L730

There is nothing actually deterministically controlling whether the global `logger.SetLevel(lvl)` call executes before the `c.logger.Info("Updating running component model")` log line executes. The call to `logger.SetLevel(lvl)` does explicitly wait for the send to happen on `logLevelCh` which is unbuffered though so it seems entirely likely you'll frequently see those INFO logs before the global agent log level change actually takes effect.

https://github.com/elastic/elastic-agent/blob/ab2cf8a6caea84f48a43e8d61fd4a5ff6aa221bc/internal/pkg/agent/application/coordinator/coordinator.go#L198

If this is the only problem, it seems explainable and while maybe no intuitive given the ordering of the logs it is working as intended.

If we continue to see INFO logs from the agent after the log level change has taken effect, that would be a concern but I haven't seen evidence of that. One problem here is we don't log when the log level actually changes on the agent side which would help debugging the exact timing here, maybe we should add a log line for that.

**Comment by oren-zohar** [comment]
Thanks for the further investigation @cmacknz! I hope the snapshot will be updated soon so I can test it and update it here.

> I also think we are restarting the Beats unnecessarily here, as we are treating a log level change in the output unit as equivalent to any other output unit config change and restarting the entire beat as a result. That can also be fixed.

This was the pre-V2 behavior AFAIK. Wouldn't that be a breaking change? we used it as a way of restarting the beat easily from the fleet UI so we don't mind keeping it 🙂

**Comment by cmacknz** [comment]
> This was the pre-V2 behavior AFAIK. Wouldn't that be a breaking change? we used it as a way of restarting the beat easily from the fleet UI so we don't mind keeping it 🙂

Just changing the log level doesn't need to restart the beats anymore, it still does I would like to remove this. 

Changing any of the other output configurations still does require a restart of the Beat, so even if we remove the restart when the log level changes you can still trigger a restart by doing something like increasing the `bulk_max_size` configuration of the ES output by 1. Ideally we wouldn't restart in this case either but it is significantly harder to remove as it is tied into years old bugs in how the Beats output reloader works.

**Comment by olegsu** [comment]
I have tried working with the latest snapshot of 8.6.1 today.
```bash
root@kind-multi-control-plane:/usr/share/elastic-agent/data/elastic-agent-8a9e9f/components# elastic-agent version
Binary: 8.6.1-SNAPSHOT (build: 8a9e9fcf76f7cd7bc7e75d7cf82b35766b993c25 at 2023-01-16 01:58:29 +0000 UTC)
```
Seems that it's not working yet.
What I tried from our side was
1. Send all the `debug` logs to `info`, this seems to work and the load was not an issue.
2. Verify that the log level is always set to the value in `cloudbeat.spec.yml`.
![image](https://user-images.githubusercontent.com/23185631/212750017-f059d425-6281-408d-906c-79a2ab2bf876.png)
Those lines will be printed to the log file based on the agent log level and the value in the spec file. When the value in the spec file will be passed as is to the process regardless to the agent log level.

**Comment by cmacknz** [comment]
The beats version in your go.mod on your 8.6 branch is https://github.com/elastic/cloudbeat/blob/9e6c670789d3d0cf79263ac0e93e988cca54acda/go.mod#L84

That points to https://github.com/elastic/beats/commit/255028c4cb3b on main

<img width="2505" alt="Screen Shot 2023-01-17 at 2 19 55 PM" src="https://user-images.githubusercontent.com/3466215/212992548-853f69f2-762b-4c0f-9549-b41dbdbe335a.png">

Support for changing the log level dynamically was added to libbeat a day later in https://github.com/elastic/beats/commit/15d9a876057435520056e5cbf5890aec109dbeba

<img width="1362" alt="Screen Shot 2023-01-17 at 2 21 59 PM" src="https://user-images.githubusercontent.com/3466215/212992909-a4b4eb43-d922-498c-863e-4e5de28746e0.png">

If you update the libbeat version to the latest one on main and 8.6 respectively this should be fixed for you.

**Comment by tehilashn** [comment]
Thank you @cmacknz !
