### ISSUE TITLE
[BUG] CIS EKS Rule 3.2.5 When streamingConnectionIdleTimeout or --streaming-connection-idle-timeout equals 0 evaluation is passed

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#632]
**Describe the bug**

When streamingConnectionIdleTimeout or --streaming-connection-idle-timeout equals 0 evaluation equals pass instead of fail.

![Screen Shot 2023-01-02 at 18 24 50](https://user-images.githubusercontent.com/99176494/210257381-58d8d4dc-0689-447e-a6de-e47af3c489fe.png)

![Screen Shot 2023-01-02 at 18 27 35](https://user-images.githubusercontent.com/99176494/210257636-445b7157-e712-440b-8e69-982f553b8696.png)

**Preconditions**
ELK Stack 8.6.0-BC 9 is deployed
Connection to test-config-1 cluster for kubectl is ready

**To Reproduce**
1. Create KSPM integration and select EKS deployment.
2. Deploy Fleet managed agent to test-config-1 cluster.
3. Navigate to Findings and search by rule.tags : "CIS 3.2.5" and host.name : "ip-192-168-57-173.eu-west-2.compute.internal"
4. Navigate to Findings and search by rule.tags : "CIS 3.2.5" and host.name : "ip-192-168-83-229.eu-west-2.compute.internal"

**Expected behavior**
Evaluation result shall be **failed**.

OS: NA
Browser: NA
Kibana Version: 8.6.0 BC-9 (COMMIT: 93183bddac40f8a7ee8e566d1651f9f3b586a520)
Elastic-Agent: Commit (3bff6ff456946a30f5b743e6d36902e472c67e48)
EKS Cluster version: V1.23

**Comment by ofiriro3** [comment]
Nice catch @gurevichdmitry 

https://github.com/elastic/csp-security-policies/blob/26b5e7d44d1c6fbc6baa1e5a255434f09cbaff78/bundle/compliance/cis_eks/rules/cis_3_2_5/rule.rego

An easy solution is the rule search for `0` and not for `0s`.

@gurevichdmitry is `0s` the default configuration? is it ok to set the value as `0s`, is `0` also valid?

**Comment by gurevichdmitry** [comment]
@ofiriro3 the default configuration is not defined in files (conf and args) and equals to 4h. Args file may contain both types `0` and `0s`. Config file accepts `0s` format.

**Comment by gurevichdmitry** [comment]
The bug still occurs with `streamingConnectionIdleTimeout=0s`

**Comment by animehart** [comment]
<img width="785" alt="Screenshot 2023-05-02 at 10 42 50 AM" src="https://user-images.githubusercontent.com/8703149/235744407-2c78fece-c5ad-485b-a2b0-dd6e1bf40896.png">
<img width="838" alt="Screenshot 2023-05-02 at 10 46 39 AM" src="https://user-images.githubusercontent.com/8703149/235744414-082e1f86-770c-4457-9809-789858bf3ef0.png">

**Test:**
For rule with rule.tag 3.2.5, When streamingConnectionIdleTimeout or --streaming-connection-idle-timeout equals 0, evaluation is now set to **Fail** . 

**Notes:**
Tested on cluster created by Dima

**Steps:**
1. Deploy 8.8.0 on staging
2. Install KSPM EKS on the Cluster created by Dima 
3. Navigate to Findings once findings shows up
4. search by rule.tags : "CIS 3.2.5" 
5. Expand the result and click on the JSON tab and verify the field vs the evaluation of that findings

Result:
**Verified**
