### ISSUE TITLE
[BUG] CIS EKS Rule 3.2.7 - Cloudbeat evaluates rule to pass even --make-iptables-util-chains is set to false.

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#633]
**Describe the bug**

When --make-iptables-util-chains is set to false, evaluation is passed. According to CIS EKS the evaluation should fail.

![Screen Shot 2023-01-02 at 18 39 39](https://user-images.githubusercontent.com/99176494/210259146-805fd222-6452-4263-8d78-730d29177cf4.png)

**Preconditions**
ELK Stack 8.6.0-BC 9 is deployed
Connection to test-config-1 cluster for kubectl is ready

**To Reproduce**
1. Create KSPM integration and select EKS deployment.
2. Deploy Fleet managed agent to test-config-1 cluster.
3. Navigate to Findings and search by rule.tags : "CIS 3.2.7" and host.name : "ip-192-168-83-229.eu-west-2.compute.internal"

**Expected behavior**
Evaluation result shall be **failed**.

OS: NA
Browser: NA
Kibana Version: 8.6.0 BC-9 (COMMIT: 93183bddac40f8a7ee8e566d1651f9f3b586a520)
Elastic-Agent: Commit (3bff6ff456946a30f5b743e6d36902e472c67e48)
EKS Cluster version: V1.23

**Comment by ofiriro3** [comment]
Nice catch @gurevichdmitry 

I wonder if this bug happen due to the same issue I described in another ticket.
Maybe the delimiter was changed from `space` to `=`.

**Comment by amirbenun** [comment]
So indeed we have some problems with parsing the delimiters.
I found the underlying bug; In our Rego code, there is some hard-coded assumption that over EKS process args have `" "` as a delimiter where in K8s it must be `=`.
IMO, that's a bad practice and we should support both delimiters with every benchmark we implement that gets processes as input.
The source of it lies in our process parser module where we build a key value **map** of arguments where instead we should have built an arguments **list** as it represents better the way processes work.
Once we have an argument list, we should check for two arguments in a row that satisfy the `..., key, value, ...` or a single arg that equals `key=value`.

The same logic can also be implemented on our arguments map as a workaround, but keep in mind that the wrong model may expose other bugs in the future.

**Comment by olegsu** [comment]
Verified
![image](https://user-images.githubusercontent.com/23185631/218706773-0b5a1819-d6a1-4f24-bbb1-f63a1fe44e55.png)
