### ISSUE TITLE
[BUG] CIS EKS Rule 3.2.11 - When RotateKubeletServerCertificate does not exist evaluation is passed.

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#634]
**Describe the bug**

When RotateKubeletServerCertificate does not exist evaluation is passed and according to CIS EKS should fail.

**Preconditions**
ELK Stack 8.6.0-BC 9 is deployed
Connection to test-config-1 cluster for kubectl is ready

**To Reproduce**
1. Create KSPM integration and select EKS deployment.
2. Deploy Fleet managed agent to test-config-1 cluster.
3. Navigate to Findings and search by rule.tags : "CIS 3.2.11" and host.name : "ip-192-168-57-173.eu-west-2.compute.internal"

**Expected behavior**
Since RotateKubeletServerCertificate is not defined or does not exist in kubelet-config.json file evaluation result shall be **failed**.

OS: NA
Browser: NA
Kibana Version: 8.6.0 BC-9 (COMMIT: 93183bddac40f8a7ee8e566d1651f9f3b586a520)
Elastic-Agent: Commit (3bff6ff456946a30f5b743e6d36902e472c67e48)
EKS Cluster version: V1.23

**Comment by ofiriro3** [comment]
@gurevichdmitry 

Did you check both the `--feature-gates", "RotateKubeletServerCertificate=true` and the `--rotate-server-certificates", "true"`?

Maybe its the same delimiter issue with the `space` instead of `=`

**Comment by gurevichdmitry** [comment]
@ofiriro3 I didn't checked both keys since `--rotate-server-certificates` key named as `--rotate-kubelet-server-certificate=true` in the CIS EKS benchmark, and when I tried to add this key to args file there was a problem with the kubelet process (process crash)

**Comment by olegsu** [comment]
Verified
![image](https://user-images.githubusercontent.com/23185631/218707760-90db6148-d769-4257-99c4-3ae53b4de383.png)
