### ISSUE TITLE
[BUG] CIS EKS Rule 4.2.7 - Cloudbeat set rule evaluation to fail even though the capabilities.drop ALL is defined in the pod spec.

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#635]
**Describe the bug**

Cloudbeat set rule 4.2.7 evaluation to fail even though the capabilities.drop ALL is defined in the pod spec.
![Screen Shot 2023-01-02 at 19 32 36](https://user-images.githubusercontent.com/99176494/210264051-5675a7b6-50a0-4adf-ae59-9bfe88907531.png)

**Preconditions**
ELK Stack 8.6.0-BC 9 is deployed
Connection to test-config-1 cluster for kubectl is ready

**To Reproduce**
1. Create KSPM integration and select EKS deployment.
2. Deploy Fleet managed agent to test-config-1 cluster.
3. Navigate to Findings and search by rule.tags : "CIS 4.2.7" and and resource.name : "test-eks-good-pod"

**Expected behavior**
Evaluation result shall be **passed**.

OS: NA
Browser: NA
Kibana Version: 8.6.0 BC-9 (COMMIT: 93183bddac40f8a7ee8e566d1651f9f3b586a520)
Elastic-Agent: Commit (3bff6ff456946a30f5b743e6d36902e472c67e48)
EKS Cluster version: V1.23

**Comment by olegsu** [comment]
Verified
![image](https://user-images.githubusercontent.com/23185631/218711591-fbf40004-4d4d-4bff-b4e8-d00a529fa2ab.png)
