### ISSUE TITLE
[BUG] CIS EKS Rule 4.2.9 - Cloudbeat set rule evaluation to fail even though the capabilities.drop ALL is defined in the pod spec.

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#636]
**Describe the bug**

According to the CIS EKS Rule 4.2.9: Do not generally permit containers with capabilities
When defining pod with capabilities.drop: ["ALL"], Cloudbeat set rule evaluation to fail.
Evaluation is passed only if field **capabilities** is not defined.

**Preconditions**
ELK Stack 8.6.0-BC 9 is deployed
Connection to test-config-1 cluster for kubectl is ready

**To Reproduce**
1. Create KSPM integration and select EKS deployment.
2. Deploy Fleet managed agent to test-config-1 cluster.
3. Navigate to Findings and search by rule.tags : "CIS 4.2.9" and and resource.name : "test-eks-good-pod"

**Expected behavior**
Evaluation result shall be **passed**.

OS: NA
Browser: NA
Kibana Version: 8.6.0 BC-9 (COMMIT: 93183bddac40f8a7ee8e566d1651f9f3b586a520)
Elastic-Agent: Commit (3bff6ff456946a30f5b743e6d36902e472c67e48)
EKS Cluster version: V1.23

**Comment by olegsu** [comment]
![Uploading image.png…]()
