### ISSUE TITLE
Support different authetntication methods for AWS

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#640]
**Motivation**
We need to support multiple authentication methods for AWS so that users can authenticate with their cloud however they prefer.

**Definition of done**
Support the following authentication methods via configuration:
- [ ] IAM role
- [ ] Direct access keys
- [ ] Temporary keys
- [ ] Shared credential file

**Out of scope**
Anything not related to authenticating with AWS

**Comment by oren-zohar** [comment]
@oren-zohar add to 8.7 QA cycle

**Comment by oren-zohar** [comment]
Already done as part of libeat implementation
