### ISSUE TITLE
Cloudbeat does not evaluate all the benchmark processes findings 

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#646]
**Describe the bug**
When running Cloudbeat, it should evaluate 5 different processes.
On 8.7 SNAPSHOT, Cloudbeat only evaluates the `kubelet` process

**Preconditions**
I deployed Cloudbeat agentless on kind --image kindest/node:v1.23.12.

**To Reproduce**
1. Deploy the ELK.
2. Go to the findings/Discover page, and filter by `resource. type: process`
3. Only `kubelet` appears.

**Expected behavior**
5 processes should appear:
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/19221736/210611512-86e0ea2a-24c1-4664-b226-87f23194a3fd.png">

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Kibana Version: v1.2.7
 - Kibana_commit_sha: cce254756796cb0f3661097789d8e484742a665c
 - Endpoint Version:
 - Other Version:
 - Cloudbeat_version: 8.7.0
 - Cloudbeat_commit_sha: 56ce4a62e41f1c8a13365eed626dc1c71ebf752e
 - Policy_version: v1.2.7
 - Kind version: kindest/node:v1.23.12

**Comment by oren-zohar** [comment]
@jeniawhite @ofiriro3 might be related:
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/85433724/210764201-518f33d7-5c06-4187-bed1-e0400b5931ed.png">
