### ISSUE TITLE
Standalone agent integration test is broken

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#647]

**Comment by oren-zohar** [comment]
Maybe we can make sure the findings contain the expected cloudbeat SHA for verification as part of the integration test? @jeniawhite @gurevichdmitry

**Comment by gurevichdmitry** [comment]
@oren-zohar, Is cloudbeat sends commit details with findings?

**Comment by oren-zohar** [comment]
[it does](https://github.com/elastic/cloudbeat/issues/412) @gurevichdmitry

**Comment by gurevichdmitry** [comment]
@oren-zohar, it is possible to verify cloudbeat SHA. Retrieving data through elasticsearch is a simple task but retrieving cloudbeat SHA is a bit complicated since SHA is dynamic value that should be passed as env variable to the test pod during a test run initialization.

**Comment by gurevichdmitry** [comment]
@oren-zohar, it is possible to verify cloudbeat SHA. Retrieving data through elasticsearch is a simple task but retrieving cloudbeat SHA is a bit complicated since SHA is dynamic value that should be passed as env variable to the test pod during a test run initialization.
