### ISSUE TITLE
Cloudbeat stdout and stderr appear as error log

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#651]
**Motivation**
Cloudbeat implementation uses [zap](https://github.com/uber-go/zap) logger to log into files by default.
In a few cases, we use libraries that output logs to stdout or stderr.
The agent then collects all the information printed out to cloudbeat std channels and copies it to cloudbeat log file as an error.
For example, k8s [go-client](https://github.com/kubernetes/client-go) outputs `attempting to acquire leader lease kube-system/cloudbeat-cluster-leader` to stdout and it appears in our log file as an error that may cause confusion.

A few suggestions on the path we may take here to make things more clear:
1. Implement k8s logger using [logp](https://github.com/elastic/elastic-agent-libs/tree/main/logp) to print logs to file as expected
2. The agent should copy the stdout info as UNKNOWN log level

**Definition of done**
Printing to stdout and stderr should more clear to the user

**Related tasks/epics**
- https://github.com/elastic/security-team/issues/4070

**Comment by oren-zohar** [comment]
I don't think it's relevant anymore
