### ISSUE TITLE
Fetchers timeout should be configurable

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#653]
**Motivation**
Cloudbeat should have configurable fetchers timeout. The old timeout before CSPM fetchers was set to 1 minute, but fetchers that fetch data from an internet API (e.g. cloud resources) might take longer than that to produce resources for evaluation, and should not timeout.

**Definition of done**
- [ ] Allow configuration of fetchers timeout via `cloudbeat.yml`
- [ ] Set default CSPM timeout for 10 minutes
- [ ] Set default KSPM timeout for 1 minute

**Comment by ofiriro3** [comment]
Interesting topic 👍

One question that I am curious about is - how will we define a timeout for all fetchers.
I mean some of the fetchers require more work/time than others.

For example, the ECR fetcher can have multiple requests depending on the number of pods it needs to process.
