### ISSUE TITLE
resources with 0 findings

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#672]
### Summary

While setting the log level to `debug` we saw some resources with no findings. We need to investigate why this is happening and address it.

**DOD**
- [ ] Reproduce the issue
- [ ] Identify the cause
- [ ] Suggest solution

**Comment by uri-weisman** [comment]
I've noticed it's happening repeatedly with the `ClusterRole` sub type.

```
[elastic_agent.cloudbeat][debug] {"decision_id":"ba39b3c1-b22b-4abe-9912-9c360fafaf7c","input":{"type":"k8s_object","subType":"ClusterRole","resource":{"kind":"ClusterRole","apiVersion":"rbac.authorization.k8s.io/v1","metadata":{"name":"system:controller:generic-garbage-collector","uid":"3c4a3e18-69a5-49fa-b926-04519d5bb75c","resourceVersion":"123","creationTimestamp":"2023-06-21T08:05:16Z","labels":{"kubernetes.io/bootstrapping":"rbac-defaults"},"annotations":{"rbac.authorization.kubernetes.io/autoupdate":"true"}},"rules":[{"verbs":["delete","get","list","patch","update","watch"],"apiGroups":["*"],"resources":["*"]},{"verbs":["create","patch","update"],"apiGroups":["","events.k8s.io"],"resources":["events"]}]},"benchmark":"cis_eks"},"message":"Decision Log","result":{"findings":[],"metadata":{"opa_version":"0.45.0","policy_version":"1.0.0"},"resource":{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{"rbac.authorization.kubernetes.io/autoupdate":"true"},"creationTimestamp":"2023-06-21T08:05:16Z","labels":{"kubernetes.io/bootstrapping":"rbac-defaults"},"name":"system:controller:generic-garbage-collector","resourceVersion":"123","uid":"3c4a3e18-69a5-49fa-b926-04519d5bb75c"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["delete","get","list","patch","update","watch"]},{"apiGroups":["","events.k8s.io"],"resources":["events"],"verbs":["create","patch","update"]}]}}}
```

**Comment by orouz** [comment]
got another one locally working on #1262:

```
{
  "log.level": "debug",
  "@timestamp": "2023-08-29T15:00:58.845+0300",
  "log.logger": "posture",
  "log.origin": { "file.name": "evaluator/opa.go", "file.line": 136 },
  "message": 'Created 0 findings for input: {identity-management gcp-iam-service-account update_time:{seconds:1692098571} name:"//iam.googleapis.com/projects/test-project-1-396010/serviceAccounts/101719364147005768777" asset_type:"iam.googleapis.com/ServiceAccount" resource:{version:"v1" discovery_document_uri:"https://iam.googleapis.com/$discovery/rest" discovery_name:"ServiceAccount" parent:"//cloudresourcemanager.googleapis.com/projects/295040128706" data:{fields:{key:"description" value:{string_value:"Firebase Admin SDK Service Agent"}} fields:{key:"displayName" value:{string_value:"firebase-adminsdk"}} fields:{key:"email" value:{string_value:"firebase-adminsdk-nmk2p@test-project-1-396010.iam.gserviceaccount.com"}} fields:{key:"name" value:{string_value:"projects/test-project-1-396010/serviceAccounts/firebase-adminsdk-nmk2p@test-project-1-396010.iam.gserviceaccount.com"}} fields:{key:"oauth2ClientId" value:{string_value:"101719364147005768777"}} fields:{key:"projectId" value:{string_value:"test-project-1-396010"}} fields:{key:"uniqueId" value:{string_value:"101719364147005768777"}}}} ancestors:"projects/295040128706" ancestors:"organizations/693506308612"}',
  "service.name": "cloudbeat",
  "ecs.version": "1.6.0",
}
```

**Comment by orouz** [comment]
> I've noticed it's happening repeatedly with the `ClusterRole` sub type.
> 
> ```
> [elastic_agent.cloudbeat][debug] {"decision_id":"ba39b3c1-b22b-4abe-9912-9c360fafaf7c","input":{"type":"k8s_object","subType":"ClusterRole","resource":{"kind":"ClusterRole","apiVersion":"rbac.authorization.k8s.io/v1","metadata":{"name":"system:controller:generic-garbage-collector","uid":"3c4a3e18-69a5-49fa-b926-04519d5bb75c","resourceVersion":"123","creationTimestamp":"2023-06-21T08:05:16Z","labels":{"kubernetes.io/bootstrapping":"rbac-defaults"},"annotations":{"rbac.authorization.kubernetes.io/autoupdate":"true"}},"rules":[{"verbs":["delete","get","list","patch","update","watch"],"apiGroups":["*"],"resources":["*"]},{"verbs":["create","patch","update"],"apiGroups":["","events.k8s.io"],"resources":["events"]}]},"benchmark":"cis_eks"},"message":"Decision Log","result":{"findings":[],"metadata":{"opa_version":"0.45.0","policy_version":"1.0.0"},"resource":{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{"rbac.authorization.kubernetes.io/autoupdate":"true"},"creationTimestamp":"2023-06-21T08:05:16Z","labels":{"kubernetes.io/bootstrapping":"rbac-defaults"},"name":"system:controller:generic-garbage-collector","resourceVersion":"123","uid":"3c4a3e18-69a5-49fa-b926-04519d5bb75c"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["delete","get","list","patch","update","watch"]},{"apiGroups":["","events.k8s.io"],"resources":["events"],"verbs":["create","patch","update"]}]}}}
> ```

plugging this to [rego playground](https://play.openpolicyagent.org/p/EqWowo2qrn) results in this specific input being evaluated as false. currently i'm not able to reproduce it.

**Comment by oren-zohar** [comment]
@orouz let's try to add log on rego side whenever there's a resource without a finding evaluation

**Comment by orouz** [comment]
> let's try to add log on rego side whenever there's a resource without a finding evaluation

we're already _kinda_ doing this in `opa.go` 
https://github.com/elastic/cloudbeat/blob/dc7730d8aa5ad84da066b5ad5edb1b063c16d082/internal/evaluator/opa.go#L136

whenever we send a `fetcherResult` with a resource and it gets `0` findings, we know this specific resource wasn't evaluated. 

an improvement here would be to change the current log to only print whenever we actually have findings, so we don't log `generated 0 findings` which is not ideal. in the case where we do have 0 findings, we would log something else, such as: `failed to evaluate a resource: <full_resource_data>` 

@oren-zohar wdyt?

**Comment by oren-zohar** [comment]
@orouz Sounds good to me

**Comment by orouz** [comment]
there are no more `Created 0 findings` logs in the long-running environment and we've deemed that the current specific log is sufficient and kept it as is, therefore i'm closing this issue as there is nothing else we can do here at the moment.

**Comment by orestisfl** [comment]
@oren-zohar Should we include this in QA?

**Comment by oren-zohar** [comment]
@orestisfl yes, I think we can check our long running env to see if we get the zero findings logs maybe?

**Comment by romulets** [comment]
✅ QA Verified


I could not find the error logs on the environment https://live-environment-do-not-delete-stack.kb.us-west2.gcp.elastic-cloud.com:9243/

![image](https://github.com/elastic/cloudbeat/assets/5350001/b6d19dc6-525e-4404-99a2-87a82a3badd7)

![image](https://github.com/elastic/cloudbeat/assets/5350001/0a4bbe02-3c44-4f5b-b75c-8e8866a95d43)
