### ISSUE TITLE
Cloud Posture findings never appear within the dashboard - unauthorized for API key id [] of user [elastic/fleet-server] on indices [logs-cloud_security_posture.findings-default]

### ISSUE THREAD

**Issue by AndyDevman** [elastic/cloudbeat#678]
## Summary

Cloud Posture findings never appear in the Cloud Posture dashboard - unauthorized for API key id [] of user [elastic/fleet-server] on indices [logs-cloud_security_posture.findings-default]

![image](https://user-images.githubusercontent.com/46032005/214873639-301d03fd-ce7f-4ee0-8fc5-2cc543643dda.png)

## Detail

Looking at the logs on agent pods here `/usr/share/elastic-agent/state/data/logs/default/cloudbeat-*.ndjson` ,

There are entries which appear to represent successful evaluation against CIS benchmarks, however the CIS benchmark part of the log messages are encapsulated by warnings as follows.

> [the main body of the message has been redacted]

**This is found at the start of the message.**
```
{"log.level":"warn","@timestamp":"2023-01-...........","log.logger":"elasticsearch","log.origin":{"file.name":"elasticsearch/client.go","file.line":429},"message":"Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2023, ...., time.UTC), Meta:{\"index\":\"logs-cloud_security_posture.findings-default\
```

**This is found at the end of the message**
```
(status=403): {\"type\":\"security_exception\",\"reason\":\"action [indices:admin/auto_create] is unauthorized for API key id [1asd12312............] of user [elastic/fleet-server] on indices [logs-cloud_security_posture.findings-default], this action is granted
 by the index privileges [auto_configure,create_index,manage,all]\"}, dropping event!","service.name":"cloudbeat","ecs.version":"1.6.0"}
```

## Configuration

Elastic Agent Version : v8.5.0
Kubernetes Security Posture Management Integration version is v1.0.5
Elastic Agent is configured as a Daemonset and enrolled into fleet
Running on EKS

**Comment by CohenIdo** [comment]
Hey @AndyDevman, in order to better understand, here are some questions:
1. What kind of deployment is it? cloud/on-prem/elastic-package? 
2. Is there another integration installed on this deployment that is sending logs successfully?
3. Did you change the value of `FLEET_ENROLLMENT_TOKEN` or any other changes in the manifest file before deployed the integration?

**Comment by uri-weisman** [comment]
@AndyDevman can you please provide your agent policy?
