### ISSUE TITLE
 Implement vulnerabilities database periodical updates

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#696]
**Motivation**
As we have discussed on a separate ticket (see below), the vulnerability database trivy uses needs to be updated before every cycle in order to provide a reliable product to our users.

**Definition of done**
- [ ] Update trivy database before every vulnerability scanning cycle
- [ ] Trivy database should be cached using the built-in cache layer
- [ ] When the cache doesn't exist, a failed database download should result in cloudbeat exit with error
- [ ] When the cache exists, a failed database download should change cloudbeat to an unhealthy state (and keep running)

**Out of scope**
- https://github.com/elastic/cloudbeat/issues/697

**Related tasks/epics**
- https://github.com/elastic/cloudbeat/issues/624

**Comment by kfirpeled** [comment]
@amirbenun do we send the DB version as part of the vulnerability?

**Comment by amirbenun** [comment]
@kfirpeled we don't, Trivy doesn't expose it.

**Comment by kfirpeled** [comment]
Thanks @amirbenun 
For the upcoming QA cycle, how do you suggest to verify this ticket?

**Comment by uri-weisman** [comment]
Verified - DB is updated every cycle (24h)



![Image](https://github.com/elastic/cloudbeat/assets/68195305/707c3069-bc9a-45b0-ac4a-c637e2760470)
