### ISSUE TITLE
[Discuss] Bundling vulnerability database into cloudbeat.tar.gz

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#697]
**Motivation**
For our vulnerability scanning flow, cloudbeat will use Trivy to scan the available AWS account volumes. In order to get the vulnerabilities it will download at the start of the first scan DB with all the latest vulnerabilities. We want to bundle our binary with the DB so if there's any issue downloading the latest one, we will have a fallback option.

**Definition of done**
- [ ] Propuse the solution
- [ ] ~~In Cloudbeat CI/CD pipeline, before we release a new version, we should download the database and package it to elastic-agent.tar.gz~~
- [ ] Cloudbeat should instruct trivy to read the vulnerabilities database from the downloaded file
- [ ] A failed database download should never cause an exit with an error but rather change cloudbeat to an unhealthy state and keep running

**Related tasks/epics**
- https://github.com/elastic/cloudbeat/issues/624
- https://github.com/elastic/cloudbeat/issues/696

**Comment by amirbenun** [comment]
As for the second part of this task, packaging Trivy DB together with cloudbeat, it means enlarging the elastic-agent artifact with 400 Mb. Is that ok @eyalkraft @oren-zohar ?

**Comment by oren-zohar** [comment]
This is pretty significant, and I think we should discuss it with the agent team before doing anything like that. I would like to hear your thoughts on this, @cmacknz @amitkanfer.

**Comment by amitkanfer** [comment]
can you download on-demand? only if the integration is installed?

**Comment by amirbenun** [comment]
Yes, this is what we do right now, and even if we package the vulnerabilities artifact we will still try to download it first.
This ticket is about having a workaround in case the vulnerabilities artifact won't be available for some reason.

**Comment by amirbenun** [comment]
A continuation tasks for improving the vuln DB download process:
https://github.com/elastic/cloudbeat/issues/1048
