### ISSUE TITLE
Implement the GetMetadata method for the EKS fetchers

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#71]
Motivation

Currently, our core fetchers - FS, k8s, Process implement GetMetadata as one of the methods of the `Resource` interface.
It is done according to the following [design doc](https://docs.google.com/document/d/19_sd8yshON-X8b6C8IsdpYYDNbc_IzdKcdtxw-ZqY_4)

Definition of done
All of our supported fetchers implement the GetMetadata method and as a result, those attributes are presented by the group by feature.

Please follow the following checklist in the beginning of your work, please comment with a suggested of high level solution. It should include:

- [ ]  Comment describing high level implementation details
- [ ]  Include API and data models
- [ ]  Include assumptions being taken
- [ ]  Provide backward/forward compatibility when changing data model schemas and key constants
- [ ]  Mention relevant individuals with a reason (getting feedback, fyi etc)
- [ ]  Submit a PR for our [technical index](https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/Technical_Index.md) that includes breaking changes/ new features before closing this ticket.

**Comment by ofiriro3** [comment]
Temporarily I put some value in these fields to make the EKS work

**Comment by eyalkraft** [comment]
@tinnytintin10 @amitkanfer 
This issue is about providing the relevant metadata for AWS resources.
The current minimal metadata we provide with each collected resource is:
```
	ID      string `json:"id"`
	Type    string `json:"type"`
	SubType string `json:"sub_type"`
	Name    string `json:"name"`
```
Some questions to be answered here are:
1. What should be the ID for AWS resources? is in the ARN? is it some permutation over it?
2. What should be the types and subtypes? please also refer to casing & spacing and provide exact examples.
3. What should be the name of the resource (probably the AWS resource name)
4. Should we include additional metadata? which?

**Comment by amitkanfer** [comment]
my $0.02, happy to discuss, not set in stone:
> What should be the ID for AWS resources? is in the ARN? is it some permutation over it?

I think we should go with a permutation of it. I also think that we need to have another fields `original_id` that will hold the ARN or the eq. in other cloud providers. Also see my comment [here](https://github.com/elastic/ecs/issues/1725#issuecomment-1156025912).

> What should be the types and subtypes? please also refer to casing & spacing and provide exact examples.
What should be the name of the resource (probably the AWS resource name)

Whatever will help the user to identity the resource... For example. Type could be "Load Balancer", subtype could be "Network Load Balancer" and the name should be the actual name if the resource as it appears in AWS, eg. "Amit's LB".

> Should we include additional metadata? which?

original_id ?

**Comment by tinnytintin10** [comment]
> What should be the ID for AWS resources? is it in the ARN? is it some permutation over it?

This should be the ARN. ARNs uniquely identify AWS resources across all of AWS. @amitkanfer why do you want to use a permutation of it? 

> What should be the types and subtypes? please also refer to casing & spacing and provide exact examples.

this is interesting... as we generally think about cloud resources we will have one general resource type, for example, storage, compute, etc. The "sub-type" can be referred to using the specific service name, for example, s3, ec2, etc. To capture the service name we can use the [`cloud` ECS field set](https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html) (`cloud.service.name` specifically). I don't want to solution too much here, I'll leave that to y'all... but from a product perspective, capturing both this general resource type and specific service name/type will be useful for the user. Look at the diagram below for some sense of what I mean: 

<img width="1784" alt="Screen Shot 2022-06-16 at 07 53 48" src="https://user-images.githubusercontent.com/53792284/174098601-564e8ceb-405d-42cf-ad2e-0bfdbf8e5120.png">

> What should be the name of the resource (probably the AWS resource name)

Where the cloud providers provide us a specific "name" value for the resource. let's use it. But if there isn't a name field/value defined explicitly (i am not sure if we'll run into this) we can default to using a resource's ARN. 

> Should we include additional metadata? which?

I can't think of anything specific atm... but let's just make sure we're leveraging applicable ECS fields where we can- and if we find something is common enough, let's think about introducing it into ECS.

**Comment by amitkanfer** [comment]
> This should be the ARN. ARNs uniquely identify AWS resources across all of AWS. @amitkanfer why do you want to use a permutation of it?

what will be the equivalent for the other clouds? will it be in the same format? will it "look and feel" the same?
For example, in GCP, the fully qualified resource name starts with `//` and looks different than ARN which uses `:`
Whatever we choose, it needs to be consistent. If we want to use the original id, the field name should state that... `original_id`, as opposed to just `id`.

**Comment by amitkanfer** [comment]
GCP: https://cloud.google.com/iam/docs/full-resource-names

**Comment by tinnytintin10** [comment]
> what will be the equivalent for the other clouds? will it be in the same format? will it "look and feel" the same?
For example, in GCP, the fully qualified resource name starts with // and looks different than ARN which uses :
Whatever we choose, it needs to be consistent. If we want to use the original id, the field name should state that... original_id, as opposed to just id.

My point is we should use the native resource id... not introduce anything "new" to the user. It is safe to assume for a customer in GCP, AWS, etc... they will be familiar with the ID format of resources there, let's not confuse them by introducing another abstraction.

**Comment by eyalkraft** [comment]
Nice [resource](https://cloud.google.com/free/docs/aws-azure-gcp-service-comparison) for category/type/subtype for the different services.
