### ISSUE TITLE
Document CIS AWS required permissions

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#716]

**Comment by ari-aviran** [comment]
For CIS AWS the user will need to attach the [`SecurityAudit`](https://console.aws.amazon.com/iam/home#policies/arn:aws:iam::aws:policy/SecurityAudit) IAM policy to the role/user the credentials they provided belongs to.

This is standard in other CSPM products:
- [Datadog](https://docs.datadoghq.com/integrations/amazon_web_services/?tab=roledelegation#cloud-security-posture-management)
- [Aqua Security](https://support.aquasec.com/support/solutions/articles/16000111545-connecting-an-aws-account)

I tested against cloudbeat version 8.7 and on our dev account an admin user gets the same number of findings as a user with the `SecurityAudit` policy attached.

@tinnytintin10 Please make sure to update this in our documentation
