### ISSUE TITLE
[BUG] EKS CIS - When multiple args provided cloudbeat evaluates results incorrectly.

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#719]
**Describe the bug**
EKS configuration fields may be provided through args or kubelet-config.json. When the same field exists both in config file and args, the value of args defines the decision's result.
Currently EKS functional test cases are failing on test-config-2: 

- Rule 3.2.4 Kubelet config readOnlyPort=26492, -read-only-port=0 - evaluation passed instead of failure
- Rule 3.2.7 Kubelet config makeIPTablesUtilChains=FALSE,  --make-iptables-util-chains==TRUE - evaluation failed instead of pass

**Preconditions**
ELK Stack 8.6.0 / 8.7.0 is deployed
Connection to test-config-2 cluster for kubectl is ready

**To Reproduce**

1. Create KSPM integration and select EKS deployment.

2. Deploy Fleet managed agent to test-config-2 cluster.

3. Navigate to Findings and search by rule.tags : "CIS 3.2.4" and host.name : "ip-192-168-89-216.eu-west-2.compute.internal"

4. Navigate to Findings and search by rule.tags : "CIS 3.2.7" and host.name : "ip-192-168-89-216.eu-west-2.compute.internal"

**Expected behavior**
3. For case Kubelet config readOnlyPort=26492, --read-only-port=0 evalutation is failed.
4. For case Kubelet config makeIPTablesUtilChains=FALSE,  --make-iptables-util-chains==TRUE evaluation is passed.

OS: NA
Browser: NA
Kibana Version: 8.6.0 / 8.7.0
Elastic-Agent: 8.6.0 / 8.7.0
EKS Cluster version: V1.23

**Comment by orestisfl** [comment]
@gurevichdmitry if I understand correctly the issue is that the CLI args take precedence over the config file? I think this is kinda the expected and standard behavior for most apps that take CLI arguments, do we want to change that?

**Comment by gurevichdmitry** [comment]
@orestisfl, not exactly, the requirement is that CLI args take precedence over the config file and the issue was that it doesn't happened. But I checked again and it seems like now all is working correctly. The issue can be closed.
