### ISSUE TITLE
DB cache configuration (how to download the DB, when to update and etc...)

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#724]
Currently, we are using the defaults of Trivy regarding the caching/downloading of the DB (`fs` layer).
We need to investigate the possibilities and options of caching/downloading and decide what we need.
This also includes the path of the cache (currently the user's default path `.cache` folder).

**Comment by olegsu** [comment]
Closing, will handle as part of https://github.com/elastic/cloudbeat/issues/697
