### ISSUE TITLE
Debug `chtimes` problem when running on AMD and limit us to running on ARM (yet the CLI runs everywhere)

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#731]
When `Trivy` downloads the database it stores it inside the cache that resides on top of the `fs`.
After downloading the DB it attempts to call `chtimes` as part of the `os` package. To be exact the flow that calls it is the `go-getter` package.
For some reason when running on top of ARM architecture it works without any problems, but when I've attempted to run the same thing on top of AMD64 it did not succeed in running the `chtimes` command:
```
{"log.level":"error","@timestamp":"2023-01-24T10:57:06.553Z","log.logger":"vulnerability","log.origin":{"file.name":"vulnerability/evaluator.go","file.line":117},"message":"VulnerabilityEvaluator.evaluate.NewRunner error: DB error: failed to download vulnerability DB: database download error: download error: failed to download: chtimes /tmp/trivy/db/trivy.db: operation not permitted","service.name":"cloudbeat","ecs.version":"1.6.0"}
```
The weird thing is that this doesn't reproduce when I've attempted to run via CLI.
For some reason running the scanning via CLI works on both architectures.
This needs to be investigated and we need to make sure that we can run on both platforms.

**Comment by amirbenun** [comment]
Update:
When using libbeat to run Cloudbeat, it by default restricts the system calls that the process can invoke using Seccomp.
https://github.com/elastic/beats/blob/3c807b0d6deb3e26e8d99d40d5e264a036cbaca1/libbeat/cmd/instance/beat.go#L465

In libbeat, they have defined various of policies to apply for different OS and architectures and that's the reason we were able to run it on ARM64.
The workaround we can take here is overriding the default policy and allow executing `chtimes` from AMD64 as well.

**Comment by amirbenun** [comment]
To understand what syscall are required for executing `os.Chtimes`, I created a small go app that runs that single command and analyzed its system calls with `strace -c` and these are the results:
```
 ✗ strace -c ./chtimes
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
  0.00    0.000000           0         1           read
  0.00    0.000000           0         1           close
  0.00    0.000000           0        20           mmap
  0.00    0.000000           0       114           rt_sigaction
  0.00    0.000000           0         6           rt_sigprocmask
  0.00    0.000000           0         3           rt_sigreturn
  0.00    0.000000           0         1           madvise
  0.00    0.000000           0         2           clone
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         3           fcntl
  0.00    0.000000           0         1           getrlimit
  0.00    0.000000           0         2           sigaltstack
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           gettid
  0.00    0.000000           0         6           futex
  0.00    0.000000           0         1           sched_getaffinity
  0.00    0.000000           0         1           openat
  0.00    0.000000           0         1           utimensat
------ ----------- ----------- --------- --------- ------------------
100.00    0.000000           0       166           total
```

**Comment by amirbenun** [comment]
Opened a followup task:
- https://github.com/elastic/cloudbeat/issues/1186

**Comment by smriti0321** [comment]
@amirbenun Could you please clarify if the limitation is about CNVM agent running on ARM only or it can scan ARM based images only? cc @benironside

**Comment by amirbenun** [comment]
The limitation is that the CNVM agent that can only run on ARM based instances.
The reason is the default seccomp policy that the elastic-agent is configured on AMD based instances, this policy blocks the  `utimensat` syscall which gets called by trivy, this syscall failure cause the entire CNVM solution to fail.
To clarify, CNVM can scan both ARM and AMD instances.
