### ISSUE TITLE
Vulnerability runner is global instead of being created each cycle from scratch

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#734]
Due to issue:
- https://github.com/elastic/cloudbeat/issues/725
I've resorted to having a single instance of `runner` to work on.
Because whenever I've attempted to recreate an instance of `runner`, I found myself in a deadlock due to locking via `boltdb`.
Initial intentions were to create an instance of `runner` for every cycle from scratch to allow flexibility and avoid global states.

**Comment by oren-zohar** [comment]
Not relevant anymore
