### ISSUE TITLE
Encrypted volumes scanning handling

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#737]
**Motivation**
- Encrypted volumes for EC2 are a common practice that we have to support.
- AWS [docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-creating-snapshot.html) says that snapshots that are taken from encrypted volumes are automatically encrypted.
- The snapshot read operation, [GetSnapshotBlock](https://docs.aws.amazon.com/ebs/latest/APIReference/API_GetSnapshotBlock.html), says that if the specified snapshot is encrypted, you must have permission to use the KMS key that was used to encrypt the snapshot.
- Since the elastic-agent role is dynamically created from a CloudFormation template, it is possible to grant permissions to the KMS key that is used to encrypt the snapshots.
- In [EBS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html) you can find that the default encryption key has an alias `alias/aws/ebs`.
- The last phase will be granting the elastic-agent role access to this key as described [here](https://stackoverflow.com/questions/54430743/how-to-get-an-aws-ssm-key-arn-from-an-alias-using-cloudformation).

**Definition of done**
Update elastic-agent CloudFormation template:
- [ ] Find the key ARN used to encrypt EBS volumes
- [ ] Grant permissions to the elastic-agent role so it could decrypt EBS volumes

**Comment by eyalkraft** [comment]
- duplicate https://github.com/elastic/cloudbeat/issues/733

**Comment by oren-zohar** [comment]
Closing and merging with the [original](https://github.com/elastic/cloudbeat/issues/733)
