### ISSUE TITLE
Security hub does not always have name

### ISSUE THREAD

**Issue by olegsu** [elastic/cloudbeat#743]
**Describe the bug**
When looking at the securityhub findings it sometimes has a name and sometimes it has an empty string

<img width="847" alt="image" src="https://user-images.githubusercontent.com/23185631/218668383-33a598b2-9938-47ab-9fa8-3a134ec73875.png">

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Run AWS CIS

**Expected behavior**
Securityhub should always have a name https://github.com/elastic/cloudbeat/blob/main/resources/providers/awslib/securityhub/securityhub.go#L47

**Comment by kfirpeled** [comment]
1. verify that all findings have resource name in the findings index (not in the latest)
2. verify `rule 4.16` shows up in the findings page
