### ISSUE TITLE
Some cloudtrail have ID and some ARN

### ISSUE THREAD

**Issue by olegsu** [elastic/cloudbeat#744]
**Describe the bug**
When looking at the cloudtrail findings id field, it sometimes hold an ARN and sometimes an ID

<img width="839" alt="image" src="https://user-images.githubusercontent.com/23185631/218669080-4c33a7fa-5795-4299-9e09-44efb56ce8ce.png">

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Run AWS CIS

**Expected behavior**
Should always have an ARN (https://github.com/elastic/cloudbeat/blob/main/resources/providers/awslib/cloudtrail/trail.go#L32)

**Comment by uri-weisman** [comment]
There are two types of resources involved in the process: one is retrieved from the monitoring fetcher and the other one from the logging fetcher. For the monitoring fetcher, an array of all trails is sent for evaluation, so it's not possible to use an AWS ARN as the `resource.id`. Instead, the monitoring fetcher sends only one resource, identified as `cloudtrail-<ACCOUNT_ID>`.

On the other hand, the logging fetcher enhances the cloudtrail resources and sends them individually for evaluation. In this case, it makes sense to use the trail's ARN as the `resource.id`.

To prevent any confusion, it may be helpful to modify the monitoring fetcher's resource sub_type.

**Comment by kfirpeled** [comment]
@uri-weisman can you please elaborate how to verify this ticket?

**Comment by uri-weisman** [comment]
> @uri-weisman can you please elaborate how to verify this ticket?

Nothing that really needs to be verified.
The monitoring resource's subtype has been replaced from `aws-trail` to `aws-multi-trails`.
The resource id is calculated the same way.

**Comment by JordanSh** [comment]
8.7 BC10 verified
there are no cspm findings without ids



![Image](https://user-images.githubusercontent.com/51442161/228528855-32f60dae-55d7-48dd-adf4-ca064fcc81cf.png)
