### ISSUE TITLE
Add region to CSPM findings

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#745]
We want to have the region of a resource in CSPM findings. We should probably use the [`cloud.region`](https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html#field-cloud-region) ECS field.

**Definition of done**
- [ ] A region field is present in every CSPM finding of a resource that is region-bound
- [x] Define a _global_ value and include it on non region specific resources
- [x] Document the field (and the global value) in the technical index
- [x] Add the field to the mapping in the CSP integration

**Comment by eyalkraft** [comment]
Let's also

- [ ] Define a _global_ value and include it on non region specific resources + document it in the technical index

**Comment by Omolola-Akinleye** [comment]
Added a filter query ->  `cloud.region: *` in Discover 
![Image](https://user-images.githubusercontent.com/17135495/235554025-a3d2e5dc-32b6-40ae-af36-721c1cc030d8.png)

Checked mappings in  stack management - logs-cloud_security_posture.findings_latest-default
![Image](https://user-images.githubusercontent.com/17135495/235554438-043686c9-e403-4c87-8b4b-98354eaa4bcb.png)
