### ISSUE TITLE
Cloudbeat ignores add_cluster_id processor configuration

### ISSUE THREAD

**Issue by eyalkraft** [elastic/cloudbeat#750]
**Describe the bug**
Cloudbeat ignores `add_cluster_id` processor configuration, and always activates it wether it's present in the configuration or not.

 The problem is implicitly using the processor always.
the [import](https://github.com/elastic/cloudbeat/blob/main/processor/processors.go#L21) has the [side effect](https://github.com/elastic/cloudbeat/blob/main/processor/add_cluster_id/add_cluster_id.go#L34-L37) of registering the processor.

[slack](https://elastic.slack.com/archives/C0348SPA1RN/p1676308731105339)

**Preconditions**
Agent runs on K8s with CSPM integration installed.

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Run CSPM integration on a deamonset (k8s) agent
2. cluster id is showing in findings

**Expected behavior**
Cloudbeat should only activate the processor if the integration configures it to do so:
YES for KSMP ([eks](https://github.com/elastic/integrations/blob/main/packages/cloud_security_posture/data_stream/findings/agent/stream/eks.yml.hbs#L44-L45) integration for example)
NO for CSPM

**Comment by tehilashn** [comment]
@eyalkraft @kfirpeled @JordanSh - does this impact the user? Will they see this in the flyout or anywhere else?

**Comment by eyalkraft** [comment]
AFAIK
If the user runs the agent on K8s, the flyout tab that shows the raw Json will include cluster_id
idk about the other flyout tabs or the tables.

**Comment by orestisfl** [comment]
Regarding the initial theory regarding `init()`: `processors.RegisterPlugin` only registers the plugin, it doesn't automatically activate it. I've confirmed this locally by running cloudbeat with different `cloudbeat.yml`s. Additionally, other beats use the same pattern, for example: https://github.com/elastic/beats/blob/210f5933d2b4f039a5ac144c6c6cf1609867be1f/libbeat/processors/add_host_metadata/add_host_metadata.go#L38-L39

I tried to reproduce the original issue and I don't seem to be observing the same buggy behavior:

## CSPM integration on a k8s agent

- the raw JSONs in the `logs-cloud_security_posture.findings_latest-default` index do **not** contain the `cluster_id`: 
[cspm_finding.json](https://github.com/elastic/cloudbeat/files/11113298/cspm_finding.json.txt)
- `cluster_id` field is created in the `logs-cloud_security_posture.findings_latest-*` view but no entries match
- same for the findings page

![cspm](https://user-images.githubusercontent.com/5778622/228887383-30da5840-8f8a-46a5-8a6c-854ed2757014.png)
![cspm-findings](https://user-images.githubusercontent.com/5778622/228887539-7fe707c1-c371-4594-8b9b-4eb0c0a3865a.png)


## KSPM integration on a k8s agent

`cluster_id` is present as expected in findings.

![kspm](https://user-images.githubusercontent.com/5778622/228888037-1775922a-28da-4aa1-8b11-c632be3e9099.png)

## cloudbeat running solo on k8s

If configured without the `add_cluster_id` processor, `cluster_id` is not present in raw JSON events, even for k8s events. If the processor is enabled, `cluster_id` is present as expected: [cloudbeat_event.json](https://github.com/elastic/cloudbeat/files/11113306/cloudbeat_event.json.txt)

**Comment by kfirpeled** [comment]
> I think it's worth checking if removing the fields from the mapping will address this point, also for us to gain a better understanding for future work, but with that being said, I think we can live with an empty field in our data view, especially a field that won't affect the dashboard, or our plug-in in any apparent way.

`cluster_id` is being used heavily in our dashboard and findings, removing the mappings will definitely cause issues in Kibana. No need to check that. (If it is just to experiment with mappings better to do so on a custom index)

FYI, in Kibana we handle the use-case it is empty and make our filters accordingly. However, once you'll fix empty values being populated and instead of not sending the field, I urge you to check if that behavior breaks something in kibana.

**Comment by eyalkraft** [comment]
Thanks for the thorough drill down @orestisfl !
I wonder why/how we had the `cluster_id` filed populated for CSPM originally then 🤔

**Comment by orestisfl** [comment]
> The other option is keep investigating the root cause for this behaviour (I would assume it's related to this CSPM fields [mapping file](https://github.com/elastic/integrations/blob/c76d691fdc4cdb78d9352697ee40c65bb0b7b974/packages/cloud_security_posture/data_stream/findings/fields/fields.yml)) and make sure we don't show it as part of our data view.
> 
> I think it's worth checking if removing the fields from the mapping will address this point, also for us to gain a better understanding for future work, but with that being said, I think we can live with an empty field in our data view, especially a field that won't affect the dashboard, or our plug-in in any apparent way.
> 
> I would love to hear your thoughts on this @orestisfl @tehilashn @tinnytintin10

Yes, I tested and removing/renaming the field does *not* create it in the `logs-cloud_security_posture.findings_latest-*` view.

What we could do is to conditionally create the field on the CSPM integration but not on the KSPM one. But I agree that we can live with it and it's not necessarily worth the effort.
