### ISSUE TITLE
Change CSPM collection cycle to 24 hours

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#752]
**Motivation**
Collecting CSPM findings has minor adverse effects on the user:
1. Creates load on the user's cloud services APIs
2. Ships a lot of data to ES

To balance this with the value add of CSPM we have decided that collection should occur every 24 hours.

**Definition of done**
What needs to be completed at the end of this task
- [ ] CSPM benchmarks (CIS AWS) are configured to collect every 24 hours out-of-the-box.
- [ ] KSPM benchmarks (CIS EKS, CIS k8s) are still configured to collect every 4 hours out-of-the-box.

**Out of scope**
Any sort of configuration of the collection cycle value other than setting defaults for CSPM/KSPM.

**Comment by oren-zohar** [comment]
Need to take into account the affect of this change on the transform

**Comment by orouz** [comment]
> Need to take into account the affect of this change on the transform

talked to @kfirpeled and @CohenIdo about this and it seems the current retention policy is set for `26h`, so CSPM period changing to `24h` shouldn't make a difference in this case.

**Comment by kfirpeled** [comment]
Here is my verification report from my testing environment. All data relates to the past 3 days

EKS: cycle happens every 4 hours - 6 different agents (2 clusters, 3 nodes each cluster)
CSPM: 2 cycles so far, 1 deployed agent, in the next 30 minutes I expect the third cycle to happen
K8S Vanilla: only 1 cycle happened in 1 cluster with 2 nodes (kind cluster running on EC2). Agents are up and running

@uri-weisman or someone from @elastic/cloudbeat can please help to investigate that?
Ping me and I'll share with you my environment

**Comment by kfirpeled** [comment]
verified - sorry for the confusion
