### ISSUE TITLE
[CIS AWS] Security hub failed findings are filtered from latest findings index

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#754]
**Describe the bug**
The evaluation of Security Hub resources is done in rule 4.16 and is expected to generate one finding for each region. 
Each Security Hub resource is identified by an AWS ARN, which is created only in regions where the Security Hub is enabled.
If the service is disabled, there is no ARN and the `resource.id` is empty but the transform logic relies on the resource ID to filter resources. 
Consequently, only a single failed resource will be present in the latest findings index.

**To Reproduce**
1. Install an 8.7.0 env.
2. Install the CSPM integration and follow agent installation instructions.

**Expected behavior**
All securityhub failed findings should have an id and appear in the latest findings index.

**Screenshots**
Only 3 findings appear in the latest findings index even though we have 17 enabled regions.
2 passed and only one failed in evaluation.

<img width="1725" alt="Screenshot 2023-02-16 at 14 14 47" src="https://user-images.githubusercontent.com/68195305/219362440-b95c4dff-821a-4658-948b-82b0f3e5cd6a.png">

**Comment by kfirpeled** [comment]
verify that all findings have resource id in the findings index (not in the latest)
