### ISSUE TITLE
Create factory per benchmark

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#756]
**Motivation**
Currently, we include a set of fetchers in the agent configuration to retrieve the necessary resources for benchmark evaluation, Cloudbeat subsequently generates and activates each fetcher.

Since we have determined that users will not have the ability to modify the fetchers list, we can establish a factory for each GCP/AWS/K8s/GKE.
With this approach, it will be possible to get rid of the repetitive code that produces a factory for each fetcher and update the fetcher list in the integration configuration file.

**Definition of done**
- [ ] Remove the fetchers list from the hbs files.
- [ ] Create a single factory per benchmark which will be used by all relevant fetchers.

**Comment by orestisfl** [comment]
Perhaps each benchmark should implement an `interface`? Otherwise it seems that `initBenchmark`, `initEksFactory` and `initK8sFactory` need to live in the same package.

WDYT about this structure?

```
.
└── fetcher
    ├── eks
    │   └── init.go  # initEksFactory()
    ├── init.go  # initBenchmark()
    └── k8s
        └── init.go  # initEksFactory()
```

**Comment by oren-zohar** [comment]
@uri-weisman Is it possible to use your suggestion only for GCP, and then refactor the other benchmarks later?

**Comment by uri-weisman** [comment]
@oren-zohar
We will have to make specific changes to the registry and factory layers.
I expect it to be less time-consuming compared to a complete refactor but it will introduce benchmark notion to areas that were previously agnostic.

I suggest postponing this task until a decision is made regarding the CIS GCP solution.
Certain solutions may not rely on the factory/fetcher/provider layers.
