### ISSUE TITLE
Add creation time to file resource id

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#78]
Motivation

While working on https://github.com/elastic/security-team/issues/3599, we've decided to handle the `creation time` at a later stage.

Definition of done

File resource id should include the `creation time`.

Please follow the following checklist at the beginning of your work, please comment with a suggested high-level solution. It should include:

- [ ]  Comment describing high level implementation details
- [ ]  Include API and data models
- [ ]  Include assumptions being taken
- [ ]  Provide backward/forward compatibility when changing data model schemas and key constants
- [ ]  Mention relevant individuals with a reason (getting feedback, FYI etc)
- [ ]  Submit a PR for our [technical index](https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/Technical_Index.md) that includes breaking changes/ new features before closing this ticket.

**Comment by eyalkraft** [comment]
After syncing on the team sprint planning, seems like there are two paths for this task:
1. Only support linux. This is probably enough for cloudbeat running in a containerized elastic-agent but will require some adaptions for testing locally.
2. Supporting all platforms. This will require completing https://github.com/elastic/cloudbeat/issues/73 as a prerequisite.

The simpler path would be 1 and would probably serve us for a while.

wdyt @tehilashn @tinnytintin10 @amitkanfer @jeniawhite @uri-weisman

**Comment by eyalkraft** [comment]
Could be related
- https://github.com/elastic/security-team/issues/3788

**Comment by tinnytintin10** [comment]
> Only support linux. This is probably enough for cloudbeat running in a containerized elastic-agent but will require some adaptions for testing locally.

This sound like a good first iteration 👍🏾

**Comment by uri-weisman** [comment]
There's another complexity to that.
As we're focusing on Linux, it offers three timestamps for files: time of last access of contents (`atime`), time of last modification of contents (`mtime`), and time of last modification of the inode (metadata) - `ctime`.
Having said that, It appears that some Linux's FS store the creation time ([discussion](https://unix.stackexchange.com/questions/7562/what-file-systems-on-linux-store-the-creation-time)), not all of them, so I'm not sure that counting on this value for uniqueness is the right approach.

We can use `ctime` instead but a file can change its Inode through its lifecycle.
@jeniawhite, @amitkanfer, @tinnytintin10 - wdyt?

**Comment by uri-weisman** [comment]
@amitkanfer  - I agree with you, I think that it's redundant and we can stick with the current implementation.

It seems to me like a product decision, do we want to stick to the same `resource.id` even when some changes apply to the file (for any reason it might be), or do we want a `resource.id` to represent the actual FS resource.

**Comment by amitkanfer** [comment]
@tinnytintin10 what do you think?

**Comment by tehilashn** [comment]
As discussed on the daily - I think this task is redundant and does not need to happen (exactly as Amit described). 
@tinnytintin10 - we are putting it on hold until you'll make a decision.

**Comment by tehilashn** [comment]
closing as we decided not to do it
