### ISSUE TITLE
CSPM config on standalone agent shows secrets in plaintext

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#808]
When configuring CSPM on a standalone agent, the user is asked to copy the `elastic-agent.yml` policy to the host where the Elastic agent is installed. In that policy, if the user connects to a cloud provider with credentials, the credentials are shown in plaintext and sometimes contain secrets (see attached screenshot). 

We should consider replacing these with environment variables and modifying the UI to ask the user to set these environment variables, similar to how the user provides ES credentials.

Screenshot:
<img width="1840" alt="Screenshot 2023-03-22 at 11 26 25" src="https://user-images.githubusercontent.com/94899776/226860205-a70f0929-2d80-49d4-9bc2-3f4babc4d784.png">

**Comment by orestisfl** [comment]
I wonder if there is anything to be done from cloudbeat's side (this repo).

Digging this up a little bit led me to this code in the kibana repo: https://github.com/elastic/kibana/blob/e99119db20c0f6e800c367d1b666950f1b1af65b/x-pack/plugins/fleet/public/components/agent_enrollment_flyout/steps/configure_standalone_agent_step.tsx#L54-L59
which seems to be the place where the message in the screenshot comes from.

Setting the username & password to `${ES_USERNAME}` and `${ES_PASSWORD}` also seems to happen in kibana: https://github.com/elastic/kibana/blob/a38dfe96c900a9b6574564c4d35528aa7c16256a/x-pack/plugins/fleet/server/services/agent_policies/full_agent_policy.ts#L327-L330

One reason that this might have some extra complexity is that the message in the UI needs to be modified dynamically, depending on whether the secret access key is present in the yaml or not.

**Comment by ari-aviran** [comment]
@orestisfl You are right it looks like there isn't much to be done from cloudbeat's side, this ticket is more for discussion on how (/if/when) to tackle this issue
