### ISSUE TITLE
[BUG] CIS AWS Rule 3.4 When CloudTrail integration with CloudWatch is enabled, Cloudbeat returns evaluation result fail

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#809]
**Describe the bug**

When CloudTrail integration with CloudWatch is enabled, Cloudbeat returns evaluation result fail.

![rule-3.4](https://user-images.githubusercontent.com/99176494/226886555-1d8d3037-1486-40d0-8ba8-599b161a858e.png)

Audit: `aws cloudtrail get-trail-status --region us-west-2 --name cloudtrail-ingest-buildsecurity`

**Preconditions**
ELK Stack 8.8 is deployed

**To Reproduce**
1. Create CSPM integration and deploy elastic agent.
2. Navigate to Findings and search by rule.tags: "CIS 3.4" and resource.name: "cloudtrail-ingest-buildsecurity"

**Expected behavior**
Evaluation result is **passed**

 - OS: Amazon Linux
 - Browser: NA
 - Kibana Version: 8.8-SNAPSHOT
 - Elastic-Agent: 8.8-SNAPSHOT

**Comment by Omolola-Akinleye** [comment]
@gurevichdmitry  @jeniawhite  I'm trying to  install CloudTrail Integration.

Here are my steps to install Cloud Trail:
1: Get AWS credentials running
`aws sts get-session-token --serial-number <your-mfa-serial-number> --token-code <your-mfa-token-code>`.
2. Update session token, access key, and secret access key input fields in CloudTrail integration.
3.  Toggle on `Collect CloudTrail logs from CloudWatch`  
4.  Clicked `Save and Continue` button.

 Result is an API Failure:

 `Error installing aws 1.33.3: Encountered 1 errors creating saved objects: [{"type":"search","id":"aws-30ccde50-7397-11ea-a345-f985c61fe654","error":{"isBoom":true,"isServer":false,"data":null,"output":{"statusCode":400,"payload":{"message":"[attributes.sort]: types that failed validation:\n- [attributes.sort.0.0]: array size is [0], but cannot be smaller than [2]\n- [attributes.sort.1.0]: expected value of type [string] but got [Array]: Bad Request","statusCode":400,"error":"Bad Request"},"headers":{}},"type":"unknown"}}]`
<img width="402" alt="Screen Shot 2023-05-02 at 12 06 59 PM" src="https://user-images.githubusercontent.com/17135495/235722896-7ee15d70-c9a2-444d-841a-86adf8dc35ba.png">

Am I missing any steps when installing Cloud Trail Integration?

**Comment by Omolola-Akinleye** [comment]
Actually sorry, I applied the incorrect search query filter. You ignore the comments above.

**Comment by Omolola-Akinleye** [comment]
Fixed Verified. Navigate to `Findings` -> `Configurations` tab and apply search filter `rule.tags: "CIS 3.4" and resource.name: "cloudtrail-ingest-buildsecurity"`. Finding is passing

![Image](https://user-images.githubusercontent.com/17135495/235793858-a8bc94fa-d240-453e-8a0b-8a727a130055.png)
