### ISSUE TITLE
Scale test CSPM for AWS on a large account

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#813]
**Motivation**
We want to ensure cloudbeat is performing properly when using it for CSPM on a large AWS account.

A large account should be of similar size to these specs from product:
Service | Count | Comment
-- | -- | --
AWS Identity and Access Management (IAM) | # user groups: 9, # users: 77, # roles: 723, #policies: 63, #identity providers: 0 | IAM Dashboard in AWS Console should have all these data points
AWS Simple Storage Service (S3) | 391 | S3 Landing page in AWS Console should have this info
Elastic Compute Cloud (EC2) (all regions) | #instances: 12906 #volumes: 13433 | EC2 Global view in AWS Console should have these data points
Relational Database Service (RDS) | 40 | RDS Dashboard in AWS Console should have this info
AWS VPC (all regions) | 50 | EC2 Dashboard or VPC Dashboard in AWS Console should have this info
Security Greoups (all regions) | 398 | EC2 Dashboard in AWS Console should have this info

**Definition of done**
What needs to be completed at the end of this task
- [x] Install CSPM integration for a large AWS account
- [x] Ensure there is no throttling of AWS APIs caused by cloudbeat hitting the API endpoints
- [x] If there is any throttling of AWS APIs, create a followup task for a rate-limiting mechanism inside cloudbeat
- [ ] Inpsect metrics for cloudbeat during and after collection (cpu/memory usage)
- [ ] Document said metrics

**Comment by ari-aviran** [comment]
I have started scale testing CSPM with a large AWS account. My methodology was bringing an internal AWS account to roughly the same number of resources required by the product spec and running cloudbeat CSPM for that AWS account.

**It seems like there are no issues with throttling or API rate limiting from AWS APIs.** Even when running a collection cycle every 30 seconds instead of every 24 hours, there are no throttling issues at all. I did manage to hit API limits when running collection cycles continuously without any pause between them (a collection cycle of 1 second) but this should never be an issue in real world usage.

cloudbeat metrics collection and documentation (CPU/memory usage) TBD.

**Comment by tehilashn** [comment]
This is great news!
btw - I'm sure "real life" scenarios of our customers will expose issues but this is already a good start.  

cc @tinnytintin10 .

**Comment by tinnytintin10** [comment]
> It seems like there are no issues with throttling or API rate limiting from AWS APIs. Even when running a collection cycle every 30 seconds instead of every 24 hours, there are no throttling issues at all. I did manage to hit API limits when running collection cycles continuously without any pause between them (a collection cycle of 1 second) but this should never be an issue in real-world usage.

This is indeed great news!! Thanks for the work on this, Ari 👑

**Comment by ari-aviran** [comment]
From my observations cloudbeat running the CIS AWS benchmark can take up to 200MB of memory during collection for a "large" AWS account, and can use up to 10% CPU (tested on a c5.large EC2 instance). Not sure how/where to document this, looking at other beats' docs I don't see much mention of resource usage... @tinnytintin10 if you have any ideas you can go for it. Closing for now.
