### ISSUE TITLE
[BUG] CIS AWS Rule 5.4 - Cloudbeat evaluates all security groups instead of default ones.

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#815]
**Describe the bug**

Rule CIS AWS 5.4: Ensure the default security group of every VPC restricts all traffic.
Cloudbeat evaluates all security groups custom and defaults.

![Rule-5-4](https://user-images.githubusercontent.com/99176494/227225940-43bfe230-25ab-4ad2-8b18-29fac300ef97.png)

**Preconditions**
ELK Stack 8.8 is deployed

**To Reproduce**
1. Create CSPM integration and deploy elastic agent.
2. Navigate to Findings and search by rule.tags: "CIS 5.4"

**Expected behavior**
Cloudbeat evaluates only default security groups

 - OS: Amazon Linux
 - Browser: NA
 - Kibana Version: 8.8-SNAPSHOT
 - Elastic-Agent: 8.8-SNAPSHOT

**Comment by Omolola-Akinleye** [comment]
Search by `rule.tags: "CIS 5.4"`

![Image](https://user-images.githubusercontent.com/17135495/235789789-d7a03299-8969-4192-9bfd-572500ac3db7.png)
