### ISSUE TITLE
Fleet server becomes unhealthy when running vulnerability management

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#850]
**Background**
What we see so far, is that the fleet server becomes unhealthy when the vulnerability management integration is installed.
First, we need to check if the problem only reproduces when vulnerability management is active or if it reproduces on conditions.
Then, we should understand what's the cause and contact the ingest team if needed.

**Related tasks/epics**
The problem was found during working on the E2E task 
- https://github.com/elastic/cloudbeat/issues/832

**Comment by jeniawhite** [comment]
I've opened a duplicate issue with diagnostics and screenshots:
- https://github.com/elastic/cloudbeat/issues/854
Closing it so we will track them both in this issue.

**Comment by tehilashn** [comment]
Seems like https://github.com/elastic/fleet-server/issues/2479 was done, can we check if this is still happening?

**Comment by amirbenun** [comment]
Fixed by elastic-agent team
