### ISSUE TITLE
Fleet server unhealthy and vulnerability agent missing check-ins

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#854]
**Describe the bug**
When deploying the E2E flow of vulnerability I've noticed that the fleet server after a while becomes unhealthy and sometimes the agent misses check-ins.  
I did not investigate this, so I've attached diagnostics from both of the agents (vulnerability and the fleet agent).

**Preconditions**
Environment state and/or platform-specific configurations.

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Deploy ESS 8.8-SNAPSHOT
2. Deploy vulnerability
3. Wait for a while and hopefully, you will get this error 

**Expected behavior**
The fleet and agent should run fine without any problems

**Screenshots**
<img width="1728" alt="Screen Shot 2023-04-10 at 13 15 11" src="https://user-images.githubusercontent.com/12246907/230889599-ea3a31f1-a962-4b89-8dd5-437419fe6610.png">

**Additional context**
[elastic-agent-diagnostics-2023-04-10T10-56-46Z-00.zip](https://github.com/elastic/cloudbeat/files/11190056/elastic-agent-diagnostics-2023-04-10T10-56-46Z-00.zip)
[elastic-agent-diagnostics-2023-04-10T10-56-55Z-00.zip](https://github.com/elastic/cloudbeat/files/11190057/elastic-agent-diagnostics-2023-04-10T10-56-55Z-00.zip)
[elastic-agent-diagnostics-2023-04-10T10-19-47Z-00.zip](https://github.com/elastic/cloudbeat/files/11190058/elastic-agent-diagnostics-2023-04-10T10-19-47Z-00.zip)

**Comment by jeniawhite** [comment]
Tracked in issue:
- https://github.com/elastic/cloudbeat/issues/850

**Comment by uri-weisman** [comment]
I haven't noticed this warning in a while.
@jeniawhite @amirbenun - can we mark this as verified?
