### ISSUE TITLE
[BUG] Kibana - Findings - Search bar placeholder is incorrect

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#87]
**Describe the bug**
The findings page search bar presents a placeholder value that doesn't exist.

**Preconditions**
Kibana  + ES + CIS k8s integration installed.
Elastic agent deployed on a k8s cluster.

**To Reproduce**
1. Enter Kibana and navigate to the `Cloud Security` section.
2. Go to the findings page.
3. Observe the search bar.

**Expected behavior**
placeholder="Search findings (eg. **rule.section** : "API Server")" 

Instead of:

placeholder="Search findings (eg. **resource.section** : "API Server")" 

**Screenshots**
<img width="1453" alt="Screen Shot 2022-05-09 at 13 13 19" src="https://user-images.githubusercontent.com/68195305/167391511-07ad8e08-907e-4815-a709-13e96dd8c02f.png">

Kibana Version: 8.3.0-SNAPSHOT
BUILD: 52444
COMMIT: 8ace5e47555d4b01a9853c430f7adb4539d2925c

**Comment by kfirpeled** [comment]
@JordanSh please fill attach the pr and close the issue

**Comment by JordanSh** [comment]
https://github.com/elastic/kibana/pull/132201
