### ISSUE TITLE
 Vulnerability document the dev flow

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#873]
**Motivation**
We would like to have documentation on how to develop the vulnerability.
Currently, we do not allow ssh access which means that we cannot replace the cloud beat code, also we cannot pull from the artifacts and we need to pull from snapshots.

Related to:
- https://github.com/elastic/cloudbeat/pull/861

**Comment by amirbenun** [comment]
I think we can close it as a duplicate.
1. We have a documentation ticket here https://github.com/elastic/cloudbeat/issues/833
2. We have a specific ticket about working with SSH here https://github.com/elastic/security-team/issues/6320
