### ISSUE TITLE
[BUG] Kibana - Find (`⌘ + /`) - Cloud security result is missing the security icon

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#88]
**Describe the bug**

Missing security icon in cloud security result when searching for it in kibana's top search bar.

**Preconditions**
Kibana environment with csp plugin enabled

**To Reproduce**

1. Open Kibana
2. Search in top bar search box for `cloud`
3. See `Cloud Security` option

**Expected behavior**
1. Security solution icon is displayed
2. Text `Security / Cloud Security` is displayed

**Screenshots 📸**
<details>
<summary>📸 Screenshot - Security solution options</summary>

<img width="628" alt="Screen Shot 2022-05-09 at 15 23 32" src="https://user-images.githubusercontent.com/61654899/167409943-07f1505f-4ea4-4c32-9749-3f7b8aca1786.png">

</details>

<details>
<summary>📸 Screenshot - Actual</summary>

<img width="634" alt="Screen Shot 2022-05-09 at 15 23 49" src="https://user-images.githubusercontent.com/61654899/167409958-15748fe9-4673-4149-9e06-a78bfe642ef9.png">

</details>

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT `df225b213b188c81888141cee2ec191424fc0649`
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by ari-aviran** [comment]
The text in the search bar can not be changed to `Security / Cloud Security` easily - we'll need to register the plugin as a sub-page in the security solution plugin, this is quite the refactor at this stage of the version. I suggest doing this as part of the security navigation refactor that's going to happen for 8.4

In the meantime, I'll fix the icon, and also in the search bar you do see a `Security` subtitle for our entry, so not that bad:
![Screen Shot 2022-05-24 at 11 44 57](https://user-images.githubusercontent.com/94899776/169990009-675d657d-bb66-4646-900b-271362ddad1d.png)

**Comment by ari-aviran** [comment]
PR https://github.com/elastic/kibana/pull/132771

**Comment by kfirpeled** [comment]
Sure, I agree to continue as you did
