### ISSUE TITLE
[BUG] Kibana - Findings - pagination summary calculation is wrong

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#89]
**Describe the bug**
The pagination summary calculation is not correct when the last page presents fewer records than the `rows per page option`.
By pagination summary calculation I mean - "Showing 31-40 of 640 Findings".
**Preconditions**

Kibana + ES + CIS k8s benchmark integration intalled.
Elastic Agent deployed on a K8s cluster.

**To Reproduce**
1. Open Kibana and navigate to the `Cloud Security` section.
2. Go to the `Findings` page.
3. Click on the `rows per page` dropdown list and choose 100.
4. Click on the last records page.
5. Look at the "Showing x-y of z Findings"

**Expected behavior**
When the last page presents fewer records than the configured value in the `rows per page`  option following is displayed:
"Showing x-y of y Findings", e.g. "Showing 601-640 of 640 Findings" 

Instead of:

"Showing 601-700 of 640 Findings"

**Screenshots**
<img width="485" alt="Screen Shot 2022-05-09 at 17 23 24" src="https://user-images.githubusercontent.com/68195305/167435305-47bd1e7b-db29-41ff-93cf-a79a900b19f5.png">

Kibana Version: 8.3.0-SNAPSHOT
BUILD: 52444
COMMIT: 8ace5e47555d4b01a9853c430f7adb4539d2925c

**Comment by orouz** [comment]
draft PR - https://github.com/elastic/kibana/pull/132203/files (there's a few PRs that need to be merged before it)
