### ISSUE TITLE
Move non-ECS fields from root level event

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#897]
**Motivation**

Currently, having custom (non ECS) fields at the root level of vulnerability is a wrong doing
It can cause conflicts with other integrations

The proposed way for integrations having customized fields is to add them under the package name
In our case, `cloud_security_posture.*`

**Definition of done**
- [ ] Move/remove root level fields like: `type`, `class`, `cluster_id` and make sure cloudbeat's events follow the specified guideline
- [ ] Fields that already exist prior 8.8, for backward compatibility, add to the ingest pipeline rules to remove these fields / move them to the proper place (only if they are not being used in `kibana`)
- [ ] Create follow-up for custom fields we want to be part of ECS
- [ ] Explore if there are more fields that weren't mentioned in DOD

**Out of scope**

- 

**Related tasks/epics**

-

**Comment by Omolola-Akinleye** [comment]
@kfirpeled is additional work needed in Kibana,?  I remember the [bug fix ](https://github.com/elastic/kibana/pull/155206) for calculating the unique transform key.  `vulnerability.package.name`, `vulnerability.package.version`, `vulnerability.package.fix_version` are used in Kibana cc: @opauloh

**Comment by uri-weisman** [comment]
> @kfirpeled is additional work needed in Kibana,? I remember the [bug fix ](https://github.com/elastic/kibana/pull/155206) for calculating the unique transform key. `vulnerability.package.name`, `vulnerability.package.version`, `vulnerability.package.fix_version` are used in Kibana cc: @opauloh

Yeah, I noticed that those fields are omitted from the findings table.
Another option is just adding the `package` object to the root level and keeping the old fields as is for BC.

**Comment by kfirpeled** [comment]
> Another option is just adding the package object to the root level and keeping the old fields as is for BC.

Anything that is not defined as part of ECS should be under `cloud_security_posture.*` and not the root level. That is the new guidance and the purpose of this issue :) 

> @kfirpeled is additional work needed in Kibana,? I remember the https://github.com/elastic/kibana/pull/155206for calculating the unique transform key. vulnerability.package.name, vulnerability.package.version, vulnerability.package.fix_version are used in Kibana

That is a good question, and currently, it is still a middle ground. Custom fields under `vulnerability.*` are a subject for further discussion. If it fits to the ECS, we should keep them there and promote that discussion. If not, we should move them to `cloud_security_posture.*`. However, that is currently a lower priority and out of the scope of this issue.

**Comment by uri-weisman** [comment]
We decided not to remove the fields that are used in the UI just add new ones.
If we'll be able to point our Kibana code to the new fields it will be great but as a security measure, we'll just add new ones and not remove them.

**Comment by kfirpeled** [comment]
@uri-weisman thanks for the update
I suggest duplicating the data for now, having it both in `package.*` and in `vulnerability.package.*`
So don't revert it completely. This will save us time doing the transition in kibana for 8.9
Makes sense?

**Comment by kfirpeled** [comment]
Hi @uri-weisman do we have followup tasks to complete the DOD in 8.9?

**Comment by orestisfl** [comment]
Verified

![image](https://github.com/elastic/cloudbeat/assets/5778622/6789d43a-6c83-4c59-aaf1-5a4c832a4a50)

**Comment by uri-weisman** [comment]
> Hi @uri-weisman do we have followup tasks to complete the DOD in 8.9?

@kfirpeled - no I'll open such for Kibana & Cloudbeat.

**Comment by kfirpeled** [comment]
Yes, thanks @uri-weisman 
Can you say in which `cloudbeat` version `orchestrator.cluster.id` was added? 

And what is the scope of the change? instead of `vulnerability.package` to use `package.*`? and instead of `cluster_id` to use `orchestrator.cluster.id`?

Anything else?

**Comment by uri-weisman** [comment]
> Can you say in which `cloudbeat` version `orchestrator.cluster.id` was added?

`8.8.0`

- https://github.com/elastic/kibana/issues/157674
