### ISSUE TITLE
[BUG] Kibana / Discover / Findings - Missing time filters

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#90]
**Describe the bug**

When going to discover screen and viewing findings, the time filters are missing

**Preconditions**
Kibana environment with csp plugin enabled

**To Reproduce**

1. Install integration `CIS Kubernetes Benchmark` version `0.0.7`
2. Go to discover
3. Switch to findings data views

**Expected behavior**
Filtering by time is enabled.

**Screenshots 📸**

<details>
<summary>Data view with time field 📸</summary>
<img width="940" alt="Screen Shot 2022-05-09 at 17 40 32" src="https://user-images.githubusercontent.com/61654899/167434853-45600275-de92-4597-b7a8-a29274f55f48.png">

</details>

<details>
<summary>Discover when data view has time field defined (with time filter on the top right) 📸</summary>

<img width="1728" alt="Screen Shot 2022-05-09 at 17 55 50" src="https://user-images.githubusercontent.com/61654899/167437591-a286cbd8-5ed4-4343-9428-4f6394439cea.png">

</details>

<details>
<summary>Our integration data view (missing time field tag) 📸</summary>

<img width="961" alt="Screen Shot 2022-05-09 at 17 54 14" src="https://user-images.githubusercontent.com/61654899/167437301-c282692f-d044-4e65-80a7-8609aa33a159.png">

</details>

<details>
<summary>Discover when data view doesn't define time field 📸</summary>
<img width="1728" alt="Screen Shot 2022-05-09 at 17 55 34" src="https://user-images.githubusercontent.com/61654899/167437546-b1e73334-3498-42e2-9f35-2020b2a8eff9.png">

</details>

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT `df225b213b188c81888141cee2ec191424fc0649`
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by tinnytintin10** [comment]
nice! this should be an easy mapping fix, was able to perform this easily: 

![Image](https://user-images.githubusercontent.com/53792284/175972795-30c81d13-cfc7-444e-8ede-8ca27b92d260.png)

**Comment by kfirpeled** [comment]
looks like we need to add `timeFieldName: "@timestamp"` to the index-pattern :)

**Comment by orouz** [comment]
tested on [`58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d`](https://github.com/elastic/kibana/commits/58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d)

time filters in discover are working for our index

**Comment by orouz** [comment]
on a different test i needed to go back to Discover page and for some reason now i don't see the time range filter. 

i've checked with @JordanSh and his cloud env does include the filters. 

we might need to re-open this task and figure out the discrepancies. 

same kibana/integration versions

@gurevichdmitry

**Comment by gurevichdmitry** [comment]
@orouz please try to find the exact scenario when it happens.

**Comment by orouz** [comment]
@gurevichdmitry we should address this next QA cycle. for now it's out of scope.
