### ISSUE TITLE
[BUG] Multi-lines in Failed Findings Table can cause UI problems

### ISSUE THREAD

**Issue by JordanSh** [elastic/cloudbeat#91]
**Describe the bug**
Having multi-lines in the Findings Table Chart makes the rows overflow which causes major problems to the UI.

**Preconditions**
1. Agent installed
2. Cluster Deployed
3. `latest-findings` index is populated by the transform

**To Reproduce**
The easiest way to reproduce is to shrink the browser window horizontally until lines are starting to drop into multi-lines.

**Expected behavior**
Instead of dropping into multi-lines, the table should truncate the text using ellipsis

**Screenshots**
![image](https://user-images.githubusercontent.com/51442161/167449876-d9e5e297-88d2-4d0b-a631-713ef0506176.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Kibana Version: 8.3-SNAPSHOT
 - SHA: df225b213b188c81888141cee2ec191424fc0649

**Comment by kfirpeled** [comment]
@JordanSh please fill attach the pr and close the issue

**Comment by JordanSh** [comment]
- https://github.com/elastic/kibana/pull/132202

**Comment by oren-zohar** [comment]
@kfirpeled @JordanSh I'm not sure if this matches the issue description, but is this a normal behavior? 

https://user-images.githubusercontent.com/85433724/172791096-756ea34c-6e25-47a6-9e8a-87486f975a57.mov
