### ISSUE TITLE
Properties of AWS resources should be in `PascalCase` casing instead of `snake_case`

### ISSUE THREAD

**Issue by ari-aviran** [elastic/cloudbeat#914]
**Motivation**
When users view AWS findings in Kibana, properties of the findings (in fields like `result.evidence` and in general) should be the same as AWS API responses. This helps users audit issues in their environment and remediate them. In AWS API responses the properties of the resources are in `PascalCase`, but in most types of resources we use `snake_case` for the properties when we push them to OPA for evaluation, which leads to findings being generated with `snake_case` properties - which might be confusing for the user.

**Definition of done**
What needs to be completed at the end of this task
- [ ] Change all properties of AWS resources to be `PascalCase`
- [ ] Adjust the rules in @elastic/csp-security-policies with the new casing

**Screenshot**
<img width="1840" alt="Screenshot 2023-05-01 at 7 29 37" src="https://user-images.githubusercontent.com/94899776/235406848-9fa6eed9-56c7-4cc1-ac5f-0cba6cd78fae.png">

**Comment by tehilashn** [comment]
We think this task requires some second thoughts due the following:
1. These fields are not indexed 
2. Seems as if this is how the objects arrive from AWS, should we really change the naming in such cases?
