### ISSUE TITLE
[CNMV] Handle snapshots scanning panics gracefully

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#920]
**Describe the bug**
Cloudbeat panics due to an external package error called `github.com/masahiro331/go-ext4-filesystem`, which is used by trivy.
We panic every time we scan a snapshot of the [this](https://eu-west-1.console.aws.amazon.com/ec2/home?region=eu-west-1#VolumeDetails:volumeId=vol-0924383785ebab906) volume,
The volume is attached to a machine running CNVM (id: i-0cd938d9d0ba2fee0, type: a1.xlarge) deployed a long time ago.

As a result of the panic we don't complete the scanning cycle and the snapshots are not being deleted.

**Preconditions**
ELK + Agent running 8.8.0-SNAPSHOT

**To Reproduce**
Write the exact actions one should perform in order to reproduce the bug.
1. Run ES agent with CNVM integration.
2. Once vol-0924383785ebab906 isscanned, cloudbeat should panic.
3. Observe agent logs for the stack trace.

**Expected behavior**
Cloudbeat should print an error and continue scanning other snapshots.

**Additional context**
[cloudbeat_panic_logs.csv](https://github.com/elastic/cloudbeat/files/11371657/cloudbeat_panic_logs.csv)

**Comment by orestisfl** [comment]
@uri-weisman Not sure if I can verify this, as the linked volume does not exist

**Comment by uri-weisman** [comment]
> @uri-weisman Not sure if I can verify this, as the linked volume does not exist

I see, might be fine to validate that we complete a scanning cycle without cloudbeat being crashed.

**Comment by uri-weisman** [comment]
No panics for the entire cycle.

![Image](https://github.com/elastic/cloudbeat/assets/68195305/421194d3-ae59-487d-b00e-6927e4ec0427)
