### ISSUE TITLE
Revisit PAT for Snyk integration

### ISSUE THREAD

**Issue by orouz** [elastic/cloudbeat#924]
**Motivation**

a placeholder ticket to re-visit PAT requirements for our snyk integration as per [SCA Setup - Snyk & Github integration](https://docs.google.com/document/d/1QgD0Xgxe7dFx-cfSfhfwKjPycTRXzmUfaN9PubBWTlc/edit#)

current token was generated from my account for 1 year. 

**Related tasks/epics**
- https://github.com/elastic/security-team/issues/6319

**Comment by oren-zohar** [comment]
I think this was fixed (not showing your use in the CI check)
