### ISSUE TITLE
Add more data regarding snapshot creation, scanning and encryption

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#928]
**Motivation**
Add more data to our logs.
1. creation time of a snapshot.
2. Scanning time of a snapshot.
3. Is the snapshot encrypted?
4. Volume size

**Definition of done**
Logs contain the above data.

**Comment by orestisfl** [comment]
Verified

![image](https://github.com/elastic/cloudbeat/assets/5778622/1412b2bc-9772-4d56-9ba4-cddbf2c13cfc)
