### ISSUE TITLE
[BUG] Cloudbeat - no results after first installation (delayed for first interval)

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#93]
**Describe the bug**

When installing `cloudbeat` for the first time, it would take up to 4 hours* to see initial results.

\* `4 hours` - it is actually the interval being set for `cloudbeat` to run. Which is currently planned to be 4 hours. And for development purposes set for 30 seconds

**Preconditions**
Kibana environment with csp plugin enabled
`cloudbeat` configured to run every 4 hours instead of 30 seconds (aka development mode)

**To Reproduce**

1. Deploy an agent, with `CIS Kubernetes Benchmark` installed, for the first time on healthy k8s cluster
2. Go to dashboard

**Expected behavior**

Dashboard starts showing results after 5-10 minutes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT `df225b213b188c81888141cee2ec191424fc0649`
 - Endpoint Version:
 - Other Version: 
   - Cloudbeat Version: COMMIT [7e1f1a135fbb3459151232dda34531527291776e](https://github.com/elastic/cloudbeat/commits/7e1f1a135fbb3459151232dda34531527291776e)

**Additional context**

**Comment by amirbenun** [comment]
Fixed by https://github.com/elastic/cloudbeat/pull/143
