### ISSUE TITLE
[CloudFormation] Accept elastic-agent artifact URL as a parameter

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#937]
**Motivation**
As for now, the elastic-agent artifact URL is hard-coded in the CloudFormation template.
It means that to deploy snapshots and BC versions of elastic-agent you will have to use a script to edit the template before deploying.
Eventually, we ended up with two ways to deploy the stack.
1. Production - from Kibana using the default elastic-agent artifact (only applies for released versions)
2. Development - using a script that modifies the template before it deploys
Of course, all the developers are using the script and the therefore the production behavior could not be tested until the release.

Instead we could accept the elastic-agent artifact URL as a parameter, then when clicking the "Deploy with CloudFormaiton" link on Kibana, users will be redirected to their AWS console and they will be able to modify the elastic-agent URL themselves.

**Definition of done**
- [x] Add a new parameter to the CFT `ElasticArtifactServer` which will be used to download elastic-agent
- [x] On the vuln-mgmt integration, populate its value with `https://artifacts.elastic.co/downloads/beats/elastic-agent/`
- [x] Remove the dev parameters `PRE_RELEASE` and `SHA` the dev scripts under `deploy/cloudfromation`
- [x] Update `deploy/cloudfromation/README.md`

**Out of scope**

**Related tasks/epics**
- https://github.com/elastic/cloudbeat/pull/907

**Comment by orestisfl** [comment]
Verified

![image](https://github.com/elastic/cloudbeat/assets/5778622/84509099-47b9-4fb7-a2d3-be94ac50301e)
