### ISSUE TITLE
[BUG] Kibana - Findings - when distribution bar refreshs it blanks the previous results

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#94]
**Describe the bug**

When viewing findings, every action makes the whole page to refresh and blanks the current results.
Although they were a moment ago there.

**Preconditions**
Kibana environment with csp plugin enabled
Agent installed that generates findings

**To Reproduce**

1. Go to findings page
2. Move to next page
3. Change page size

**Expected behavior**
From step 2 forward, the distribution bar shows the results without clearing them.

**Screenshots**
<details>
<summary>📹 Video capturing the refresh to distribution bar 📹</summary>

https://user-images.githubusercontent.com/61654899/167471308-5e66ed74-09b6-4ef5-90b5-83210404c0d7.mov

</details>

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT: [df225b213b188c81888141cee2ec191424fc0649](https://github.com/elastic/kibana/commits/df225b213b188c81888141cee2ec191424fc0649)
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by tinnytintin10** [comment]
While doing a refresh, what happens if there is an error? What will the user see? and will we be able to revert them back to a previous view? 

Questions worth thinking about when implementing the fix.

**Comment by ari-aviran** [comment]
@kfirpeled this does not reproduce in the latest version, attached a video:



https://user-images.githubusercontent.com/94899776/169992757-40f5b70d-ed0b-4ad6-8ddd-9273a08f4d48.mov


Closing this issue
