### ISSUE TITLE
[BUG] Kibana - Findings flyout - Switching tabs does not reset scroll position

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#95]
**Describe the bug**

In the findings flyout, it appears that all the tabs share the same scrolling position. Which is not expected.

**Preconditions**
Kibana environment with csp plugin enabled
Agent installed that generates findings

**To Reproduce**
1. Open a finding flyout
2. Scroll down
3. Switch to `Resource` tab

**Expected behavior**
Scroll position is set to the beginning of the tab

Note: it does not reproduce in `JSON` tab

**Screenshots**

<details>
<summary>Video capturing the scroll position is being shared between `Remediation` and `Resource` tabs 📹</summary>

https://user-images.githubusercontent.com/61654899/167472618-fcf55013-afa9-488f-844b-10bb8334c68a.mov

</details>

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT: [df225b213b188c81888141cee2ec191424fc0649](https://github.com/elastic/kibana/commits/df225b213b188c81888141cee2ec191424fc0649)
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by orouz** [comment]
this is the [native](https://elastic.github.io/eui/#/layout/flyout) behaviour:
1. open the flyout
2. scroll down in Tab1
3. go to Tab2
4. same scroll position

we can workaround it if needed (set `scrollTop` manually), but tbh IMO if any this fix belongs to upstream.

@kfirpeled wdyt?

**Comment by kfirpeled** [comment]
I see in the EUI demo it is the native behaviour, in that case we should bring this up in their slack channel.

If that is intended to behave like this, no need to solve this ticket.

@orouz can you bring this subject to the eui team and check if it is intended or not? and out of curiosity what is their rational for working like that?

**Comment by kfirpeled** [comment]
Also, I've played with their demojs and it looks they don't render a different page for the tab.
Is this the right way to use EuiTabs?

**Comment by orouz** [comment]
i think the scroll position doesn't reset automatically just because all tabs share the same scrollable div. doesn't look like there's a rationale behind this decision, but i'll ask. 

regarding proper usage of `EuiTabs`, yeah, i think what we're doing is fine. note that the "complicated flyout" example re-uses the same html for both tabs, which isn't the case for us.

**Comment by orouz** [comment]
i'm not sure what this demo is supposed to demonstrate, there is no scrolling in either tabs. 
lets talk about this IRL. 

in anyway, this demo shows how the current tab is displayed by uitilizing  `display: none`, we just don't render it to begin with. it's identical behaviour AFAIK.

**Comment by kfirpeled** [comment]
Hey I've attached a video, you can see on the right the scroll position being changed

https://user-images.githubusercontent.com/61654899/172594111-369cdcf4-352c-4276-b134-ebed97105422.mov

**Comment by orouz** [comment]
ah! ok i see now, yeah. if we don't share `EuiBodyFlyout` across renders, the scroll position won't be shared too. good catch! 
PR - https://github.com/elastic/kibana/pull/133865

**Comment by CohenIdo** [comment]
Verification passed. using Kibana Commit sha: 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d
