### ISSUE TITLE
CNVM documentation - touch ups

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#953]
**Summary**
We currently have two documents for CNVM, one in the [integration](https://github.com/elastic/integrations/tree/main/packages/cloud_security_posture/docs), and one, more complete in [elastic docs hub](https://security-docs_3162.docs-preview.app.elstc.co/guide/en/security/master/vuln-management-overview.html). Before releasing we need to make sure to update to all of the latest relevant information we discovered after the feature freeze.

- [x] Add VM images to the integration preview
- [x] Add supported VM file system types - see https://aquasecurity.github.io/trivy/v0.35/docs/vm/
- [x] Document used Trivy version (0.35 for 8.8)
- [x] Add CloudFormation context/link (?) - I would suggest adding a cloudformation deployment section
- [x] Communicate to the user that the integration will only scan only the deployed region
- [x] Add missing screenshots

![Image](https://user-images.githubusercontent.com/85433724/237087691-06756225-b8c2-4394-bb5d-46fbc0345aa8.png)

**Comment by tehilashn** [comment]
@nick-alayil - what's the status of this task?
