### ISSUE TITLE
[Cloud Security] Failed to deploy cloudformation on `eu-north-1` (Stockholm)

### ISSUE THREAD

**Issue by JordanSh** [elastic/cloudbeat#954]
Cloud formation deployment is failing when trying to deploy on `eu-north-1` (Stockholm) using the `just deploy-cloudformation` script

version: 8.8.0 BC1
cloud env: https://qa-cycle.kb.us-west2.gcp.elastic-cloud.com:9243/app/home#/
username: elastic
password: https://p.elstc.co/paste/NQtkW0Bc#bFth1p63BjUQmBJ02Tg36JyyLORFSolwjxyJQUC0P0F (expires June 3rd)

Cloud formation stack error:
<img width="1434" alt="image" src="https://github.com/elastic/cloudbeat/assets/51442161/640da3a3-0d0d-4c26-8bc8-95386a5fc198">

`.env` file configurations:
```
STACK_NAME="yardenqabc18805"
FLEET_URL="https://651ba413510b43f7abd0589fd76b5818.fleet.us-west2.gcp.elastic-cloud.com:443"
ENROLLMENT_TOKEN="<hidden>"
ELASTIC_AGENT_VERSION="8.8.0" # 8.8.0 | 8.8.0-SNAPSHOT

DEV.KEY_NAME="yarden-qa-8.8-bc1" # Your EC2 key for SSH
DEV.ALLOW_SSH=false
DEV.PRE_RELEASE=true # Set to true in order to replace the artifact URL with a pre-release version (BC or snapshot)
DEV.SHA="1da9bb67" # A specific SHA of a pre-release artifact (on SNAPSHOT versions you can leave empty to take the latest)
```

**Comment by oren-zohar** [comment]
Thank you for reporting this @JordanSh! @amirbenun found out is happening since our default instance type is not supported in this region (and in more regions from a quick check). We changed the [instance type in 8.9](https://github.com/elastic/cloudbeat/pull/923/files) to a newer version that is supported by more regions (for a full list you can check [Supported instance types](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-supported-instance-types.html)) but is also not a complete list. @tehilashn do you think we need to backport it?

**Comment by amirbenun** [comment]
I would recommend to backport the changes to 8.8 as the change of `a1` to `c6g` is an improvement either way.
In that case we should document that `c6g` instance family is not available in `eu-central-2` and `af-south-1`.

**Comment by amirbenun** [comment]
Yes, you are right, moving to the `c6g` instance family will still not work globally.
I will start with backporting https://github.com/elastic/cloudbeat/pull/923/ to 8.8.
Then as a long term solution we want to be able to deploy vulnerability management in all regions.
Suggested solution:
1. Check if there is a single instance family that is supported globally and it run cloudbeat + trivy without crashing.
2. If we can't find one, we can have a map between the region and the available instance types that we offer to the user.

**Comment by amirbenun** [comment]
It works on `eu-north-1` with the `c6g` instance family.

**Comment by tehilashn** [comment]
@amirbenun - why did we close this task?
I thought we'll start with the backport but we also need to find a [solution](https://github.com/elastic/cloudbeat/issues/954#issuecomment-1540359953) for the two regions that it's not supported in.  
where are we tracking this?

**Comment by amirbenun** [comment]
Yes, I verified it right after I released the new integration.
