### ISSUE TITLE
[BUG] Kibana - Findings - Not showing results when updating search filters on page greater than 1

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#96]
**Describe the bug**

In the findings page, the user get `There are no Findings` message while the distribution bar shows there are findings to show.

**Preconditions**
Kibana environment with csp plugin enabled
Agent installed that generates findings

**To Reproduce**

1. Go to findings page
2. Navigate to last page
3. Update the filter to show less results

**Expected behavior**
When updating the search filters the user should be always navigated to the first page

**Screenshots**

<details>
<summary>Video capturing how the issue is being reproduced 📹</summary>

https://user-images.githubusercontent.com/61654899/167473863-48374f78-9336-433a-a7c1-a6fbe64c401f.mov

</details>

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT: [df225b213b188c81888141cee2ec191424fc0649](https://github.com/elastic/kibana/commits/df225b213b188c81888141cee2ec191424fc0649)
 - Endpoint Version:
 - Other Version: 

**Additional context**

**Comment by ari-aviran** [comment]
PR: https://github.com/elastic/kibana/pull/132778
