### ISSUE TITLE
[CloudFormation] AWS instance family exploration

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#969]
### Motivation
We recently saw that the instance family that we use has a great effect on the solution. 
1. The `a1` instance family caused problems where the agent became unhealthy - https://github.com/elastic/security-team/issues/6338
2. Both `a1` and `c6g` families are not available in all regions which caused the deployment to fail - https://github.com/elastic/cloudbeat/issues/954

We need to further investigate what instance family (or more than one)  we need to use.

### Definition of done
Option 1:
- [ ] Find a suitable instance family that is strong enough to run elastic-agent and it is available in all regions
- [ ] Replace the CloudFormation template to use that family

Option 2:
- [ ] Find a composition of instance families that are all strong enough to run elastic-agent and together they cover al the regions
- [ ] Introduce a map in the CloudFormation template that based on the region we offer the supported instance family

### Restriction
As a reminder we are still limited to use ARM based instances
- https://github.com/elastic/cloudbeat/issues/731

**Comment by amirbenun** [comment]
To narrow down the options:
- Since our instances need to have a graviton processor, the suffix should be `g`.
- Instead of using a compute optimized instances (`c` prefixed) we should use the general purpose (`m` prefixed)

I think `m6g` will suit best for our needs so I would start with checking its availability in all regions. 
If `m6g` is not available in all regions, I would try to use an older generation, `m5g`, where it's missing.

Resources:
- Instance type naming convention - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html. 
- Instance types specs - https://aws.amazon.com/ec2/instance-types/

**Comment by amirbenun** [comment]
BTW, you can use https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-supported-instance-types.html to check for availability. I think that `m6g` is a good match for us 😄

**Comment by mitodrummer** [comment]
Verified instance type is now m6g family.
![Image](https://github.com/elastic/cloudbeat/assets/16198204/29d569a3-b36c-4aa6-b5c4-9fe6f0c2fd0c)
