### ISSUE TITLE
[CNVM] Index vulnerable resource fields

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#983]
### Motivation
Cloudbeat holds a lot of information about the vulnerable resource that it doesn't even ship to ES.
As a first step, cloudbeat should index those fields compliant with ECS where possible.
Existing ECS fields:
```
cloud.service.name: AWS EC2 | AWS EKS // requires an ingest pipeline for 8.9
cloud.machine.type: c6g.xlarge
cloud.availability_zone
cloud.region
host.architecture
host.os.platform
```

Non ECS fields (consider contributing):
```
cloud.machine.authentication.key // EC2 key name
cloud.machine.launch_time
cloud.machine.Image
cloud.tags // EC2 tags
Network interfaces: (private ip, public ip, mac address)
Security groups: (name, id)
```

### Definition of done
- [ ] Update the technical index accordingly
- [ ] Send the new fields as part of the vulnerability event
- [ ] Update the CNVM integration to map the new fields
- [ ] Add ingest pipeline for 8.8 to set `cloud.service.name` as `AWS EC2`

### Out of scope
- Add the new fields into ECS
- Any changes on kibana

### Related tasks/epics
- https://github.com/elastic/kibana/issues/158074

**Comment by amirbenun** [comment]
@CohenIdo suggested to add the scan duration as part of the vulnerability event.
This can be done as part of this task.
One implementation option is to send the following ECS fields:
```
process.start
process.end
```

**Comment by eyalkraft** [comment]
I think for `image` we should consider using the [container namespace](https://www.elastic.co/guide/en/ecs/current/ecs-container.html#field-container-image-name)

**Comment by eyalkraft** [comment]
@amirbenun
`process` is for computer process specifically (for example it has `proccess.pid`) so I don't think it fits for scan duration.

**Comment by amirbenun** [comment]
@oren-zohar @jeniawhite 
As discussed, we want to have the fields as follow:
Network fields should remain on the root:
`network.public_ip`
`network.private_ip`
`network.mac_address`

Security fields should move under `cloud`:
`cloud.security_groups.group_id`
`cloud.security_groups.group_name`
