### ISSUE TITLE
Vulnerability scanner won't finish

### ISSUE THREAD

**Issue by amirbenun** [elastic/cloudbeat#998]
**Describe the bug**
On CNVM, the vulnerabilities scanner never finishes it job (or so it seems from the logs). It results with no vulnerabilities in kibana even when the integration is installed and running for a while.

**Preconditions**
elastic-agent 8.9.0-SNAPSHOT

**To Reproduce**
Write the exact actions one should perform to reproduce the bug.
1. Install CNVM
2. Wait (forever)
3. No vulnerabilities were reported

**Expected behavior**
1. Get vulnerabilities

**Comment by amirbenun** [comment]
To keep main functioning, I opened a PR to revert the commit: https://github.com/elastic/cloudbeat/pull/1009.
I will keep checking what causes the problem and open a new PR with those changes fixed.

**Comment by amirbenun** [comment]
I found the cause of the vulnerabilities DB deadlock.
This code bloxk is a section of `artifacts.Run` in trivy:
```
	r, err := NewRunner(ctx, opts)
	if err != nil {
		if errors.Is(err, SkipScan) {
			return nil
		}
		return xerrors.Errorf("init error: %w", err)
	}
	defer r.Close(ctx)
```

The first time we call `artifacts.Run` we only want to download the DB, therefore `DownloadDBOnly` flag is passed, next, the `NewRunner` call will return a `SkipScan` error. This chain of events causes the runner will never get closed.

**Comment by eyalkraft** [comment]
Is this bugfix an opportunity for using (local) Trivy client/server?
https://aquasecurity.github.io/trivy/v0.18.3/modes/client-server/

Or should we consider that separately in a later stage?

**Comment by amirbenun** [comment]
This is a bug in trivy, it doesn't free resources in that edge case.
For now, we can solve the bug in trivy / keep workaround it as we did before.
I don't think it's an opportunity to use DB server, we should consider it separately and probably have a proper discussion before we do that.

**Comment by amirbenun** [comment]
Since the commit was reverted, I am closing the ticket, next steps will be delivered as part of the original ticket:
- https://github.com/elastic/cloudbeat/issues/697
